-- ═════════════════════════════════════════════════════════════════════════════
-- FIXEO ENTERPRISE — 7C.15A.6
-- ENTERPRISE INVITATION CONTROL PLANE
-- PRODUCTION MIGRATION — STATIC AUDIT PASS — PRE-APPLY PASS
--
-- HARDENING THROUGH DRAFT v3
--   • invitation token is generated by PostgreSQL, never supplied by client
--   • identity resolution / acceptance uses auth.users as email source of truth
--   • all mutation RPCs use the same lock order: account → invitation → member
--   • removed memberships can be safely re-used for a new invitation
--   • stale pending invitations are atomically expired before re-invitation
--   • expiry also retires any matching invited membership
--   • token_hash is never client-readable (column-level SELECT allowlist)
--   • email syntax check uses strpos(), not POSITION special syntax
--   • invitation expiry is now explicitly audited
--   • auth.users UUID resolution no longer relies on MIN(uuid)
--   • acceptance can safely reactivate a removed membership
--
-- CONTRACT
--   • owner/admin can create Enterprise invitations by email
--   • pending invitations are tokenized; only SHA-256 token hashes are stored
--   • existing FIXEO users receive/re-use an enterprise_members row as invited
--   • unknown users remain only in enterprise_invitations until authentication
--   • acceptance is self-service and bound to auth.uid() + auth.users.email
--   • owner/admin can revoke pending invitations
--   • expired/revoked invitations cannot activate membership
--   • no physical enterprise_members DELETE
--   • no outbound email provider is implemented here
--
-- VALIDATION STATUS
--   Static audit: PASS (22/22).
--   Production READ-ONLY pre-apply: PASS (26/26).
--   Authorized production migration candidate.
-- ═════════════════════════════════════════════════════════════════════════════

BEGIN;


-- ═════════════════════════════════════════════════════════════════════════════
-- SECTION 1 — INVITATION STORAGE
-- ═════════════════════════════════════════════════════════════════════════════

CREATE TABLE public.enterprise_invitations (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),

  enterprise_id uuid NOT NULL,
  email_normalized text NOT NULL,
  role text NOT NULL,

  invited_by uuid NOT NULL,
  target_user_id uuid NULL,

  token_hash text NOT NULL,

  status text NOT NULL DEFAULT 'pending',

  expires_at timestamptz NOT NULL,
  accepted_at timestamptz NULL,
  accepted_by uuid NULL,
  revoked_at timestamptz NULL,
  revoked_by uuid NULL,

  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),

  CONSTRAINT enterprise_invitations_enterprise_fk
    FOREIGN KEY (enterprise_id)
    REFERENCES public.enterprise_accounts(id)
    ON UPDATE CASCADE
    ON DELETE CASCADE,

  CONSTRAINT enterprise_invitations_invited_by_fk
    FOREIGN KEY (invited_by)
    REFERENCES public.users(id)
    ON UPDATE CASCADE
    ON DELETE RESTRICT,

  CONSTRAINT enterprise_invitations_target_user_fk
    FOREIGN KEY (target_user_id)
    REFERENCES public.users(id)
    ON UPDATE CASCADE
    ON DELETE SET NULL,

  CONSTRAINT enterprise_invitations_accepted_by_fk
    FOREIGN KEY (accepted_by)
    REFERENCES public.users(id)
    ON UPDATE CASCADE
    ON DELETE SET NULL,

  CONSTRAINT enterprise_invitations_revoked_by_fk
    FOREIGN KEY (revoked_by)
    REFERENCES public.users(id)
    ON UPDATE CASCADE
    ON DELETE SET NULL,

  CONSTRAINT enterprise_invitations_email_chk
    CHECK (
      email_normalized = lower(btrim(email_normalized))
      AND char_length(email_normalized) BETWEEN 3 AND 320
      AND strpos(email_normalized,'@') > 1
    ),

  CONSTRAINT enterprise_invitations_role_chk
    CHECK (
      role IN (
        'admin',
        'operations_manager',
        'site_manager',
        'reporter',
        'viewer'
      )
    ),

  CONSTRAINT enterprise_invitations_status_chk
    CHECK (status IN ('pending','accepted','revoked','expired')),

  CONSTRAINT enterprise_invitations_token_hash_chk
    CHECK (token_hash ~ '^[0-9a-f]{64}$'),

  CONSTRAINT enterprise_invitations_expiry_chk
    CHECK (expires_at > created_at),

  CONSTRAINT enterprise_invitations_terminal_state_chk
    CHECK (
      (
        status = 'pending'
        AND accepted_at IS NULL
        AND accepted_by IS NULL
        AND revoked_at IS NULL
        AND revoked_by IS NULL
      )
      OR
      (
        status = 'accepted'
        AND accepted_at IS NOT NULL
        AND accepted_by IS NOT NULL
        AND revoked_at IS NULL
        AND revoked_by IS NULL
      )
      OR
      (
        status = 'revoked'
        AND accepted_at IS NULL
        AND accepted_by IS NULL
        AND revoked_at IS NOT NULL
        AND revoked_by IS NOT NULL
      )
      OR
      (
        status = 'expired'
        AND accepted_at IS NULL
        AND accepted_by IS NULL
        AND revoked_at IS NULL
        AND revoked_by IS NULL
      )
    )
);

CREATE UNIQUE INDEX enterprise_invitations_token_hash_uq
  ON public.enterprise_invitations(token_hash);

CREATE UNIQUE INDEX enterprise_invitations_one_pending_email_uq
  ON public.enterprise_invitations(enterprise_id, email_normalized)
  WHERE status = 'pending';

CREATE INDEX idx_enterprise_invitations_enterprise_status
  ON public.enterprise_invitations(enterprise_id, status, created_at DESC);

CREATE INDEX idx_enterprise_invitations_target_user
  ON public.enterprise_invitations(target_user_id, status)
  WHERE target_user_id IS NOT NULL;

CREATE TRIGGER enterprise_invitations_updated_at
BEFORE UPDATE ON public.enterprise_invitations
FOR EACH ROW
EXECUTE FUNCTION public.update_updated_at();


-- ═════════════════════════════════════════════════════════════════════════════
-- SECTION 2 — RLS / CLIENT READ ALLOWLIST
-- No direct client mutation path. token_hash is never selectable by clients.
-- ═════════════════════════════════════════════════════════════════════════════

ALTER TABLE public.enterprise_invitations ENABLE ROW LEVEL SECURITY;

CREATE POLICY ei_deny_anon
ON public.enterprise_invitations
FOR ALL
TO anon
USING (false)
WITH CHECK (false);

CREATE POLICY ei_fixeo_admin_all
ON public.enterprise_invitations
FOR ALL
TO authenticated
USING (fixeo_private._fixeo_is_admin())
WITH CHECK (fixeo_private._fixeo_is_admin());

CREATE POLICY ei_managers_select
ON public.enterprise_invitations
FOR SELECT
TO authenticated
USING (
  fixeo_private._fixeo_is_enterprise_manager(enterprise_id)
);

CREATE POLICY ei_self_select
ON public.enterprise_invitations
FOR SELECT
TO authenticated
USING (
  target_user_id = auth.uid()
);

REVOKE ALL
ON TABLE public.enterprise_invitations
FROM PUBLIC, anon, authenticated;

GRANT SELECT (
  id,
  enterprise_id,
  email_normalized,
  role,
  invited_by,
  target_user_id,
  status,
  expires_at,
  accepted_at,
  accepted_by,
  revoked_at,
  revoked_by,
  created_at,
  updated_at
)
ON public.enterprise_invitations
TO authenticated;


-- ═════════════════════════════════════════════════════════════════════════════
-- SECTION 3 — AUDIT VOCABULARY
-- ═════════════════════════════════════════════════════════════════════════════

ALTER TABLE public.enterprise_audit_events
  DROP CONSTRAINT enterprise_audit_events_event_type_chk;

ALTER TABLE public.enterprise_audit_events
  ADD CONSTRAINT enterprise_audit_events_event_type_chk
  CHECK (
    event_type IN (
      'member.role_updated',
      'member.status_updated',
      'site.created',
      'site.updated',
      'site.status_updated',
      'request.created',
      'account.created',
      'account.updated',
      'member.invited',
      'member.invitation_accepted',
      'member.invitation_revoked',
      'member.invitation_expired'
    )
  );

ALTER TABLE public.enterprise_audit_events
  DROP CONSTRAINT enterprise_audit_events_target_type_chk;

ALTER TABLE public.enterprise_audit_events
  ADD CONSTRAINT enterprise_audit_events_target_type_chk
  CHECK (
    target_type IN (
      'enterprise_member',
      'enterprise_site',
      'service_request',
      'enterprise_account',
      'enterprise_invitation'
    )
  );


-- ═════════════════════════════════════════════════════════════════════════════
-- SECTION 4 — CREATE INVITATION
--
-- Token generation:
--   raw token = 32 cryptographically-random bytes encoded as hex (256 bits)
--   stored value = SHA-256(raw token), hex-encoded
--   raw token is returned exactly once to the authorized creator so a trusted
--   application/backend can deliver it later. It is never persisted.
--
-- Identity resolution:
--   auth.users.email is authoritative.
--   Because normalized-email uniqueness is not guaranteed by the discovered
--   schema, exactly one normalized auth.users match is required.
-- ═════════════════════════════════════════════════════════════════════════════

CREATE OR REPLACE FUNCTION public.create_enterprise_invitation(
  p_enterprise_id uuid,
  p_email text,
  p_role text,
  p_expires_at timestamptz
)
RETURNS jsonb
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path TO ''
AS $function$
DECLARE
  v_caller_id uuid;
  v_caller_role text;
  v_caller_status text;

  v_email text;

  v_auth_match_count integer;
  v_auth_user_id uuid;
  v_public_user_exists boolean;

  v_existing_member_id uuid;
  v_existing_member_status text;

  v_old_invitation_id uuid;
  v_old_target_user_id uuid;
  v_old_member_id uuid;
  v_old_member_status text;

  v_raw_token text;
  v_token_hash text;

  v_invitation_id uuid;
  v_member_id uuid;
BEGIN
  v_caller_id := auth.uid();

  IF v_caller_id IS NULL THEN
    RETURN pg_catalog.jsonb_build_object('ok',false,'reason','unauthenticated');
  END IF;

  v_email := pg_catalog.lower(pg_catalog.btrim(p_email));

  IF v_email IS NULL
     OR pg_catalog.char_length(v_email) < 3
     OR pg_catalog.char_length(v_email) > 320
     OR pg_catalog.strpos(v_email,'@') <= 1
  THEN
    RETURN pg_catalog.jsonb_build_object('ok',false,'reason','invalid_email');
  END IF;

  IF p_role IS NULL
     OR p_role NOT IN (
       'admin',
       'operations_manager',
       'site_manager',
       'reporter',
       'viewer'
     )
  THEN
    RETURN pg_catalog.jsonb_build_object('ok',false,'reason','invalid_role');
  END IF;

  IF p_expires_at IS NULL
     OR p_expires_at <= pg_catalog.now()
     OR p_expires_at > pg_catalog.now() + interval '30 days'
  THEN
    RETURN pg_catalog.jsonb_build_object('ok',false,'reason','invalid_expiry');
  END IF;

  -- LOCK ORDER #1: enterprise account.
  PERFORM ea.id
  FROM public.enterprise_accounts ea
  WHERE ea.id = p_enterprise_id
  FOR UPDATE;

  IF NOT FOUND THEN
    RETURN pg_catalog.jsonb_build_object('ok',false,'reason','enterprise_not_found');
  END IF;

  SELECT em.role, em.status
  INTO v_caller_role, v_caller_status
  FROM public.enterprise_members em
  WHERE em.enterprise_id = p_enterprise_id
    AND em.user_id = v_caller_id;

  IF NOT FOUND THEN
    RETURN pg_catalog.jsonb_build_object('ok',false,'reason','not_a_member');
  END IF;

  IF v_caller_status <> 'active' THEN
    RETURN pg_catalog.jsonb_build_object('ok',false,'reason','caller_not_active');
  END IF;

  IF v_caller_role NOT IN ('owner','admin') THEN
    RETURN pg_catalog.jsonb_build_object('ok',false,'reason','forbidden');
  END IF;

  -- LOCK ORDER #2: stale/current invitation for this Enterprise+email.
  SELECT ei.id, ei.target_user_id
  INTO v_old_invitation_id, v_old_target_user_id
  FROM public.enterprise_invitations ei
  WHERE ei.enterprise_id = p_enterprise_id
    AND ei.email_normalized = v_email
    AND ei.status = 'pending'
  ORDER BY ei.created_at DESC
  LIMIT 1
  FOR UPDATE;

  IF FOUND THEN
    IF (
      SELECT ei.expires_at
      FROM public.enterprise_invitations ei
      WHERE ei.id = v_old_invitation_id
    ) > pg_catalog.now()
    THEN
      RETURN pg_catalog.jsonb_build_object(
        'ok',false,
        'reason','invitation_pending'
      );
    END IF;

    -- Expire stale pending invitation.
    UPDATE public.enterprise_invitations
    SET status = 'expired',
        updated_at = pg_catalog.now()
    WHERE id = v_old_invitation_id;

    -- LOCK ORDER #3: membership. Retire only an invited membership associated
    -- with the same resolved target. No physical DELETE.
    IF v_old_target_user_id IS NOT NULL THEN
      SELECT em.id, em.status
      INTO v_old_member_id, v_old_member_status
      FROM public.enterprise_members em
      WHERE em.enterprise_id = p_enterprise_id
        AND em.user_id = v_old_target_user_id
      FOR UPDATE;

      IF FOUND AND v_old_member_status = 'invited' THEN
        UPDATE public.enterprise_members
        SET status = 'removed',
            updated_at = pg_catalog.now()
        WHERE id = v_old_member_id;
      END IF;
    END IF;

    PERFORM fixeo_private._write_enterprise_audit_event(
      p_enterprise_id,
      'member.invitation_expired',
      'enterprise_invitation',
      v_old_invitation_id,
      pg_catalog.jsonb_build_object('status','pending'),
      pg_catalog.jsonb_build_object('status','expired'),
      pg_catalog.jsonb_build_object('member_id',v_old_member_id)
    );
  END IF;

  -- Resolve normalized email against auth.users, never public.users email.
  SELECT COUNT(*)
  INTO v_auth_match_count
  FROM auth.users au
  WHERE pg_catalog.lower(pg_catalog.btrim(au.email::text)) = v_email;

  IF v_auth_match_count > 1 THEN
    RETURN pg_catalog.jsonb_build_object(
      'ok',false,
      'reason','ambiguous_email_identity'
    );
  END IF;

  IF v_auth_match_count = 0 THEN
    v_auth_user_id := NULL;
  ELSE
    -- Exactly one normalized auth.users identity exists.
    SELECT au.id
    INTO STRICT v_auth_user_id
    FROM auth.users au
    WHERE pg_catalog.lower(pg_catalog.btrim(au.email::text)) = v_email;

    SELECT EXISTS (
      SELECT 1
      FROM public.users u
      WHERE u.id = v_auth_user_id
    )
    INTO v_public_user_exists;

    IF NOT v_public_user_exists THEN
      RETURN pg_catalog.jsonb_build_object(
        'ok',false,
        'reason','identity_not_ready'
      );
    END IF;
  END IF;

  -- Existing membership handling.
  IF v_auth_user_id IS NOT NULL THEN
    SELECT em.id, em.status
    INTO v_existing_member_id, v_existing_member_status
    FROM public.enterprise_members em
    WHERE em.enterprise_id = p_enterprise_id
      AND em.user_id = v_auth_user_id
    FOR UPDATE;

    IF FOUND THEN
      IF v_existing_member_status IN ('active','suspended') THEN
        RETURN pg_catalog.jsonb_build_object(
          'ok',false,
          'reason','already_member',
          'member_id',v_existing_member_id,
          'member_status',v_existing_member_status
        );
      END IF;

      IF v_existing_member_status = 'invited' THEN
        -- No current pending invitation exists at this point. An invited row
        -- without a live pending invitation is stale and is safely re-used.
        UPDATE public.enterprise_members
        SET role = p_role,
            invited_by = v_caller_id,
            updated_at = pg_catalog.now()
        WHERE id = v_existing_member_id;

        v_member_id := v_existing_member_id;

      ELSIF v_existing_member_status = 'removed' THEN
        UPDATE public.enterprise_members
        SET role = p_role,
            status = 'invited',
            invited_by = v_caller_id,
            updated_at = pg_catalog.now()
        WHERE id = v_existing_member_id;

        v_member_id := v_existing_member_id;

      ELSE
        RETURN pg_catalog.jsonb_build_object(
          'ok',false,
          'reason','membership_state_unsupported'
        );
      END IF;
    END IF;
  END IF;

  -- Generate token inside PostgreSQL. Raw token is never stored.
  v_raw_token :=
    pg_catalog.encode(
      extensions.gen_random_bytes(32),
      'hex'
    );

  v_token_hash :=
    pg_catalog.encode(
      extensions.digest(
        pg_catalog.convert_to(v_raw_token,'UTF8'),
        'sha256'
      ),
      'hex'
    );

  INSERT INTO public.enterprise_invitations (
    enterprise_id,
    email_normalized,
    role,
    invited_by,
    target_user_id,
    token_hash,
    status,
    expires_at
  )
  VALUES (
    p_enterprise_id,
    v_email,
    p_role,
    v_caller_id,
    v_auth_user_id,
    v_token_hash,
    'pending',
    p_expires_at
  )
  RETURNING id INTO v_invitation_id;

  IF v_auth_user_id IS NOT NULL AND v_member_id IS NULL THEN
    INSERT INTO public.enterprise_members (
      enterprise_id,
      user_id,
      role,
      status,
      invited_by
    )
    VALUES (
      p_enterprise_id,
      v_auth_user_id,
      p_role,
      'invited',
      v_caller_id
    )
    RETURNING id INTO v_member_id;
  END IF;

  PERFORM fixeo_private._write_enterprise_audit_event(
    p_enterprise_id,
    'member.invited',
    'enterprise_invitation',
    v_invitation_id,
    NULL,
    pg_catalog.jsonb_build_object(
      'role',p_role,
      'status','pending',
      'target_user_resolved',(v_auth_user_id IS NOT NULL)
    ),
    pg_catalog.jsonb_build_object('member_id',v_member_id)
  );

  RETURN pg_catalog.jsonb_build_object(
    'ok',true,
    'invitation_id',v_invitation_id,
    'invitation_token',v_raw_token,
    'member_id',v_member_id,
    'target_user_resolved',(v_auth_user_id IS NOT NULL),
    'expires_at',p_expires_at
  );

EXCEPTION
  WHEN unique_violation THEN
    RETURN pg_catalog.jsonb_build_object(
      'ok',false,
      'reason','invitation_conflict'
    );

  WHEN OTHERS THEN
    RAISE WARNING '[create_enterprise_invitation] error: % (SQLSTATE: %)',
      SQLERRM, SQLSTATE;
    RETURN pg_catalog.jsonb_build_object('ok',false,'reason','internal_error');
END;
$function$;


-- ═════════════════════════════════════════════════════════════════════════════
-- SECTION 5 — ACCEPT INVITATION
--
-- Two-step lookup preserves the global lock order:
--   1) read invitation's enterprise_id without locking
--   2) lock enterprise_accounts row
--   3) re-read + lock invitation and re-validate it
--   4) lock membership
--
-- Identity is bound to auth.uid() and auth.users.email.
-- ═════════════════════════════════════════════════════════════════════════════

CREATE OR REPLACE FUNCTION public.accept_enterprise_invitation(
  p_token text
)
RETURNS jsonb
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path TO ''
AS $function$
DECLARE
  v_caller_id uuid;
  v_caller_email text;
  v_public_user_exists boolean;

  v_token_hash text;

  v_probe_enterprise_id uuid;

  v_invitation_id uuid;
  v_enterprise_id uuid;
  v_invitation_email text;
  v_invitation_role text;
  v_invitation_status text;
  v_target_user_id uuid;
  v_expires_at timestamptz;

  v_member_id uuid;
  v_member_status text;
BEGIN
  v_caller_id := auth.uid();

  IF v_caller_id IS NULL THEN
    RETURN pg_catalog.jsonb_build_object('ok',false,'reason','unauthenticated');
  END IF;

  IF p_token IS NULL
     OR pg_catalog.char_length(p_token) <> 64
     OR p_token !~ '^[0-9a-fA-F]{64}$'
  THEN
    RETURN pg_catalog.jsonb_build_object('ok',false,'reason','invalid_token');
  END IF;

  SELECT pg_catalog.lower(pg_catalog.btrim(au.email::text))
  INTO v_caller_email
  FROM auth.users au
  WHERE au.id = v_caller_id;

  IF NOT FOUND OR v_caller_email IS NULL OR v_caller_email = '' THEN
    RETURN pg_catalog.jsonb_build_object(
      'ok',false,
      'reason','identity_email_unavailable'
    );
  END IF;

  SELECT EXISTS (
    SELECT 1 FROM public.users u WHERE u.id = v_caller_id
  )
  INTO v_public_user_exists;

  IF NOT v_public_user_exists THEN
    RETURN pg_catalog.jsonb_build_object(
      'ok',false,
      'reason','identity_not_ready'
    );
  END IF;

  v_token_hash :=
    pg_catalog.encode(
      extensions.digest(
        pg_catalog.convert_to(pg_catalog.lower(p_token),'UTF8'),
        'sha256'
      ),
      'hex'
    );

  -- Probe only: no lock yet.
  SELECT ei.enterprise_id
  INTO v_probe_enterprise_id
  FROM public.enterprise_invitations ei
  WHERE ei.token_hash = v_token_hash;

  IF NOT FOUND THEN
    RETURN pg_catalog.jsonb_build_object('ok',false,'reason','invitation_not_found');
  END IF;

  -- LOCK ORDER #1: enterprise account.
  PERFORM ea.id
  FROM public.enterprise_accounts ea
  WHERE ea.id = v_probe_enterprise_id
  FOR UPDATE;

  IF NOT FOUND THEN
    RETURN pg_catalog.jsonb_build_object('ok',false,'reason','enterprise_not_found');
  END IF;

  -- LOCK ORDER #2: invitation. Re-read all mutable fields after account lock.
  SELECT
    ei.id,
    ei.enterprise_id,
    ei.email_normalized,
    ei.role,
    ei.status,
    ei.target_user_id,
    ei.expires_at
  INTO
    v_invitation_id,
    v_enterprise_id,
    v_invitation_email,
    v_invitation_role,
    v_invitation_status,
    v_target_user_id,
    v_expires_at
  FROM public.enterprise_invitations ei
  WHERE ei.token_hash = v_token_hash
    AND ei.enterprise_id = v_probe_enterprise_id
  FOR UPDATE;

  IF NOT FOUND THEN
    RETURN pg_catalog.jsonb_build_object('ok',false,'reason','invitation_not_found');
  END IF;

  IF v_invitation_status <> 'pending' THEN
    RETURN pg_catalog.jsonb_build_object(
      'ok',false,
      'reason','invitation_not_pending'
    );
  END IF;

  IF v_expires_at <= pg_catalog.now() THEN
    UPDATE public.enterprise_invitations
    SET status='expired',
        updated_at=pg_catalog.now()
    WHERE id=v_invitation_id;

    -- LOCK ORDER #3: invited membership, if one was materialized.
    IF v_target_user_id IS NOT NULL THEN
      SELECT em.id, em.status
      INTO v_member_id, v_member_status
      FROM public.enterprise_members em
      WHERE em.enterprise_id=v_enterprise_id
        AND em.user_id=v_target_user_id
      FOR UPDATE;

      IF FOUND AND v_member_status='invited' THEN
        UPDATE public.enterprise_members
        SET status='removed',
            updated_at=pg_catalog.now()
        WHERE id=v_member_id;
      END IF;
    END IF;

    PERFORM fixeo_private._write_enterprise_audit_event(
      v_enterprise_id,
      'member.invitation_expired',
      'enterprise_invitation',
      v_invitation_id,
      pg_catalog.jsonb_build_object('status','pending'),
      pg_catalog.jsonb_build_object('status','expired'),
      pg_catalog.jsonb_build_object('member_id',v_member_id)
    );

    RETURN pg_catalog.jsonb_build_object('ok',false,'reason','invitation_expired');
  END IF;

  IF v_caller_email <> v_invitation_email THEN
    RETURN pg_catalog.jsonb_build_object(
      'ok',false,
      'reason','invitation_identity_mismatch'
    );
  END IF;

  IF v_target_user_id IS NOT NULL
     AND v_target_user_id <> v_caller_id
  THEN
    RETURN pg_catalog.jsonb_build_object(
      'ok',false,
      'reason','invitation_identity_mismatch'
    );
  END IF;

  -- LOCK ORDER #3: membership.
  SELECT em.id, em.status
  INTO v_member_id, v_member_status
  FROM public.enterprise_members em
  WHERE em.enterprise_id=v_enterprise_id
    AND em.user_id=v_caller_id
  FOR UPDATE;

  IF FOUND THEN
    IF v_member_status IN ('active','suspended') THEN
      RETURN pg_catalog.jsonb_build_object(
        'ok',false,
        'reason','membership_conflict',
        'member_status',v_member_status
      );
    END IF;

    IF v_member_status NOT IN ('invited','removed') THEN
      RETURN pg_catalog.jsonb_build_object(
        'ok',false,
        'reason','membership_state_unsupported',
        'member_status',v_member_status
      );
    END IF;

    -- 'removed' is valid here when the invitation was created before this
    -- auth identity existed, or after an older invitation lifecycle ended.
    -- Acceptance reuses the historical membership row; no physical DELETE.
    UPDATE public.enterprise_members
    SET role=v_invitation_role,
        status='active',
        invited_by=(
          SELECT ei.invited_by
          FROM public.enterprise_invitations ei
          WHERE ei.id=v_invitation_id
        ),
        updated_at=pg_catalog.now()
    WHERE id=v_member_id;

  ELSE
    INSERT INTO public.enterprise_members (
      enterprise_id,
      user_id,
      role,
      status,
      invited_by
    )
    SELECT
      ei.enterprise_id,
      v_caller_id,
      ei.role,
      'active',
      ei.invited_by
    FROM public.enterprise_invitations ei
    WHERE ei.id=v_invitation_id
    RETURNING id INTO v_member_id;
  END IF;

  UPDATE public.enterprise_invitations
  SET status='accepted',
      target_user_id=v_caller_id,
      accepted_at=pg_catalog.now(),
      accepted_by=v_caller_id,
      updated_at=pg_catalog.now()
  WHERE id=v_invitation_id;

  PERFORM fixeo_private._write_enterprise_audit_event(
    v_enterprise_id,
    'member.invitation_accepted',
    'enterprise_invitation',
    v_invitation_id,
    pg_catalog.jsonb_build_object(
      'status','pending',
      'role',v_invitation_role
    ),
    pg_catalog.jsonb_build_object(
      'status','accepted',
      'role',v_invitation_role,
      'member_id',v_member_id
    ),
    pg_catalog.jsonb_build_object(
      'accepted_user_id',v_caller_id
    )
  );

  RETURN pg_catalog.jsonb_build_object(
    'ok',true,
    'invitation_id',v_invitation_id,
    'enterprise_id',v_enterprise_id,
    'member_id',v_member_id,
    'role',v_invitation_role,
    'status','active'
  );

EXCEPTION
  WHEN unique_violation THEN
    RETURN pg_catalog.jsonb_build_object(
      'ok',false,
      'reason','membership_conflict'
    );

  WHEN OTHERS THEN
    RAISE WARNING '[accept_enterprise_invitation] error: % (SQLSTATE: %)',
      SQLERRM, SQLSTATE;
    RETURN pg_catalog.jsonb_build_object('ok',false,'reason','internal_error');
END;
$function$;


-- ═════════════════════════════════════════════════════════════════════════════
-- SECTION 6 — REVOKE INVITATION
-- Same lock order: account → invitation → member.
-- ═════════════════════════════════════════════════════════════════════════════

CREATE OR REPLACE FUNCTION public.revoke_enterprise_invitation(
  p_enterprise_id uuid,
  p_invitation_id uuid
)
RETURNS jsonb
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path TO ''
AS $function$
DECLARE
  v_caller_id uuid;
  v_caller_role text;
  v_caller_status text;

  v_status text;
  v_role text;
  v_target_user_id uuid;

  v_member_id uuid;
  v_member_status text;
BEGIN
  v_caller_id := auth.uid();

  IF v_caller_id IS NULL THEN
    RETURN pg_catalog.jsonb_build_object('ok',false,'reason','unauthenticated');
  END IF;

  -- LOCK ORDER #1: enterprise account.
  PERFORM ea.id
  FROM public.enterprise_accounts ea
  WHERE ea.id=p_enterprise_id
  FOR UPDATE;

  IF NOT FOUND THEN
    RETURN pg_catalog.jsonb_build_object('ok',false,'reason','enterprise_not_found');
  END IF;

  SELECT em.role, em.status
  INTO v_caller_role, v_caller_status
  FROM public.enterprise_members em
  WHERE em.enterprise_id=p_enterprise_id
    AND em.user_id=v_caller_id;

  IF NOT FOUND THEN
    RETURN pg_catalog.jsonb_build_object('ok',false,'reason','not_a_member');
  END IF;

  IF v_caller_status <> 'active' THEN
    RETURN pg_catalog.jsonb_build_object('ok',false,'reason','caller_not_active');
  END IF;

  IF v_caller_role NOT IN ('owner','admin') THEN
    RETURN pg_catalog.jsonb_build_object('ok',false,'reason','forbidden');
  END IF;

  -- LOCK ORDER #2: invitation.
  SELECT ei.status, ei.role, ei.target_user_id
  INTO v_status, v_role, v_target_user_id
  FROM public.enterprise_invitations ei
  WHERE ei.id=p_invitation_id
    AND ei.enterprise_id=p_enterprise_id
  FOR UPDATE;

  IF NOT FOUND THEN
    RETURN pg_catalog.jsonb_build_object('ok',false,'reason','invitation_not_found');
  END IF;

  IF v_status <> 'pending' THEN
    RETURN pg_catalog.jsonb_build_object(
      'ok',false,
      'reason','invitation_not_pending'
    );
  END IF;

  -- LOCK ORDER #3: membership.
  IF v_target_user_id IS NOT NULL THEN
    SELECT em.id, em.status
    INTO v_member_id, v_member_status
    FROM public.enterprise_members em
    WHERE em.enterprise_id=p_enterprise_id
      AND em.user_id=v_target_user_id
    FOR UPDATE;

    IF FOUND AND v_member_status='invited' THEN
      UPDATE public.enterprise_members
      SET status='removed',
          updated_at=pg_catalog.now()
      WHERE id=v_member_id;

    ELSIF FOUND THEN
      RETURN pg_catalog.jsonb_build_object(
        'ok',false,
        'reason','membership_conflict',
        'member_status',v_member_status
      );
    END IF;
  END IF;

  UPDATE public.enterprise_invitations
  SET status='revoked',
      revoked_at=pg_catalog.now(),
      revoked_by=v_caller_id,
      updated_at=pg_catalog.now()
  WHERE id=p_invitation_id;

  PERFORM fixeo_private._write_enterprise_audit_event(
    p_enterprise_id,
    'member.invitation_revoked',
    'enterprise_invitation',
    p_invitation_id,
    pg_catalog.jsonb_build_object(
      'status','pending',
      'role',v_role
    ),
    pg_catalog.jsonb_build_object(
      'status','revoked',
      'role',v_role
    ),
    pg_catalog.jsonb_build_object('member_id',v_member_id)
  );

  RETURN pg_catalog.jsonb_build_object(
    'ok',true,
    'invitation_id',p_invitation_id,
    'status','revoked'
  );

EXCEPTION
  WHEN OTHERS THEN
    RAISE WARNING '[revoke_enterprise_invitation] error: % (SQLSTATE: %)',
      SQLERRM, SQLSTATE;
    RETURN pg_catalog.jsonb_build_object('ok',false,'reason','internal_error');
END;
$function$;


-- ═════════════════════════════════════════════════════════════════════════════
-- SECTION 7 — FUNCTION EXECUTE PRIVILEGES
-- ═════════════════════════════════════════════════════════════════════════════

REVOKE EXECUTE ON FUNCTION public.create_enterprise_invitation(
  uuid,text,text,timestamptz
) FROM PUBLIC, anon;

GRANT EXECUTE ON FUNCTION public.create_enterprise_invitation(
  uuid,text,text,timestamptz
) TO authenticated;

REVOKE EXECUTE ON FUNCTION public.accept_enterprise_invitation(text)
FROM PUBLIC, anon;

GRANT EXECUTE ON FUNCTION public.accept_enterprise_invitation(text)
TO authenticated;

REVOKE EXECUTE ON FUNCTION public.revoke_enterprise_invitation(uuid,uuid)
FROM PUBLIC, anon;

GRANT EXECUTE ON FUNCTION public.revoke_enterprise_invitation(uuid,uuid)
TO authenticated;


-- ═════════════════════════════════════════════════════════════════════════════
-- SECTION 8 — FINAL STATUS
-- ═════════════════════════════════════════════════════════════════════════════

DO $$
BEGIN
  RAISE NOTICE '';
  RAISE NOTICE '══════════════════════════════════════════════════════════';
  RAISE NOTICE '7C.15A.6 Enterprise Invitation Control Plane — PRODUCTION MIGRATION.';
  RAISE NOTICE '';
  RAISE NOTICE 'New relation: public.enterprise_invitations';
  RAISE NOTICE '';
  RAISE NOTICE 'New RPCs:';
  RAISE NOTICE '  create_enterprise_invitation(uuid,text,text,timestamptz)';
  RAISE NOTICE '  accept_enterprise_invitation(text)';
  RAISE NOTICE '  revoke_enterprise_invitation(uuid,uuid)';
  RAISE NOTICE '';
  RAISE NOTICE 'Token generation: PostgreSQL CSPRNG, 256 bits';
  RAISE NOTICE 'Token storage: SHA-256 hash only';
  RAISE NOTICE 'token_hash client SELECT: forbidden';
  RAISE NOTICE 'Identity source: auth.users email';
  RAISE NOTICE 'Acceptance: auth.uid + auth.users.email bound';
  RAISE NOTICE 'Removed membership re-invitation: supported';
  RAISE NOTICE 'Removed membership acceptance/reactivation: supported';
  RAISE NOTICE 'Expired pending invitation cleanup: supported';
  RAISE NOTICE 'Physical enterprise_members DELETE: not implemented';
  RAISE NOTICE 'Outbound email delivery: not implemented';
  RAISE NOTICE '';
  RAISE NOTICE 'STATIC AUDIT PASS — PRODUCTION PRE-APPLY PASS';
  RAISE NOTICE '══════════════════════════════════════════════════════════';
END $$;

COMMIT;
