-- ============================================================
-- FIXEO — Estimator Context Redemptions Table
-- File: supabase/estimator-context-redemptions-v1.sql
-- Phase: 7C.9E / 7C.9F  — Estimator Idempotency Closure
-- Version: 1.0 — 2026-08-10
--
-- PURPOSE
-- -------
-- Provides durable, cross-instance idempotency for estimator-backed
-- COD bookings. Guarantees that ONE encrypted pricing context
-- (identified by context_id) can successfully create AT MOST ONE
-- booking, even under:
--   - Browser retry after network failure
--   - Double-submit from the same user
--   - Concurrent race conditions (multiple serverless instances)
--   - Token replay within the 15-min TTL window
--
-- ATOMICITY MECHANISM
-- -------------------
-- The UNIQUE constraint on context_id is the single atomic gate.
-- Two concurrent INSERT attempts for the same context_id → exactly
-- one succeeds (PostgreSQL guarantees). The application never
-- performs check-then-act in application code — the uniqueness is
-- enforced at database level.
--
-- context_id format: fxctx-<32 lowercase hex chars>
-- Generated by: api/estimator-v1/fixeo-estimator-runtime-v1.js
-- Used by:      api/fixeo-estimator-idempotency-v1.js
--
-- SECURITY ARCHITECTURE
-- ---------------------
-- This table is SERVER-ONLY infrastructure.
-- Inserts and updates arrive exclusively from the Vercel serverless
-- function api/server.js via api/fixeo-estimator-idempotency-v1.js,
-- which uses the Supabase SERVICE ROLE key (server-side env var,
-- never exposed to browser).
--
-- The service role bypasses RLS at the Supabase PostgREST layer,
-- so no anon or authenticated INSERT policy is needed or wanted.
--
-- Role access summary:
--   anon          -> NO access (REVOKE ALL, no policies)
--   authenticated -> NO write access; SELECT only for admin role
--   service_role  -> unrestricted (Vercel fn + Supabase Studio)
--
-- RLS is ENABLED and FORCED as defence-in-depth.
-- If SUPABASE_SERVICE_ROLE_KEY is ever accidentally replaced with
-- the anon key, all writes will be blocked — not silently accepted.
--
-- STATE MACHINE
-- -------------
-- 'acquired'  → context reserved; booking creation in progress
-- 'committed' → booking successfully created; context permanently consumed
-- 'failed'    → booking creation failed; context available for retry
--
-- Transitions:
--   [not-exists] → INSERT → 'acquired'
--   'acquired'   → PATCH  → 'committed'   (success: commit booking_ref)
--   'acquired'   → PATCH  → 'failed'      (failure: allow retry)
--   'failed'     → PATCH  → 'acquired'    (re-acquire for retry)
--
-- SAFE TO RE-RUN
-- --------------
-- All statements use IF NOT EXISTS / OR REPLACE / DROP IF EXISTS.
-- Running this script twice on the same database is harmless.
-- ============================================================


-- ============================================================
-- SECTION 1 — CREATE TABLE
-- ============================================================

CREATE TABLE IF NOT EXISTS public.estimator_context_redemptions (

  -- Primary key (surrogate — context_id is the real identity key)
  id                bigserial     PRIMARY KEY,

  -- ── IDEMPOTENCY KEY ─────────────────────────────────────────────────────
  -- context_id is the atomic replay boundary.
  -- Format: fxctx-<32 lowercase hex chars>
  -- Generated server-side only (api/estimator-v1/fixeo-estimator-runtime-v1.js).
  -- The UNIQUE constraint provides database-level atomicity for concurrent
  -- INSERT attempts. Never forge-able from the browser (AES-256-GCM sealed).
  context_id        text          NOT NULL,

  -- ── IDENTITY FIELDS (written on INSERT, used for conflict detection) ─────
  -- All three are required by consumeEstimatorContext() bookingCandidate param.
  outcome_type      text          NOT NULL,
  service_code      text          NOT NULL,
  session_id        text          NOT NULL,

  -- ── PRICE AUDIT (server-canonical, written on INSERT for admin audit) ────
  -- amount_mad is the server-authoritative canonical amount from the sealed
  -- pricing context token. Stored for audit/admin only — NOT used to re-derive
  -- booking amounts. Bookings always use the live token authority, not this.
  amount_mad        integer       NOT NULL,

  -- ── STATE MACHINE ───────────────────────────────────────────────────────
  -- Valid values: 'acquired' | 'committed' | 'failed'
  -- CHECK constraint enforces the exact values known to the runtime.
  state             text          NOT NULL DEFAULT 'acquired'
                                  CHECK (state IN ('acquired', 'committed', 'failed')),

  -- ── BOOKING BINDING (populated on commitEstimatorContext) ───────────────
  -- Set to NULL on INSERT; bound to the real booking on PATCH to 'committed'.
  -- booking_ref: COD booking reference (e.g. COD-LK3X2Y)
  -- order_id:    COD orderID from the browser request
  booking_ref       text,
  order_id          text,

  -- ── FAILURE AUDIT (populated on failEstimatorContext) ───────────────────
  -- failure_reason: up to 500 chars (truncated by runtime before storage).
  -- Set back to NULL on re-acquire (recovery path).
  failure_reason    text          CHECK (failure_reason IS NULL OR char_length(failure_reason) <= 500),

  -- ── TIMESTAMPS ──────────────────────────────────────────────────────────
  -- acquired_at: ISO timestamp of the most recent acquisition attempt.
  -- Set on INSERT and also on re-acquire (recovery path PATCH).
  acquired_at       timestamptz   NOT NULL DEFAULT now(),

  -- committed_at: ISO timestamp when context was committed (booking created).
  -- NULL until state = 'committed'.
  committed_at      timestamptz,

  -- failed_at: ISO timestamp of most recent failure.
  -- NULL until state = 'failed'. Reset to NULL on re-acquire.
  failed_at         timestamptz

);

-- Table comments
COMMENT ON TABLE public.estimator_context_redemptions IS
  'Durable idempotency table for estimator-backed COD bookings. '
  'context_id (UNIQUE) is the atomic replay boundary. '
  'Inserted server-side by api/server.js via fixeo-estimator-idempotency-v1.js '
  'using service_role key. anon has no access. '
  'Phase 7C.9E / 7C.9F — Version 1.0';

COMMENT ON COLUMN public.estimator_context_redemptions.context_id IS
  'Atomic idempotency key. Format: fxctx-<32hex>. Server-generated only. '
  'UNIQUE constraint is the concurrency safety mechanism.';

COMMENT ON COLUMN public.estimator_context_redemptions.state IS
  'State machine: acquired → committed (success) or failed (retry allowed). '
  'Only committed contexts are permanently consumed. '
  'failed contexts can be re-acquired.';

COMMENT ON COLUMN public.estimator_context_redemptions.amount_mad IS
  'Server-canonical booking amount in MAD (from sealed pricing context token). '
  'Stored for audit only. Booking price authority is always the live token — not this column.';

COMMENT ON COLUMN public.estimator_context_redemptions.booking_ref IS
  'COD booking reference (e.g. COD-LK3X2Y). NULL until committed.';

COMMENT ON COLUMN public.estimator_context_redemptions.failure_reason IS
  'Failure description from failEstimatorContext(). Max 500 chars. '
  'Reset to NULL on re-acquire (recovery path).';


-- ============================================================
-- SECTION 2 — UNIQUE CONSTRAINT (ATOMICITY MECHANISM)
-- ============================================================

-- This is the core idempotency guarantee.
-- Concurrent INSERT for the same context_id → exactly one succeeds.
-- The second INSERT returns a unique violation → application detects
-- conflict without a race condition window.
--
-- Named explicitly so it can be referenced in documentation and
-- application error handling.

ALTER TABLE public.estimator_context_redemptions
  DROP CONSTRAINT IF EXISTS estimator_context_redemptions_context_id_unique;

ALTER TABLE public.estimator_context_redemptions
  ADD CONSTRAINT estimator_context_redemptions_context_id_unique
  UNIQUE (context_id);


-- ============================================================
-- SECTION 3 — INDEXES
-- ============================================================

-- Primary lookup: by context_id (single-row point lookup on INSERT+PATCH+GET)
-- The UNIQUE constraint above creates an implicit index on context_id.
-- Explicitly named index for clarity and DROP-IF-EXISTS safety.
CREATE UNIQUE INDEX IF NOT EXISTS idx_ecr_context_id
  ON public.estimator_context_redemptions (context_id);

-- Admin audit: most recent acquisitions first
CREATE INDEX IF NOT EXISTS idx_ecr_acquired_at
  ON public.estimator_context_redemptions (acquired_at DESC);

-- Admin audit: filter by state (find stuck 'acquired' rows, failed rows)
CREATE INDEX IF NOT EXISTS idx_ecr_state
  ON public.estimator_context_redemptions (state);

-- Admin audit: filter by service_code (usage statistics per service)
CREATE INDEX IF NOT EXISTS idx_ecr_service_code
  ON public.estimator_context_redemptions (service_code);


-- ============================================================
-- SECTION 4 — ROW LEVEL SECURITY
-- ============================================================

-- Enable RLS (defence-in-depth).
-- service_role bypasses RLS — all Vercel fn writes go through service_role.
-- anon and authenticated cannot touch this table.
ALTER TABLE public.estimator_context_redemptions ENABLE ROW LEVEL SECURITY;

-- Force RLS even for table owner when accessed via PostgREST API.
-- Ensures no accidental public access even if a policy is mis-created.
ALTER TABLE public.estimator_context_redemptions FORCE ROW LEVEL SECURITY;


-- ============================================================
-- SECTION 5 — REVOKE ALL FROM anon
-- ============================================================

-- anon has zero access to this table.
-- Belt-and-suspenders: revoke at grant level AND have no anon policies.
REVOKE ALL ON public.estimator_context_redemptions FROM anon;

-- Drop any previously created anon policies (idempotent cleanup)
DROP POLICY IF EXISTS "ecr_anon_insert"  ON public.estimator_context_redemptions;
DROP POLICY IF EXISTS "ecr_anon_select"  ON public.estimator_context_redemptions;
DROP POLICY IF EXISTS "ecr_anon_update"  ON public.estimator_context_redemptions;
DROP POLICY IF EXISTS "ecr_anon_delete"  ON public.estimator_context_redemptions;

-- Drop authenticated write policies if previously created (idempotent)
DROP POLICY IF EXISTS "ecr_auth_insert"  ON public.estimator_context_redemptions;
DROP POLICY IF EXISTS "ecr_auth_update"  ON public.estimator_context_redemptions;


-- ============================================================
-- SECTION 6 — RLS POLICIES (authenticated role — admin read-only)
-- ============================================================

-- 6-A: Admin SELECT — read-only audit access for Supabase Studio admin users.
-- Non-admin authenticated users see zero rows.
-- service_role (Vercel fn, Supabase Studio as service) bypasses this entirely.
DROP POLICY IF EXISTS "ecr_admin_select" ON public.estimator_context_redemptions;

CREATE POLICY "ecr_admin_select"
  ON public.estimator_context_redemptions
  FOR SELECT
  TO authenticated
  USING (
    EXISTS (
      SELECT 1
      FROM public.profiles
      WHERE profiles.id   = auth.uid()
        AND profiles.role = 'admin'
    )
  );

-- NOTE: No authenticated INSERT, UPDATE, or DELETE policy.
-- All writes go through the Vercel fn using service_role.
-- RLS default-deny blocks any authenticated INSERT/UPDATE/DELETE.
-- No anon policy exists → anon gets zero access.


-- ============================================================
-- SECTION 7 — GRANTS
-- ============================================================

-- anon: NO grants (REVOKE ALL already issued above)
REVOKE ALL ON public.estimator_context_redemptions FROM anon;

-- authenticated: SELECT only (INSERT/UPDATE/DELETE blocked by RLS default-deny + no policies)
-- Admin SELECT is additionally gated by the ecr_admin_select policy.
GRANT SELECT ON public.estimator_context_redemptions TO authenticated;

-- service_role: Supabase grants this implicitly; explicit GRANT not required.
-- The Vercel fn uses service_role → bypasses RLS → INSERT/UPDATE/RETURNING work.

-- Schema usage (Supabase default — usually already granted)
GRANT USAGE ON SCHEMA public TO authenticated;

-- Sequence: service_role needs this for bigserial INSERT
GRANT USAGE, SELECT ON SEQUENCE public.estimator_context_redemptions_id_seq TO authenticated;


-- ============================================================
-- SECTION 8 — VERIFICATION QUERIES
-- Run after applying to confirm everything is correct.
-- Expected results documented inline.
-- ============================================================

-- 8-A: Confirm table exists and all columns are present
-- Expected: 12 rows (one per column defined above)
SELECT
  column_name,
  data_type,
  is_nullable,
  column_default
FROM information_schema.columns
WHERE table_schema = 'public'
  AND table_name   = 'estimator_context_redemptions'
ORDER BY ordinal_position;

-- 8-B: Confirm RLS is enabled and forced
-- Expected: rls_enabled=true, rls_forced=true
SELECT
  relname             AS table_name,
  relrowsecurity      AS rls_enabled,
  relforcerowsecurity AS rls_forced
FROM pg_class
WHERE relname = 'estimator_context_redemptions';

-- 8-C: Confirm UNIQUE constraint exists
-- Expected: 1 row — estimator_context_redemptions_context_id_unique
SELECT conname, contype, pg_get_constraintdef(oid) AS definition
FROM pg_constraint
WHERE conrelid = 'public.estimator_context_redemptions'::regclass
  AND contype  = 'u';

-- 8-D: Confirm indexes (expected: 4 — context_id UNIQUE, acquired_at, state, service_code)
SELECT indexname, indexdef
FROM pg_indexes
WHERE tablename = 'estimator_context_redemptions'
ORDER BY indexname;

-- 8-E: Confirm anon has no privileges
-- Expected: zero rows
SELECT grantee, privilege_type
FROM information_schema.role_table_grants
WHERE table_name = 'estimator_context_redemptions'
  AND grantee    = 'anon';

-- 8-F: Confirm policies (expected: 1 row — ecr_admin_select)
SELECT policyname, roles, cmd AS command, qual AS using_expr
FROM pg_policies
WHERE tablename = 'estimator_context_redemptions'
ORDER BY policyname;

-- 8-G: Confirm empty table (no data yet — baseline)
-- Expected: count = 0
SELECT COUNT(*) AS baseline_row_count
FROM public.estimator_context_redemptions;

-- 8-H: Test INSERT as service_role (simulates Vercel fn)
-- The SQL Editor runs as service_role by default — this should succeed.
INSERT INTO public.estimator_context_redemptions (
  context_id, outcome_type, service_code, session_id,
  amount_mad, state, acquired_at
) VALUES (
  'fxctx-00000000000000000000000000000000',
  'PRICE_READY', 'test.schema_verify', 'sess-test-7c9f',
  300, 'acquired', now()
)
RETURNING id, context_id, state, acquired_at;

-- 8-I: Test UNIQUE constraint (should fail with unique violation)
-- Expected: ERROR: duplicate key value violates unique constraint
INSERT INTO public.estimator_context_redemptions (
  context_id, outcome_type, service_code, session_id,
  amount_mad, state, acquired_at
) VALUES (
  'fxctx-00000000000000000000000000000000',
  'PRICE_READY', 'test.schema_verify', 'sess-test-7c9f-2',
  300, 'acquired', now()
);

-- 8-J: Test PATCH to committed (simulates commitEstimatorContext)
UPDATE public.estimator_context_redemptions
SET
  state        = 'committed',
  booking_ref  = 'COD-TESTREF',
  order_id     = 'ORD-TEST-7C9F',
  committed_at = now()
WHERE context_id = 'fxctx-00000000000000000000000000000000'
RETURNING id, context_id, state, booking_ref, committed_at;

-- 8-K: Test state CHECK constraint (should fail)
-- Expected: ERROR: new row for relation "estimator_context_redemptions" violates check constraint
UPDATE public.estimator_context_redemptions
SET state = 'invalid_state'
WHERE context_id = 'fxctx-00000000000000000000000000000000';

-- 8-L: Clean up test row
DELETE FROM public.estimator_context_redemptions
WHERE context_id = 'fxctx-00000000000000000000000000000000';

-- 8-M: Confirm clean
SELECT COUNT(*) AS rows_after_cleanup FROM public.estimator_context_redemptions;
