-- ============================================================
-- FIXEO — Estimator Context Redemptions Table
-- File: supabase/estimator-context-redemptions-v1.sql
-- Phase: 7C.9E / 7C.9F / 7C.9F.1
-- Version: 1.1 — 2026-08-10 (corrected from 1.0)
--
-- CHANGES IN VERSION 1.1 (7C.9F.1 surgical patch):
--   - REMOVED redundant CREATE UNIQUE INDEX idx_ecr_context_id.
--     The UNIQUE constraint already owns a unique index.
--     Having both creates a duplicate index, confuses VQ-4 count,
--     and wastes storage. Canonical uniqueness mechanism is the
--     named UNIQUE constraint only.
--   - STRENGTHENED authenticated/anon grants:
--     REVOKE ALL from both anon AND authenticated before re-granting.
--     Sequence USAGE/SELECT explicitly revoked from anon and authenticated
--     (no SELECT operation needs sequence access).
--   - VERIFIED profiles admin contract:
--     profiles.id = auth.uid() AND profiles.role = 'admin'
--     is the established FIXEO admin pattern used by 10+ existing RLS
--     policies across enterprise_leads, notifications-table,
--     rls-fix-2026-04-29, rls-claim-requests, rls-artisan-* files.
--     public.profiles has columns: id (UUID), role (TEXT).
--     Contract is proved by existing production migration history.
--     ecr_admin_select policy is UNCHANGED.
--   - UPDATED verification queries (VQ-1 through VQ-9):
--     VQ-4: expected 5 indexes (not 6 — redundant idx_ecr_context_id removed).
--     VQ-6: authenticated SELECT only, zero INSERT/UPDATE/DELETE.
--     VQ-7: anon + authenticated have zero sequence privileges.
--     VQ-8: exactly 1 policy (ecr_admin_select).
--     VQ-9: COUNT(*) = 0 baseline.
--
-- PURPOSE
-- -------
-- Provides durable, cross-instance idempotency for estimator-backed
-- COD bookings. Guarantees that ONE encrypted pricing context
-- (identified by context_id) can successfully create AT MOST ONE
-- booking, even under:
--   - Browser retry after network failure
--   - Double-submit from the same user
--   - Concurrent race conditions (multiple serverless instances)
--   - Token replay within the 15-min TTL window
--
-- ATOMICITY MECHANISM
-- -------------------
-- The UNIQUE constraint on context_id is the single atomic gate.
-- PostgreSQL automatically creates one unique index to back this
-- constraint. No additional explicit unique index is needed or wanted.
-- Two concurrent INSERT attempts for the same context_id → exactly
-- one succeeds. The application never performs check-then-act in
-- application code — the uniqueness is enforced at database level.
--
-- context_id format: fxctx-<32 lowercase hex chars>
-- Generated by: api/estimator-v1/fixeo-estimator-runtime-v1.js
-- Used by:      api/fixeo-estimator-idempotency-v1.js
--
-- SECURITY ARCHITECTURE
-- ---------------------
-- This table is SERVER-ONLY infrastructure.
-- Inserts and updates arrive exclusively from the Vercel serverless
-- function api/server.js via api/fixeo-estimator-idempotency-v1.js,
-- which uses the Supabase SERVICE ROLE key (server-side env var,
-- never exposed to browser).
--
-- The service role bypasses RLS at the Supabase PostgREST layer,
-- so no anon or authenticated INSERT policy is needed or wanted.
--
-- Role access summary:
--   anon          -> NO access (REVOKE ALL, no policies, no sequence access)
--   authenticated -> NO write access; SELECT only for admin role via policy;
--                    no sequence access (SELECT does not require it)
--   service_role  -> unrestricted (bypasses RLS — Vercel fn + Supabase Studio)
--
-- RLS is ENABLED and FORCED as defence-in-depth.
-- If SUPABASE_SERVICE_ROLE_KEY is ever accidentally replaced with
-- the anon key, all writes will be blocked — not silently accepted.
--
-- PROFILES ADMIN CONTRACT (verified from production migration history)
-- -------------------------------------------------------------------
-- The ecr_admin_select policy uses:
--   EXISTS (SELECT 1 FROM public.profiles
--           WHERE profiles.id = auth.uid() AND profiles.role = 'admin')
--
-- This exact expression is the canonical FIXEO admin check used in:
--   enterprise_leads.sql, notifications-table-v1.sql,
--   rls-fix-2026-04-29.sql, rls-claim-requests-v1.sql,
--   rls-artisan-read-linked-requests.sql, rls-artisan-update-requests.sql,
--   rls-missions-artisan-select.sql (10+ policies total).
--
-- public.profiles has: id (UUID PK, FK to auth.users), role (TEXT).
-- It is the production name for the table created as public.users in
-- schema.sql — confirmed by rls-fix-2026-04-29.sql comment:
--   "TABLE: profiles (was: public.users in schema.sql)"
--
-- STATE MACHINE
-- -------------
-- 'acquired'  → context reserved; booking creation in progress
-- 'committed' → booking successfully created; context permanently consumed
-- 'failed'    → booking creation failed; context available for retry
--
-- Transitions:
--   [not-exists] → INSERT → 'acquired'
--   'acquired'   → PATCH  → 'committed'   (success: commit booking_ref)
--   'acquired'   → PATCH  → 'failed'      (failure: allow retry)
--   'failed'     → PATCH  → 'acquired'    (re-acquire for retry)
--
-- SAFE TO RE-RUN
-- --------------
-- All statements use IF NOT EXISTS / DROP IF EXISTS / or are idempotent.
-- Running this script twice on the same database is harmless.
-- See Section 9 for detailed re-run safety analysis.
-- ============================================================


-- ============================================================
-- SECTION 1 — CREATE TABLE
-- ============================================================

CREATE TABLE IF NOT EXISTS public.estimator_context_redemptions (

  -- Primary key (surrogate — context_id is the real identity key)
  id                bigserial     PRIMARY KEY,

  -- ── IDEMPOTENCY KEY ─────────────────────────────────────────────────────
  -- context_id is the atomic replay boundary.
  -- Format: fxctx-<32 lowercase hex chars>
  -- Generated server-side only (api/estimator-v1/fixeo-estimator-runtime-v1.js).
  -- The UNIQUE constraint in Section 2 provides database-level atomicity
  -- for concurrent INSERT attempts. Never forge-able from the browser
  -- (AES-256-GCM sealed token).
  context_id        text          NOT NULL,

  -- ── IDENTITY FIELDS (written on INSERT, used for conflict detection) ─────
  -- All three are required by consumeEstimatorContext() bookingCandidate param.
  outcome_type      text          NOT NULL,
  service_code      text          NOT NULL,
  session_id        text          NOT NULL,

  -- ── PRICE AUDIT (server-canonical, written on INSERT for admin audit) ────
  -- amount_mad is the server-authoritative canonical amount from the sealed
  -- pricing context token. Stored for audit/admin only — NOT used to re-derive
  -- booking amounts. Bookings always use the live token authority, not this.
  amount_mad        integer       NOT NULL,

  -- ── STATE MACHINE ───────────────────────────────────────────────────────
  -- Valid values: 'acquired' | 'committed' | 'failed'
  -- CHECK constraint enforces the exact values known to the runtime.
  state             text          NOT NULL DEFAULT 'acquired'
                                  CHECK (state IN ('acquired', 'committed', 'failed')),

  -- ── BOOKING BINDING (populated on commitEstimatorContext) ───────────────
  -- Set to NULL on INSERT; bound to the real booking on PATCH to 'committed'.
  -- booking_ref: COD booking reference (e.g. COD-LK3X2Y)
  -- order_id:    COD orderID from the browser request
  booking_ref       text,
  order_id          text,

  -- ── FAILURE AUDIT (populated on failEstimatorContext) ───────────────────
  -- failure_reason: up to 500 chars (truncated by runtime before storage).
  -- Set back to NULL on re-acquire (recovery path).
  failure_reason    text          CHECK (failure_reason IS NULL OR char_length(failure_reason) <= 500),

  -- ── TIMESTAMPS ──────────────────────────────────────────────────────────
  -- acquired_at: ISO timestamp of the most recent acquisition attempt.
  -- Set on INSERT and also on re-acquire (recovery path PATCH).
  acquired_at       timestamptz   NOT NULL DEFAULT now(),

  -- committed_at: ISO timestamp when context was committed (booking created).
  -- NULL until state = 'committed'.
  committed_at      timestamptz,

  -- failed_at: ISO timestamp of most recent failure.
  -- NULL until state = 'failed'. Reset to NULL on re-acquire.
  failed_at         timestamptz

);

-- Table comments
COMMENT ON TABLE public.estimator_context_redemptions IS
  'Durable idempotency table for estimator-backed COD bookings. '
  'context_id (UNIQUE) is the atomic replay boundary. '
  'Inserted server-side by api/server.js via fixeo-estimator-idempotency-v1.js '
  'using service_role key. anon has no access. '
  'Phase 7C.9E / 7C.9F / 7C.9F.1 — Version 1.1';

COMMENT ON COLUMN public.estimator_context_redemptions.context_id IS
  'Atomic idempotency key. Format: fxctx-<32hex>. Server-generated only. '
  'UNIQUE constraint (estimator_context_redemptions_context_id_unique) is the '
  'sole concurrency safety mechanism. One implicit unique index backs it.';

COMMENT ON COLUMN public.estimator_context_redemptions.state IS
  'State machine: acquired → committed (success) or failed (retry allowed). '
  'Only committed contexts are permanently consumed. '
  'failed contexts can be re-acquired.';

COMMENT ON COLUMN public.estimator_context_redemptions.amount_mad IS
  'Server-canonical booking amount in MAD (from sealed pricing context token). '
  'Stored for audit only. Booking price authority is always the live token — not this column.';

COMMENT ON COLUMN public.estimator_context_redemptions.booking_ref IS
  'COD booking reference (e.g. COD-LK3X2Y). NULL until committed.';

COMMENT ON COLUMN public.estimator_context_redemptions.failure_reason IS
  'Failure description from failEstimatorContext(). Max 500 chars. '
  'Reset to NULL on re-acquire (recovery path).';


-- ============================================================
-- SECTION 2 — UNIQUE CONSTRAINT (SOLE ATOMICITY MECHANISM)
-- ============================================================
-- This is the single canonical idempotency gate.
-- Concurrent INSERT for the same context_id → exactly one succeeds.
--
-- PostgreSQL creates exactly ONE unique index to back this constraint.
-- No additional explicit unique index is created (see Section 3).
-- Named explicitly for documentation and error-handling reference.

ALTER TABLE public.estimator_context_redemptions
  DROP CONSTRAINT IF EXISTS estimator_context_redemptions_context_id_unique;

ALTER TABLE public.estimator_context_redemptions
  ADD CONSTRAINT estimator_context_redemptions_context_id_unique
  UNIQUE (context_id);


-- ============================================================
-- SECTION 3 — SUPPORTING INDEXES (non-uniqueness)
-- ============================================================
-- The unique index for context_id is created implicitly by the
-- UNIQUE constraint in Section 2 and is NOT repeated here.
--
-- After this section the total index set is:
--   1. estimator_context_redemptions_pkey        (btree on id, from PRIMARY KEY)
--   2. estimator_context_redemptions_context_id_unique
--                                                (btree on context_id, from UNIQUE constraint)
--   3. idx_ecr_acquired_at                       (btree on acquired_at DESC, admin audit)
--   4. idx_ecr_state                             (btree on state, admin audit)
--   5. idx_ecr_service_code                      (btree on service_code, admin audit)
--
-- Total expected by VQ-4: 5

CREATE INDEX IF NOT EXISTS idx_ecr_acquired_at
  ON public.estimator_context_redemptions (acquired_at DESC);

CREATE INDEX IF NOT EXISTS idx_ecr_state
  ON public.estimator_context_redemptions (state);

CREATE INDEX IF NOT EXISTS idx_ecr_service_code
  ON public.estimator_context_redemptions (service_code);


-- ============================================================
-- SECTION 4 — ROW LEVEL SECURITY
-- ============================================================
-- Enable RLS (defence-in-depth).
-- service_role bypasses RLS — all Vercel fn writes go through service_role.
-- anon and authenticated cannot write to this table.
-- ENABLE and FORCE are idempotent — safe to run twice.

ALTER TABLE public.estimator_context_redemptions ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.estimator_context_redemptions FORCE ROW LEVEL SECURITY;


-- ============================================================
-- SECTION 5 — REVOKE ALL (anon + authenticated + sequence)
-- ============================================================

-- anon: zero table access
REVOKE ALL ON public.estimator_context_redemptions FROM anon;

-- authenticated: start from zero; selective re-grant in Section 7
REVOKE ALL ON public.estimator_context_redemptions FROM authenticated;

-- Sequence: anon and authenticated need no sequence access.
-- SELECT operations do not require sequence USAGE or SELECT.
-- service_role retains implicit unrestricted access (not affected by REVOKE).
REVOKE ALL ON SEQUENCE public.estimator_context_redemptions_id_seq FROM anon;
REVOKE ALL ON SEQUENCE public.estimator_context_redemptions_id_seq FROM authenticated;

-- Drop any previously created policies (idempotent cleanup before re-create)
DROP POLICY IF EXISTS "ecr_anon_insert"  ON public.estimator_context_redemptions;
DROP POLICY IF EXISTS "ecr_anon_select"  ON public.estimator_context_redemptions;
DROP POLICY IF EXISTS "ecr_anon_update"  ON public.estimator_context_redemptions;
DROP POLICY IF EXISTS "ecr_anon_delete"  ON public.estimator_context_redemptions;
DROP POLICY IF EXISTS "ecr_auth_insert"  ON public.estimator_context_redemptions;
DROP POLICY IF EXISTS "ecr_auth_update"  ON public.estimator_context_redemptions;


-- ============================================================
-- SECTION 6 — RLS POLICIES
-- ============================================================

-- 6-A: Admin SELECT — read-only audit access for authenticated admins.
-- Identified by: profiles.id = auth.uid() AND profiles.role = 'admin'
--
-- This pattern is the canonical FIXEO admin check verified from production
-- migration history (10+ existing policies across rls-fix-2026-04-29.sql,
-- enterprise_leads.sql, notifications-table-v1.sql, rls-claim-requests-v1.sql,
-- rls-artisan-*.sql, and others). public.profiles has columns:
--   id   UUID  (PK, FK to auth.users)
--   role TEXT  (values: 'admin' | 'artisan' | 'client')
--
-- Non-admin authenticated users see zero rows (policy USING = false for them).
-- service_role bypasses this entirely (unrestricted, no policy needed).
DROP POLICY IF EXISTS "ecr_admin_select" ON public.estimator_context_redemptions;

CREATE POLICY "ecr_admin_select"
  ON public.estimator_context_redemptions
  FOR SELECT
  TO authenticated
  USING (
    EXISTS (
      SELECT 1
      FROM public.profiles
      WHERE profiles.id   = auth.uid()
        AND profiles.role = 'admin'
    )
  );

-- NOTE: No authenticated INSERT, UPDATE, or DELETE policy.
-- All writes go through the Vercel fn using service_role.
-- RLS default-deny blocks any authenticated INSERT/UPDATE/DELETE.
-- No anon policy exists → anon gets zero access (RLS default-deny + REVOKE ALL).


-- ============================================================
-- SECTION 7 — GRANTS (minimal, targeted)
-- ============================================================

-- anon: zero grants (REVOKE ALL already issued in Section 5)
-- (No GRANT to anon — REVOKE is the sole statement for anon)

-- authenticated: SELECT only.
-- INSERT/UPDATE/DELETE blocked by:
--   (a) no INSERT/UPDATE/DELETE policy (RLS default-deny)
--   (b) REVOKE ALL in Section 5 + only SELECT re-granted here
GRANT SELECT ON public.estimator_context_redemptions TO authenticated;

-- Schema usage: required for authenticated to resolve table references.
-- Supabase normally grants this by default; explicit for safety.
GRANT USAGE ON SCHEMA public TO authenticated;

-- Sequence: NOT granted to authenticated or anon.
-- SELECT does not require sequence access.
-- service_role retains implicit access (INSERT uses the bigserial sequence
-- server-side only; no explicit grant needed for service_role).


-- ============================================================
-- SECTION 8 — PROFILES ADMIN CONTRACT VERIFICATION NOTE
-- ============================================================
-- The ecr_admin_select policy references public.profiles.role.
-- Evidence from production migration history:
--
-- File: supabase/rls-fix-2026-04-29.sql
--   Comment: "TABLE: profiles (was: public.users in schema.sql)"
--   SQL: ALTER TABLE public.profiles ENABLE ROW LEVEL SECURITY;
--        CREATE POLICY "profiles_self_read" ON public.profiles ...
--        CREATE POLICY "profiles_admin_all" ON public.profiles ...
--        EXISTS (SELECT 1 FROM public.profiles p WHERE p.id = auth.uid() AND p.role = 'admin')
--
-- File: supabase/enterprise_leads.sql
--   EXISTS (SELECT 1 FROM public.profiles WHERE profiles.id = auth.uid() AND profiles.role = 'admin')
--   (used in SELECT, UPDATE, and TRUNCATE policies)
--
-- File: supabase/notifications-table-v1.sql
--   SELECT 1 FROM public.profiles p WHERE p.id = auth.uid() AND p.role = 'admin'
--
-- File: supabase/rls-claim-requests-v1.sql
--   SELECT 1 FROM public.profiles p WHERE p.id = auth.uid() AND p.role = 'admin'
--
-- File: supabase/rls-artisan-read-linked-requests.sql
--   FROM public.profiles p / AND p.role = 'admin'
--
-- Conclusion: the profiles.id / profiles.role admin pattern is PROVEN
-- by existing committed production SQL. ecr_admin_select is correct.
-- public.profiles has: id (UUID), role (TEXT, values: admin/artisan/client).
-- DO NOT modify public.profiles.


-- ============================================================
-- SECTION 9 — RE-RUN SAFETY ANALYSIS
-- ============================================================
-- Each statement class and its idempotency behavior:
--
-- CREATE TABLE IF NOT EXISTS
--   → No-op if table already exists. Columns/constraints already present
--     are preserved. New columns not added (no ALTER TABLE ADD COLUMN here).
--   → SAFE.
--
-- COMMENT ON TABLE / COLUMN
--   → Replaces existing comment. No structural change.
--   → SAFE.
--
-- DROP CONSTRAINT IF EXISTS ... / ADD CONSTRAINT ... UNIQUE
--   → DROP: no-op if constraint doesn't exist.
--   → ADD: re-creates the constraint. If constraint already exists with
--     the same name AND same definition, this is effectively idempotent
--     because DROP precedes it. If re-run on a live table with data,
--     the ADD will succeed as long as no duplicate context_id rows exist
--     (which is guaranteed by the constraint itself — if it was enforced
--     during normal operation, no duplicates can exist).
--   → SAFE (when data invariant holds — guaranteed by constraint enforcement).
--
-- CREATE INDEX IF NOT EXISTS
--   → No-op if index already exists with the same name.
--   → SAFE.
--
-- ALTER TABLE ... ENABLE ROW LEVEL SECURITY
--   → Idempotent — enabling already-enabled RLS is a no-op.
--   → SAFE.
--
-- ALTER TABLE ... FORCE ROW LEVEL SECURITY
--   → Idempotent — forcing already-forced RLS is a no-op.
--   → SAFE.
--
-- REVOKE ALL
--   → Revoking privileges that weren't granted is a no-op (no error).
--   → SAFE.
--
-- DROP POLICY IF EXISTS
--   → No-op if policy doesn't exist.
--   → SAFE.
--
-- CREATE POLICY (after DROP IF EXISTS)
--   → Always creates fresh — previous DROP ensures no "already exists" error.
--   → SAFE.
--
-- GRANT SELECT
--   → Re-granting an already-held privilege is a no-op.
--   → SAFE.
--
-- Sequence availability after bigserial CREATE TABLE IF NOT EXISTS:
--   → If table already exists, bigserial sequence was created on first run
--     and persists. REVOKE on the sequence is idempotent.
--   → If table does not yet exist, bigserial creates both table and sequence.
--   → SAFE in both cases.
--
-- CONCLUSION: This migration is safe to run twice (or more).
-- No data is deleted, no columns are dropped, no tables are dropped.


-- ============================================================
-- SECTION 10 — VERIFICATION QUERIES (VQ-1 through VQ-9)
-- Run AFTER applying this migration to confirm all expectations.
-- Each query documents its exact expected result.
-- Run queries individually in Supabase SQL Editor.
-- ============================================================

-- VQ-1: All 13 columns present with correct types
-- Expected: 13 rows (ordinal_position 1–13)
-- Columns: id, context_id, outcome_type, service_code, session_id,
--          amount_mad, state, booking_ref, order_id, failure_reason,
--          acquired_at, committed_at, failed_at
SELECT
  ordinal_position,
  column_name,
  data_type,
  is_nullable,
  column_default
FROM information_schema.columns
WHERE table_schema = 'public'
  AND table_name   = 'estimator_context_redemptions'
ORDER BY ordinal_position;

-- VQ-2: RLS enabled AND forced
-- Expected: relrowsecurity = true, relforcerowsecurity = true
SELECT
  relname             AS table_name,
  relrowsecurity      AS rls_enabled,
  relforcerowsecurity AS rls_forced
FROM pg_class
WHERE relname = 'estimator_context_redemptions';

-- VQ-3: Exactly ONE UNIQUE constraint on context_id
-- Expected: exactly 1 row
--   conname = 'estimator_context_redemptions_context_id_unique'
--   contype = 'u'
--   definition = 'UNIQUE (context_id)'
SELECT conname, contype, pg_get_constraintdef(oid) AS definition
FROM pg_constraint
WHERE conrelid = 'public.estimator_context_redemptions'::regclass
  AND contype  = 'u';

-- VQ-4: Exactly 5 indexes
-- Expected: exactly 5 rows, in this order (alphabetical):
--   estimator_context_redemptions_context_id_unique  (UNIQUE btree on context_id — backs UNIQUE constraint)
--   estimator_context_redemptions_pkey               (btree on id — PRIMARY KEY)
--   idx_ecr_acquired_at                              (btree on acquired_at DESC)
--   idx_ecr_service_code                             (btree on service_code)
--   idx_ecr_state                                    (btree on state)
SELECT indexname, indexdef
FROM pg_indexes
WHERE tablename = 'estimator_context_redemptions'
ORDER BY indexname;

-- VQ-5: anon has zero table privileges
-- Expected: zero rows (anon is not listed as grantee for any privilege)
SELECT grantee, privilege_type
FROM information_schema.role_table_grants
WHERE table_name = 'estimator_context_redemptions'
  AND grantee    = 'anon';

-- VQ-6: authenticated has SELECT only — zero INSERT/UPDATE/DELETE/TRUNCATE
-- Expected: exactly 1 row — privilege_type = 'SELECT', grantee = 'authenticated'
-- Must NOT contain INSERT, UPDATE, DELETE, TRUNCATE
SELECT grantee, privilege_type
FROM information_schema.role_table_grants
WHERE table_name = 'estimator_context_redemptions'
  AND grantee    = 'authenticated';

-- VQ-7: anon and authenticated have zero sequence privileges
-- Expected: zero rows for both anon and authenticated
SELECT grantee, privilege_type
FROM information_schema.role_usage_grants
WHERE object_name = 'estimator_context_redemptions_id_seq'
  AND grantee IN ('anon', 'authenticated');

-- VQ-8: Policies — exactly 1 policy
-- Expected: 1 row
--   policyname = 'ecr_admin_select'
--   roles      = '{authenticated}'
--   command    = 'SELECT'
SELECT policyname, roles, cmd AS command, qual AS using_expr
FROM pg_policies
WHERE tablename = 'estimator_context_redemptions'
ORDER BY policyname;

-- VQ-9: Baseline empty (no rows before preview QA)
-- Expected: 0
SELECT COUNT(*) AS baseline_row_count
FROM public.estimator_context_redemptions;


-- ============================================================
-- OPTIONAL: Test INSERT cycle (runs as service_role in SQL Editor)
-- Run only if you want to verify the live constraint and PATCH behavior.
-- ALWAYS run the cleanup at the end.
-- ============================================================

-- TEST-A: Insert test row (simulates Vercel fn)
-- Expected: 1 row returned with id, context_id, state='acquired'
INSERT INTO public.estimator_context_redemptions (
  context_id, outcome_type, service_code, session_id,
  amount_mad, state, acquired_at
) VALUES (
  'fxctx-00000000000000000000000000000000',
  'PRICE_READY', 'test.schema_verify', 'sess-test-7c9f1',
  300, 'acquired', now()
)
RETURNING id, context_id, state, acquired_at;

-- TEST-B: Duplicate INSERT — must fail with unique constraint violation
-- Expected: ERROR: duplicate key value violates unique constraint
-- "estimator_context_redemptions_context_id_unique"
INSERT INTO public.estimator_context_redemptions (
  context_id, outcome_type, service_code, session_id,
  amount_mad, state, acquired_at
) VALUES (
  'fxctx-00000000000000000000000000000000',
  'PRICE_READY', 'test.schema_verify', 'sess-test-different',
  300, 'acquired', now()
);

-- TEST-C: PATCH to committed (simulates commitEstimatorContext)
-- Expected: 1 row returned, state='committed', booking_ref='COD-TESTREF'
UPDATE public.estimator_context_redemptions
SET
  state        = 'committed',
  booking_ref  = 'COD-TESTREF',
  order_id     = 'ORD-TEST-7C9F1',
  committed_at = now()
WHERE context_id = 'fxctx-00000000000000000000000000000000'
RETURNING id, context_id, state, booking_ref, committed_at;

-- TEST-D: Invalid state — must fail with CHECK constraint violation
-- Expected: ERROR: new row violates check constraint "estimator_context_redemptions_state_check"
UPDATE public.estimator_context_redemptions
SET state = 'invalid_state'
WHERE context_id = 'fxctx-00000000000000000000000000000000';

-- TEST-CLEANUP: Remove test row
DELETE FROM public.estimator_context_redemptions
WHERE context_id = 'fxctx-00000000000000000000000000000000';

-- TEST-CONFIRM: Should be 0 after cleanup
SELECT COUNT(*) AS rows_after_cleanup FROM public.estimator_context_redemptions;
