const {test}=require('node:test');
const assert=require('node:assert/strict');
const fs=require('node:fs');
const {PGlite}=require('@electric-sql/pglite');
const sql=fs.readFileSync('supabase/migrations/20261005104459_mobile_w5_artisan_bio.sql','utf8');
const authority=fs.readFileSync('supabase/migrations/20261005085640_mobile_w5_artisan_authority_v2.sql','utf8').split('-- W5_AUTHORITY_CORE_BEGIN')[1].split('-- W5_AUTHORITY_CORE_END')[0];
const uid='aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaaa',client='bbbbbbbb-bbbb-4bbb-8bbb-bbbbbbbbbbbb',sid='cccccccc-cccc-4ccc-8ccc-cccccccccccc',aid='dddddddd-dddd-4ddd-8ddd-dddddddddddd';
test('W5 Bio: additive definition, canonical authority, timestamp exception, exact other columns, owner isolation and length',async()=>{
 const db=new PGlite();try{
  await db.exec(`CREATE ROLE authenticated;CREATE ROLE anon;CREATE ROLE service_role;CREATE SCHEMA auth;CREATE SCHEMA fixeo_private;
   CREATE TABLE local_users(id uuid primary key,deleted_at timestamptz,banned_until timestamptz);
   CREATE TABLE local_sessions(id uuid primary key,user_id uuid,not_after timestamptz);
   CREATE VIEW auth.users AS SELECT * FROM local_users;CREATE VIEW auth.sessions AS SELECT * FROM local_sessions;
   CREATE FUNCTION auth.uid() RETURNS uuid LANGUAGE sql STABLE AS $$SELECT (current_setting('request.jwt.claims',true)::jsonb->>'sub')::uuid$$;
   CREATE FUNCTION auth.jwt() RETURNS jsonb LANGUAGE sql STABLE AS $$SELECT current_setting('request.jwt.claims',true)::jsonb$$;
   CREATE TABLE public.users(id uuid primary key,role text);
   CREATE TABLE public.artisans(id uuid primary key,owner_user_id uuid,description text,updated_at timestamptz,name text,city text,verified boolean);
   CREATE FUNCTION public.update_updated_at() RETURNS trigger LANGUAGE plpgsql AS $$BEGIN NEW.updated_at = NOW(); RETURN NEW; END;$$;
   CREATE TRIGGER artisans_updated_at BEFORE UPDATE ON public.artisans FOR EACH ROW EXECUTE FUNCTION public.update_updated_at();
   INSERT INTO local_users(id) VALUES('${uid}'),('${client}');INSERT INTO local_sessions VALUES('${sid}','${uid}',null);
   INSERT INTO public.users VALUES('${uid}','artisan'),('${client}','client');
   INSERT INTO public.artisans VALUES('${aid}','${uid}','Avant','2026-10-01','Atelier','Rabat',false),('${client}','${client}','Étranger','2026-10-01','Autre','Fès',true);
   GRANT USAGE ON SCHEMA auth,public,fixeo_private TO authenticated,anon;
  `);
  await db.exec(authority);
  const rows=async()=>(await db.query('SELECT to_jsonb(a) AS value FROM public.artisans a ORDER BY id')).rows.map(x=>x.value);
  const before=await rows();await db.exec(sql);assert.deepEqual(await rows(),before);
  assert.equal((await db.query("SELECT has_function_privilege('anon','public.w5_update_my_artisan_bio_v1(text)','EXECUTE') AS ok")).rows[0].ok,false);
  assert.equal((await db.query("SELECT has_function_privilege('authenticated','public.w5_update_my_artisan_bio_v1(text)','EXECUTE') AS ok")).rows[0].ok,true);
  const claims=async(subject=uid)=>db.query("SELECT set_config('request.jwt.claims',$1,false)",[JSON.stringify({sub:subject,session_id:sid})]);
  await claims();await db.exec('SET ROLE authenticated');
  await assert.rejects(db.query("UPDATE public.artisans SET description='direct' WHERE id=$1",[aid]),/permission denied/);
  const call=(text)=>db.query('SELECT public.w5_update_my_artisan_bio_v1($1) AS result',[text]);
  assert.equal((await call('  Bio professionnelle · مرحبا  ')).rows[0].result.ok,true);
  await db.exec('RESET ROLE');const after=await rows();
  const mineBefore=before.find(x=>x.id===aid),mineAfter=after.find(x=>x.id===aid);
  assert.equal(mineAfter.description,'Bio professionnelle · مرحبا');
  assert.deepEqual(Object.keys(mineBefore).filter(k=>mineBefore[k]!==mineAfter[k]).sort(),['description','updated_at']);
  assert.deepEqual(after.find(x=>x.id===client),before.find(x=>x.id===client));
  await db.exec('SET ROLE authenticated');
  assert.equal((await call('é'.repeat(4000))).rows[0].result.ok,true);
  await assert.rejects(call('é'.repeat(4001)),/BIO_TOO_LONG/);
  await assert.rejects(db.query('SELECT public.w5_update_my_artisan_bio_v1($1,$2)',['attaque',client]),/does not exist/);
  await db.exec('RESET ROLE');await claims(client);await db.exec('SET ROLE authenticated');
  await assert.rejects(call('Client'),/ARTISAN_REQUIRED/);
  await db.exec('RESET ROLE');await claims();await db.exec('DELETE FROM local_sessions');await db.exec('SET ROLE authenticated');
  await assert.rejects(call('Révoqué'),/SESSION_REVOKED/);
  await db.exec('RESET ROLE');await claims(null);await db.exec('SET ROLE authenticated');
  await assert.rejects(call('Sans acteur'),/AUTH_REQUIRED/);
 }finally{await db.close();}
});
test('W5 Bio migration creates only its approved RPC and leaves table rights and triggers intact',()=>{
 for(const keyword of ['DROP','DELETE','TRUNCATE'])assert.doesNotMatch(sql,new RegExp('\\b'+keyword+'\\b','i'));
 assert.equal((sql.match(/CREATE FUNCTION/g)||[]).length,1);
 assert.match(sql,/SET description = v_description\s+WHERE id = v_artisan_id AND owner_user_id = auth.uid\(\)/);
 assert.doesNotMatch(sql,/ALTER TABLE|CREATE TRIGGER|ALTER FUNCTION|GRANT.*ON TABLE|SET\s+updated_at/i);
 const top=sql.replace(/\$w5_bio\$[\s\S]*?\$w5_bio\$/,"'body'").replace(/--[^\n]*/g,'');
 assert.doesNotMatch(top,/(?:^|;)\s*(?:INSERT|UPDATE|DELETE|TRUNCATE|CALL|SELECT)\b/i);
});
