const {test}=require('node:test');
const assert=require('node:assert/strict');
const fs=require('node:fs');
const {PGlite}=require('@electric-sql/pglite');
const prior=fs.readFileSync('supabase/migrations/20261005085640_mobile_w5_artisan_authority_v2.sql','utf8');
const migration=fs.readFileSync('supabase/migrations/20261007181756_pb1_post_audit_integrity.sql','utf8');
const original=name=>prior.match(new RegExp('CREATE OR REPLACE FUNCTION public\\.'+name+'\\([^]*?\\$function\\$[^]*?\\$function\\$\\s*;'))[0];
const u='aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaaa',a='bbbbbbbb-bbbb-4bbb-8bbb-bbbbbbbbbbbb',s='cccccccc-cccc-4ccc-8ccc-cccccccccccc',r='dddddddd-dddd-4ddd-8ddd-dddddddddddd',foreign='eeeeeeee-eeee-4eee-8eee-eeeeeeeeeeee';
test('PB1 post audit: exact SQL, stale profile repair without forced availability, missing fields, guarded quote source/title/lines and legacy bypass refusal',async()=>{
 const db=new PGlite();try{
 await db.exec(`CREATE ROLE anon;CREATE ROLE authenticated;CREATE ROLE service_role;CREATE SCHEMA auth;CREATE SCHEMA fixeo_private;
 CREATE TABLE local_actors(id uuid primary key,deleted_at timestamptz,banned_until timestamptz);
 CREATE TABLE local_sessions(id uuid primary key,user_id uuid,not_after timestamptz);
 CREATE VIEW auth.users AS SELECT * FROM local_actors;CREATE VIEW auth.sessions AS SELECT * FROM local_sessions;
 CREATE FUNCTION auth.uid() RETURNS uuid LANGUAGE sql STABLE AS $$SELECT (current_setting('request.jwt.claims',true)::jsonb->>'sub')::uuid$$;
 CREATE FUNCTION auth.jwt() RETURNS jsonb LANGUAGE sql STABLE AS $$SELECT current_setting('request.jwt.claims',true)::jsonb$$;
 CREATE TABLE users(id uuid primary key,role text);
 CREATE TABLE artisans(id uuid primary key,owner_user_id uuid,updated_at timestamptz,full_name text,phone_public text,description text,service_category text,category text,services jsonb,city text,claimed boolean,claim_status text,onboarding_completed boolean,availability text,verified boolean);
 CREATE TABLE service_requests(id uuid primary key,status text,city text,service_category text,pricing_offer_id uuid,description text);
 CREATE TABLE dispatch_execution_queue(request_id uuid,artisan_id uuid,execution_status text);
 CREATE TABLE enterprise_request_context(service_request_id uuid);
 CREATE TABLE artisan_service_cities(artisan_id uuid,city text);CREATE TABLE artisan_service_categories(artisan_id uuid,service_category text);
 CREATE TABLE quotes(id uuid primary key default gen_random_uuid(),request_id uuid,artisan_profile_id uuid,proposed_price numeric,service_description text,supplies_description text,estimated_duration text,message text,status text,submitted_at timestamptz,review_status text,created_at timestamptz default now(),quote_version integer default 1,reviewed_version integer,reviewed_at timestamptz,reviewed_by uuid,review_reason text,presented_at timestamptz,expires_at timestamptz);
 CREATE TABLE artisan_business_quotes(id text,title text,total numeric,status text,source text);
 CREATE TABLE fixeo_private.mobile_intelligence_config_v1(singleton boolean,project_ref text,enabled boolean);
 INSERT INTO fixeo_private.mobile_intelligence_config_v1 VALUES(true,'kqyhusnbybsukbcaoqtu',false);
 INSERT INTO local_actors(id) VALUES('${u}');INSERT INTO local_sessions VALUES('${s}','${u}',null);INSERT INTO users VALUES('${u}','artisan');
 INSERT INTO artisans VALUES('${a}','${u}',now(),'PB1 Artisan Test','+212600000000','Présentation','Plomberie',null,'["Plomberie"]','Fès',true,'approved',false,'unavailable',false);
 INSERT INTO service_requests VALUES('${r}','new','Fès','Plomberie',null,'Fuite');INSERT INTO dispatch_execution_queue VALUES('${r}','${a}','QUEUED');
 INSERT INTO artisan_business_quotes VALUES('DEV-2026-0001','Réparation',500,'sent','personal');
 GRANT USAGE ON SCHEMA public,auth,fixeo_private TO authenticated,anon,service_role;`);
 await db.exec(prior.split('-- W5_AUTHORITY_CORE_BEGIN')[1].split('-- W5_AUTHORITY_CORE_END')[0]);
 await db.exec(original('update_artisan_availability'));await db.exec(original('submit_artisan_quote_v2'));
 await db.exec('REVOKE ALL ON FUNCTION update_artisan_availability(text) FROM PUBLIC;GRANT EXECUTE ON FUNCTION update_artisan_availability(text) TO authenticated,service_role;');
 const snapshot=async()=>JSON.stringify((await db.query('SELECT to_jsonb(a) row FROM artisans a')).rows);
 const before=await snapshot(),personal=(await db.query('SELECT * FROM artisan_business_quotes')).rows;
 const oldQuote=(await db.query("SELECT pg_get_functiondef('submit_artisan_quote_v2(uuid,numeric,text,text,text,text)'::regprocedure) body")).rows[0].body;
 await db.exec(migration);
 assert.equal(await snapshot(),before,'migration must not backfill identity/availability');
 assert.equal((await db.query("SELECT pg_get_functiondef('submit_artisan_quote_v2(uuid,numeric,text,text,text,text)'::regprocedure) body")).rows[0].body,oldQuote);
 await db.query("SELECT set_config('request.jwt.claims',$1,false)",[JSON.stringify({sub:u,session_id:s})]);await db.exec('SET ROLE authenticated');
 const gate=async()=>(await db.query('SELECT get_my_artisan_profile_gate_v1() result')).rows[0].result;
 assert.equal((await gate()).complete,true,'derive from real fields despite stale false flag');
 await db.exec('RESET ROLE');assert.equal(await snapshot(),before,'reading must not force availability');
 await db.exec("UPDATE artisans SET description='Présentation enrichie' WHERE id='"+a+"'");
 assert.deepEqual((await db.query('SELECT onboarding_completed,availability,verified,claim_status FROM artisans')).rows,[{onboarding_completed:true,availability:'unavailable',verified:false,claim_status:'approved'}]);
 await db.exec("UPDATE artisans SET full_name='' WHERE id='"+a+"';SET ROLE authenticated;");
 assert.deepEqual((await gate()).missing_fields,['full_name']);
 let result=(await db.query("SELECT update_artisan_availability('available') result")).rows[0].result;assert.equal(result.reason,'profile_incomplete');assert.deepEqual(result.missing_fields,['full_name']);
 assert.equal((await db.query("SELECT update_artisan_availability('unavailable') result")).rows[0].result.ok,true);
 await db.exec("RESET ROLE;UPDATE artisans SET full_name='PB1 Artisan Test' WHERE id='"+a+"';SET ROLE authenticated;");
 assert.equal((await db.query("SELECT update_artisan_availability('available') result")).rows[0].result.status,'available');
 const lines=[{type:'service',label:'Main-d’œuvre',quantity:3,unit_price:0.335},{type:'supply',label:'Matériel',quantity:1,unit_price:498.99}];
 const submit=(id=r,title='Réparation',items=lines)=>db.query('SELECT to_jsonb(submit_my_mobile_quote_v1($1,$2,$3::jsonb,null,null)) q',[id,title,JSON.stringify(items)]);
 for(const [id,title,items,error] of [[null,'Réparation',lines,/SOURCE/],[foreign,'Réparation',lines,/SOURCE/],[r,'',lines,/TITLE/],[r,'Réparation',[],/INVALID/],[r,'Réparation',[{...lines[0],quantity:0}],/INVALID/],[r,'Réparation',[lines[1]],/INVALID/],[r,'Réparation',[{...lines[0],unit_price:0}],/INVALID/]]) await assert.rejects(submit(id,title,items),error);
 await assert.rejects(db.query('SELECT submit_artisan_quote_v2($1,500,$2)',[r,'Legacy bypass']),/permission denied/);
 let quote=(await submit()).rows[0].q;assert.equal(quote.proposed_price,500);assert.equal(quote.status,'pending');assert.equal(quote.review_status,'submitted');assert.match(quote.service_description,/Réparation/);assert.equal((await submit()).rows[0].q.id,quote.id,'same submission idempotent');
 await db.exec("RESET ROLE;UPDATE dispatch_execution_queue SET execution_status='CANCELLED';SET ROLE authenticated;");await assert.rejects(submit(),/SOURCE/);
 await db.exec("RESET ROLE;UPDATE dispatch_execution_queue SET execution_status='QUEUED',artisan_id='"+foreign+"';SET ROLE authenticated;");await assert.rejects(submit(),/SOURCE/);
 await db.exec("RESET ROLE;UPDATE local_sessions SET not_after=now()-interval '1 second';SET ROLE authenticated;");await assert.rejects(gate(),/SESSION_REVOKED/);await assert.rejects(submit(),/SESSION_REVOKED/);await assert.rejects(db.query("SELECT update_artisan_availability('busy')"),/SESSION_REVOKED/);
 await db.exec('RESET ROLE;SET ROLE anon;');await assert.rejects(gate(),/permission denied/);await assert.rejects(submit(),/permission denied/);
 await db.exec('RESET ROLE');assert.deepEqual((await db.query('SELECT * FROM artisan_business_quotes')).rows,personal,'personal 500 MAD remains unchanged');assert.equal((await db.query('SELECT count(*)::int n FROM quotes')).rows[0].n,1);
 }finally{await db.close();}
});
