BEGIN READ ONLY;
WITH targets AS (SELECT p.*,n.nspname FROM pg_proc p JOIN pg_namespace n ON n.oid=p.pronamespace WHERE n.nspname='public' AND p.prokind='f' AND (p.proname ILIKE '%dispatch%' OR p.proname='enqueue_dispatch_notification_from_mission_v1'))
SELECT jsonb_build_object(
'captured_at',now(),'server_version',current_setting('server_version'),
'functions',(SELECT jsonb_agg(jsonb_build_object('oid',p.oid,'signature',p.oid::regprocedure::text,'name',p.proname,'identity_args',pg_get_function_identity_arguments(p.oid),'args',pg_get_function_arguments(p.oid),'owner',pg_get_userbyid(p.proowner),'language',(SELECT lanname FROM pg_language WHERE oid=p.prolang),'security_definer',p.prosecdef,'volatility',p.provolatile,'config',p.proconfig,'result',pg_get_function_result(p.oid),'definition',pg_get_functiondef(p.oid),'definition_md5',md5(pg_get_functiondef(p.oid)),'acl_raw',p.proacl,'acl_normalized',(SELECT jsonb_agg(jsonb_build_object('grantor',pg_get_userbyid(a.grantor),'grantee',CASE WHEN a.grantee=0 THEN 'PUBLIC' ELSE pg_get_userbyid(a.grantee) END,'privilege',a.privilege_type,'grantable',a.is_grantable) ORDER BY a.grantee,a.privilege_type) FROM aclexplode(COALESCE(p.proacl,acldefault('f',p.proowner)))a),'execute',jsonb_build_object('PUBLIC',EXISTS(SELECT 1 FROM aclexplode(COALESCE(p.proacl,acldefault('f',p.proowner)))a WHERE a.grantee=0 AND a.privilege_type='EXECUTE'),'anon',has_function_privilege('anon',p.oid,'EXECUTE'),'authenticated',has_function_privilege('authenticated',p.oid,'EXECUTE'),'service_role',has_function_privilege('service_role',p.oid,'EXECUTE'),'postgres',has_function_privilege('postgres',p.oid,'EXECUTE'))) ORDER BY p.proname,pg_get_function_identity_arguments(p.oid)) FROM targets p),
'db_source_inventory',(SELECT jsonb_agg(jsonb_build_object('signature',p.oid::regprocedure::text,'schema',n.nspname,'name',p.proname,'definition',pg_get_functiondef(p.oid),'definition_md5',md5(pg_get_functiondef(p.oid))) ORDER BY n.nspname,p.proname,p.oid) FROM pg_proc p JOIN pg_namespace n ON n.oid=p.pronamespace WHERE n.nspname IN('public','fixeo_private') AND p.prokind IN('f','p')),
'triggers',(SELECT jsonb_agg(jsonb_build_object('table',t.tgrelid::regclass::text,'trigger',t.tgname,'enabled',t.tgenabled,'function',t.tgfoid::regprocedure::text,'definition',pg_get_triggerdef(t.oid,true))) FROM pg_trigger t WHERE NOT t.tgisinternal AND t.tgfoid IN (SELECT oid FROM targets)),
'dependencies',(SELECT jsonb_agg(jsonb_build_object('dependent',pg_describe_object(d.classid,d.objid,d.objsubid),'referenced',pg_describe_object(d.refclassid,d.refobjid,d.refobjsubid),'type',d.deptype)) FROM pg_depend d WHERE (d.classid='pg_proc'::regclass AND d.objid IN(SELECT oid FROM targets)) OR (d.refclassid='pg_proc'::regclass AND d.refobjid IN(SELECT oid FROM targets))),
'views',(SELECT jsonb_agg(jsonb_build_object('name',c.oid::regclass::text,'definition',pg_get_viewdef(c.oid,true),'options',c.reloptions)) FROM pg_class c JOIN pg_namespace n ON n.oid=c.relnamespace WHERE n.nspname IN('public','fixeo_private') AND c.relkind IN('v','m')),
'role_memberships',(SELECT jsonb_agg(jsonb_build_object('member',pg_get_userbyid(m.member),'parent',pg_get_userbyid(m.roleid),'inherit',m.inherit_option,'set',m.set_option,'admin',m.admin_option)) FROM pg_auth_members m),
'role_flags',(SELECT jsonb_agg(jsonb_build_object('role',rolname,'superuser',rolsuper,'inherit',rolinherit,'bypassrls',rolbypassrls)) FROM pg_roles WHERE rolname IN('anon','authenticated','service_role','postgres')),
'schema_privileges',(SELECT jsonb_agg(jsonb_build_object('schema',n.nspname,'role',r,'usage',has_schema_privilege(r,n.oid,'USAGE'),'create',has_schema_privilege(r,n.oid,'CREATE'))) FROM pg_namespace n CROSS JOIN unnest(ARRAY['anon','authenticated','service_role','postgres'])r WHERE n.nspname IN('public','fixeo_private')),
'extensions',(SELECT jsonb_agg(jsonb_build_object('name',extname,'version',extversion,'schema',extnamespace::regnamespace::text)) FROM pg_extension),
'cron_job_relation',to_regclass('cron.job')::text,
'function_stats',(SELECT jsonb_agg(jsonb_build_object('signature',s.funcid::regprocedure::text,'calls',s.calls)) FROM pg_stat_user_functions s WHERE s.funcid IN(SELECT oid FROM targets)),
'p0_is_admin_md5',md5(pg_get_functiondef('public.is_admin()'::regprocedure))
) evidence; ROLLBACK;

