'use strict';
const assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),h=require('./http.cjs'),{createHandler}=require('../../../api/control');
const checks=[];async function check(name,fn){const start=Date.now();await fn();checks.push({name,status:'PASS',ms:Date.now()-start});console.log(JSON.stringify(checks.at(-1)));}
(async()=>{
 const roles=['admin','client','artisan','enterprise_owner','enterprise_b_owner'];
 for(const role of roles){try{await h.ensureSession(role);}catch(e){if(!/AUTH_REFRESH_STATUS|SYNTHETIC_SESSION_REQUIRED/.test(e.message))throw e;await h.login(role);}}
 const missing='00000000-0000-4000-8000-999999999999';
 const endpoints=[['decisions',{},'control_rafi_source_v3',{p_source:'trust',p_classification:'all'}],['rafi-followups',{limit:1},'control_rafi_followups_v3',{p_limit:1}],['rafi-followup-evidence',{id:missing},'control_rafi_followup_evidence_v3',{p_id:missing}],['rafi/preview',{},'control_rafi_proposal_v3',{p_proof:{},p_rule:'claim.pending',p_capability:'claim.reject',p_target_id:missing,p_payload:{},p_correlation_id:missing}],['rafi/execute',{preview_id:missing,confirmed:true,idempotency_key:missing},'control_rafi_execute_v3',{p_preview_id:missing,p_confirmed:true,p_idempotency_key:missing}],['rafi-followup',{operation:'acknowledge',id:missing,version:1,idempotency_key:missing},'control_rafi_followup_v3',{p_operation:'acknowledge',p_id:missing,p_version:1,p_proof:null,p_rule:null,p_due_at:null,p_resolution_audit_id:null,p_idempotency_key:missing}]];
 await check('anon_all_six_RPC_denied',async()=>{for(const [,,name,body] of endpoints)assert.ok([401,403,404].includes((await h.request('/rest/v1/rpc/'+name,{body})).status),name);});
 for(const role of roles.slice(1))await check('all_six_RPC_deny_'+role,async()=>{for(const [,,name,body] of endpoints)assert.equal((await h.rpc(role,name,body)).status,403,name);});
 await check('Admin_sources_reads_no_hidden_persistence',async()=>{for(const source of ['operations','network','trust','finance','enterprise']){const r=await h.rpc('admin','control_rafi_source_v3',{p_source:source,p_classification:'all'});assert.equal(r.status,200);assert.equal(r.data.evidence_contract,'rafi-evidence-v3');assert.ok(r.data.observations.every(o=>o.proof.ref&&o.proof.token));}assert.equal((await h.rpc('admin','control_rafi_followups_v3',{p_limit:1})).status,200);});
 const env={VERCEL_ENV:'preview',VERCEL_URL:'isolated-api.invalid',SUPABASE_URL:h.config.url,SUPABASE_ANON_KEY:h.config.key,FIXEO_STAGING_PROJECT_REF:h.REF};
 const api=async(role,op,body)=>{const res={setHeader(){},status(n){this.statusCode=n;return this;},json(v){this.body=v;}};await createHandler({env,fetchImpl:(url,options)=>fetch(url,{...options,signal:AbortSignal.timeout(20000)})})({method:'POST',url:'/api/control-v1/'+op,headers:{authorization:'Bearer '+h.sessions[role].access_token},body},res);return res;};
 await check('real_Admin_API_briefing_followups_synthesis',async()=>{for(const [op,body] of [['decisions',{}],['rafi-followups',{limit:1}],['rafi-synthesis',{}]])assert.equal((await api('admin',op,body)).statusCode,200,op);});
 await check('real_nonadmin_API_denials',async()=>{for(const [op,body] of endpoints.filter(x=>x[0]!=='rafi/preview'))assert.equal((await api('client',op,body)).statusCode,403,op);});
 await check('Admin_missing_target_and_forged_proof_refusals',async()=>{for(const [,,name,body] of endpoints.slice(2)){const r=await h.rpc('admin',name,body);assert.ok(r.status>=400,name);assert.match(r.data.message,/FOLLOWUP_NOT_FOUND|INVALID_EVIDENCE|PROPOSAL_NOT_FOUND/);}});
 const out={status:'PASS',pass:checks.length,fail:0,checks,at:new Date().toISOString(),project_ref:h.REF,mutations:'none; existing staging identities and synthetic populations',api_harness:'Real Auth and RPC through handler; 20s test transport allowance only, production 5s unchanged'};
 const file=path.join(__dirname,'../../../docs/control-os/bloc7/evidence/staging.json');fs.mkdirSync(path.dirname(file),{recursive:true});fs.writeFileSync(file,JSON.stringify(out,null,2));
})().catch(e=>{console.error(e.message);process.exitCode=1;});
