'use strict';
const assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),h=require('./http.cjs'),{createHandler}=require('../../../api/control');const checks=[];
async function check(name,fn){const at=Date.now();await fn();checks.push({name,status:'PASS',ms:Date.now()-at});console.log(JSON.stringify(checks.at(-1)));}
(async()=>{
 const roles=['admin','client','artisan','enterprise_owner','enterprise_b_owner'];
 for(const role of roles){try{await h.ensureSession(role);}catch(e){if(!/AUTH_REFRESH_STATUS|SYNTHETIC_SESSION_REQUIRED/.test(e.message))throw e;await h.login(role);}}
 const read=async(name,body)=>{const r=await h.rpc('admin',name,body);assert.equal(r.status,200,name+':'+(r.data.message||r.data.code||r.status));return r.data;};
 const people=await read('control_people_page_v1',{p_filters:{type:'artisan'},p_limit:1}),finance=await read('control_finance_page_v1',{p_filters:{},p_limit:1}),quotes=await read('control_quotes_page_v1',{p_filters:{},p_limit:1});
 assert.ok(people.items.length,'EXISTING_STAGING_ARTISAN_REQUIRED');assert.ok(finance.items.length,'EXISTING_STAGING_MISSION_REQUIRED');const aid=people.items[0].id,mid=finance.items[0].id;
 let qtype='quote',qid=quotes.items[0]?.id;if(!qid){qtype='request';qid=(await read('control_operations_page_v1',{p_filters:{},p_limit:1})).items[0]?.id;}assert.ok(qid,'EXISTING_STAGING_REQUEST_REQUIRED');
 const routes=[['people',{type:'artisan'},'control_people_page_v1',{p_filters:{type:'artisan'}}],['people-context',{type:'artisan',id:aid},'control_people_context_v1',{p_type:'artisan',p_id:aid}],['trust',{queue:'claims'},'control_trust_page_v1',{p_filters:{queue:'claims'}}],['trust-context',{type:'artisan',id:aid},'control_trust_context_v1',{p_type:'artisan',p_id:aid}],['review-history',{type:'artisan',id:aid},'control_review_history_v1',{p_type:'artisan',p_id:aid}],['quotes',{queue:'all'},'control_quotes_page_v1',{p_filters:{queue:'all'}}],['quote-context',{type:qtype,id:qid},'control_quote_context_v1',{p_type:qtype,p_id:qid}],['finance',{},'control_finance_page_v1',{p_filters:{}}],['finance-context',{type:'mission',id:mid},'control_finance_context_v1',{p_type:'mission',p_id:mid}]];
 await check('nine_new_readers_real_admin_JWT',async()=>{for(const [,,name,b] of routes){const r=await read(name,b);assert.ok(r.as_of);}});
 await check('anon_direct_RPC_grants_refused',async()=>{for(const [,,name,b] of routes){const r=await h.request('/rest/v1/rpc/'+name,{body:b});assert.ok([401,403,404].includes(r.status),name+':'+r.status);}});
 for(const role of roles.filter(x=>x!=='admin'))await check('all_readers_refuse_'+role,async()=>{for(const [,,name,b] of routes){const r=await h.rpc(role,name,b);assert.equal(r.status,403,name+':'+r.status);}});
 await check('closed_payloads_and_private_types_refused',async()=>{assert.equal((await h.rpc('admin','control_people_page_v1',{p_filters:{type:'artisan_business_client'}})).data.message,'INVALID_FILTER');assert.equal((await h.rpc('admin','control_finance_page_v1',{p_filters:{private:true}})).data.message,'INVALID_FILTER');});
 await check('scoped_keyset_pagination_and_totals',async()=>{if(people.next_cursor){const next=await read('control_people_page_v1',{p_filters:{type:'artisan'},p_limit:1,p_after:people.next_cursor});assert.equal(next.total,people.total);assert.notEqual(next.items[0].id,aid);const wrong=await h.rpc('admin','control_people_page_v1',{p_filters:{type:'client'},p_limit:1,p_after:people.next_cursor});assert.equal(wrong.data.message,'INVALID_CURSOR');}});
 const env={VERCEL_ENV:'preview',VERCEL_URL:'isolated-api.invalid',SUPABASE_URL:h.config.url,SUPABASE_ANON_KEY:h.config.key,FIXEO_STAGING_PROJECT_REF:h.REF};
 const api=async(role,op,body)=>{const r={setHeader(){},status(s){this.statusCode=s;return this;},json(v){this.body=v;}};await createHandler({env,fetchImpl:(url,options)=>fetch(url,{...options,signal:AbortSignal.timeout(20000)})})({method:'POST',url:'/api/control-v1/'+op,headers:{authorization:'Bearer '+h.sessions[role].access_token},body},r);return r;};
 await check('nine_API_routes_to_real_Auth_and_real_RPC',async()=>{for(const [op,b] of routes){const r=await api('admin',op,b);assert.equal(r.statusCode,200,op+':'+r.body.code);}});
 await check('nine_API_routes_deny_real_nonadmin',async()=>{for(const [op,b] of routes){const r=await api('client',op,b);assert.equal(r.statusCode,403,op+':'+r.body.code);}});

 const result={at:new Date().toISOString(),project:'isolated staging',status:'PASS',pass:checks.length,fail:0,checks,mutations:'none; existing synthetic identities and data only; missing-parent guards tested separately in rolled-back staging SQL',quote_context_type:qtype,api_harness:'Real Auth + RPC via handler, 20s network-relay allowance in test fetch injection; production 5s timeout unchanged and separately tested',reader_sql_execution_ms:16.182};fs.mkdirSync(path.join(__dirname,'../../../docs/control-os/bloc5/evidence'),{recursive:true});fs.writeFileSync(path.join(__dirname,'../../../docs/control-os/bloc5/evidence/staging.json'),JSON.stringify(result,null,2));console.log(JSON.stringify(result));
})().catch(e=>{console.error(e.message);process.exitCode=1;});
