'use strict';
const assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),h=require('./http.cjs'),{createHandler}=require('../../../api/control');
const checks=[];async function check(name,fn){const start=Date.now();await fn();checks.push({name,status:'PASS',ms:Date.now()-start});console.log(JSON.stringify(checks.at(-1)));}
(async()=>{
 const roles=['admin','client','artisan','enterprise_owner','enterprise_b_owner'];
 for(const role of roles){try{await h.ensureSession(role);}catch(e){if(!/AUTH_REFRESH_STATUS|SYNTHETIC_SESSION_REQUIRED/.test(e.message))throw e;await h.login(role);}}
 const endpoints=[['marketplace',{filters:{},limit:1},'control_marketplace_cube_v1',{p_source:'operations',p_filters:{},p_limit:1}],['marketplace-population',{kind:'cohort',filters:{},limit:1},'control_marketplace_population_v1',{p_kind:'cohort',p_filters:{},p_limit:1}],['marketplace-coverage',{filters:{},limit:1},'control_marketplace_coverage_v1',{p_filters:{},p_limit:1}],['marketplace-cohorts',{filters:{}},'control_marketplace_cohorts_v1',{p_filters:{}}],['decisions',{classification:'all'},'control_marketplace_signals_v1',{p_source:'network',p_classification:'all'}]];
 const read=async(name,body)=>{const r=await h.rpc('admin',name,body);assert.equal(r.status,200,name+':'+(r.data.message||r.data.code||r.status));assert.ok(r.data.as_of);return r.data;};
 await check('five_read_RPC_real_Admin_JWT',async()=>{for(const [,,name,body] of endpoints)await read(name,body);});
 await check('anon_all_five_RPC_denied',async()=>{for(const [,,name,body] of endpoints){const r=await h.request('/rest/v1/rpc/'+name,{body});assert.ok([401,403,404].includes(r.status),name+':'+r.status);}});
 for(const role of roles.slice(1))await check('all_five_RPC_deny_'+role,async()=>{for(const [,,name,body] of endpoints)assert.equal((await h.rpc(role,name,body)).status,403,name);});
 await check('source_grains_and_population_pagination',async()=>{const cubes=[];for(const source of ['operations','network','commerce'])cubes.push(await read('control_marketplace_cube_v1',{p_source:source,p_filters:{},p_limit:1}));assert.ok(cubes.every(c=>c.scope_hash===cubes[0].scope_hash));assert.ok(cubes.every(c=>JSON.stringify(c.items.map(x=>x.key))===JSON.stringify(cubes[0].items.map(x=>x.key))));const p=await read('control_marketplace_population_v1',{p_kind:'cohort',p_filters:{},p_limit:1});if(p.has_more){const n=await read('control_marketplace_population_v1',{p_kind:'cohort',p_filters:{},p_limit:1,p_after:p.next_cursor});assert.equal(n.total,p.total);assert.notEqual(n.items[0].id,p.items[0].id);assert.equal((await h.rpc('admin','control_marketplace_population_v1',{p_kind:'waiting',p_filters:{},p_limit:1,p_after:p.next_cursor})).data.message,'INVALID_CURSOR');}});
 await check('scope_private_and_tenant_filters_fail_closed',async()=>{assert.equal((await h.rpc('admin','control_marketplace_cube_v1',{p_source:'private',p_filters:{}})).data.message,'INVALID_FILTER');assert.equal((await h.rpc('admin','control_marketplace_cohorts_v1',{p_filters:{private:true}})).data.message,'INVALID_FILTER');assert.equal((await h.rpc('admin','control_marketplace_cohorts_v1',{p_filters:{site_id:'00000000-0000-4000-8000-999999999999'}})).data.message,'INVALID_TENANT_CONTEXT');});
 const env={VERCEL_ENV:'preview',VERCEL_URL:'isolated-api.invalid',SUPABASE_URL:h.config.url,SUPABASE_ANON_KEY:h.config.key,FIXEO_STAGING_PROJECT_REF:h.REF};
 const api=async(role,op,body)=>{const res={setHeader(){},status(n){this.statusCode=n;return this;},json(v){this.body=v;}};await createHandler({env,fetchImpl:(url,options)=>fetch(url,{...options,signal:AbortSignal.timeout(20000)})})({method:'POST',url:'/api/control-v1/'+op,headers:{authorization:'Bearer '+h.sessions[role].access_token},body},res);return res;};
 await check('all_API_routes_real_Auth_and_RPC',async()=>{for(const [op,body] of endpoints){const r=await api('admin',op,body);assert.equal(r.statusCode,200,op+':'+r.body.code);if(op==='marketplace')assert.equal(r.body.status,'FRESH');if(op==='marketplace-cohorts'){assert.ok(r.body.cohorts);assert.notEqual(r.body.comparison.reason,'INCOMPARABLE_OR_UNDATED');}}});
 await check('all_API_routes_deny_real_nonadmin',async()=>{for(const [op,body] of endpoints)assert.equal((await api('client',op,body)).statusCode,403,op);});
 const out={status:'PASS',pass:checks.length,fail:0,checks,at:new Date().toISOString(),project_ref:h.REF,mutations:'none; existing staging identities and synthetic populations',api_harness:'Real Auth and RPC through handler; 20s test transport allowance only, production 5s unchanged'};
 const file=path.join(__dirname,'../../../docs/control-os/bloc6/evidence/staging.json');fs.mkdirSync(path.dirname(file),{recursive:true});fs.writeFileSync(file,JSON.stringify(out,null,2));
})().catch(e=>{console.error(e.message);process.exitCode=1;});
