'use strict';
const {test}=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path');
const {PGlite}=require('@electric-sql/pglite');
const {randomUUID}=require('node:crypto');
const {attest}=require('../../api/mobile-intelligence-fn/transport');
const read=p=>fs.readFileSync(path.join(__dirname,'../..',p),'utf8');
const uid='aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaaa',other='bbbbbbbb-bbbb-4bbb-8bbb-bbbbbbbbbbbb',session='cccccccc-cccc-4ccc-8ccc-cccccccccccc';
const env={FIXEO_W41_ATTESTATION_SECRET:'public-test-fixture-only-'.repeat(4)};
test('JWT SQL: attestation, owner, canonical offer, atomic confirmation, retry/conflict, ACL and Storage RLS',async()=>{
 const db=new PGlite();
 try {
  await db.exec(`CREATE ROLE anon; CREATE ROLE authenticated; CREATE ROLE service_role;
  CREATE SCHEMA auth; CREATE SCHEMA extensions; CREATE SCHEMA storage; CREATE SCHEMA vault;
  CREATE TABLE auth.users(id uuid PRIMARY KEY,deleted_at timestamptz,banned_until timestamptz);
  CREATE TABLE auth.sessions(id uuid PRIMARY KEY,user_id uuid);
  CREATE FUNCTION auth.jwt() RETURNS jsonb LANGUAGE sql STABLE AS $$ SELECT current_setting('request.jwt.claims',true)::jsonb $$;
  CREATE FUNCTION auth.uid() RETURNS uuid LANGUAGE sql STABLE AS $$ SELECT (auth.jwt()->>'sub')::uuid $$;
  CREATE TABLE vault.decrypted_secrets(name text,decrypted_secret text);
  CREATE FUNCTION extensions.digest(data bytea,algorithm text) RETURNS bytea LANGUAGE sql AS $$ SELECT pg_catalog.sha256(data) $$;
  -- Test-only pgcrypto compatibility using core SHA256. Production uses installed pgcrypto.
  CREATE FUNCTION extensions.hmac(data bytea,key bytea,algorithm text) RETURNS bytea LANGUAGE plpgsql AS $$
  DECLARE k bytea:=key; ip bytea:=decode(repeat('00',64),'hex'); op bytea:=ip; i integer;
  BEGIN IF length(k)>64 THEN k:=sha256(k); END IF;
   k:=k||decode(repeat('00',64-length(k)),'hex');
   FOR i IN 0..63 LOOP ip:=set_byte(ip,i,get_byte(k,i)#54);op:=set_byte(op,i,get_byte(k,i)#92);END LOOP;
   RETURN sha256(op||sha256(ip||data)); END $$;
  CREATE TABLE storage.objects(bucket_id text,name text,UNIQUE(bucket_id,name));ALTER TABLE storage.objects ENABLE ROW LEVEL SECURITY;
  CREATE TABLE users(id uuid PRIMARY KEY,role text); CREATE TABLE profiles(id uuid PRIMARY KEY);
  CREATE TABLE service_requests(id uuid PRIMARY KEY DEFAULT gen_random_uuid(),service_category text,city text,description text,client_phone text,urgency text,status text,idempotency_key text,tracking_ref text,guest_token_hash text,client_profile_id uuid);
  CREATE TABLE estimator_context_redemptions(context_id text PRIMARY KEY,outcome_type text,service_code text,session_id text,amount_mad integer,state text,acquired_at timestamptz,service_request_id uuid,committed_at timestamptz,failed_at timestamptz,failure_reason text,booking_ref text,order_id text);
  CREATE TABLE missions(id uuid PRIMARY KEY DEFAULT gen_random_uuid(),request_id text,status text,agreed_price numeric,final_price numeric,commission_amount numeric);
  CREATE FUNCTION set_commission_amount() RETURNS trigger LANGUAGE plpgsql AS $$ BEGIN RETURN NEW; END $$;
  GRANT USAGE ON SCHEMA public,auth,storage TO anon,authenticated,service_role;
  GRANT SELECT,INSERT,UPDATE,DELETE ON storage.objects TO authenticated;
  INSERT INTO auth.users(id) VALUES('${uid}'),('${other}');INSERT INTO auth.sessions VALUES('${session}','${uid}');
  INSERT INTO users VALUES('${uid}','client'),('${other}','client');INSERT INTO profiles SELECT id FROM users;`);
  await db.query('INSERT INTO vault.decrypted_secrets VALUES($1,$2)',['fixeo_w41_attestation_v1',env.FIXEO_W41_ATTESTATION_SECRET]);
  for(const name of ['20260921005143_vap_bp33_offers_foundation.sql','20260921012731_vap_booking_settlement_binding.sql','20260921090058_garden_vap_confirmation.sql','20260921174531_diagnostic_foundation_v1.sql','20261004181121_mobile_intelligence_jwt_attestation_v1.sql','20261004183523_mobile_intelligence_replay_city_guard.sql','20261004184025_mobile_intelligence_diagnostic_payload_guard.sql'])await db.exec('BEGIN;'+read('supabase/migrations/'+name)+'COMMIT;');
  await db.exec('GRANT USAGE ON SCHEMA fixeo_private TO authenticated;UPDATE fixeo_private.mobile_intelligence_config_v1 SET enabled=true');
  const claims=async(u=uid)=>db.query("SELECT set_config('request.jwt.claims',$1,false)",[JSON.stringify({sub:u,session_id:session,role:'authenticated'})]);
  await claims();
  const call=(rpc,op,p,id=randomUUID(),user=uid)=>{const a=attest(op,p,user,env,id);return db.query('SELECT public.'+rpc+'($1,$2) result',[a.p_envelope,a.p_mac]);};
  for(const role of ['anon','service_role']) {await db.exec('SET ROLE '+role);await assert.rejects(call('mobile_estimator_offer_v1','offer',{}));await db.exec('RESET ROLE')}
  await db.exec('SET ROLE authenticated');
  const diagnosticSession=randomUUID();
  const diagnosticCreate={action:'create',session_id:diagnosticSession,payload:{revision:1,city_slug:'rabat',consent_version:'diagnostic-privacy-v1',input:{description:'fixture',answers:{},safety_signals:[]}}};
  const diagnostic=await call('mobile_diagnostic_state_v1','diagnostic',diagnosticCreate);
  assert.equal(diagnostic.rows[0].result.session.owner_user_id,uid);
  await assert.rejects(call('mobile_diagnostic_state_v1','diagnostic',{...diagnosticCreate,session_id:randomUUID(),payload:{...diagnosticCreate.payload,input:{...diagnosticCreate.payload.input,answers:{price:1}}}}),/PAYLOAD_INVALID/);
  await assert.rejects(db.query('SELECT * FROM fixeo_private.mobile_intelligence_receipts_v1'));
  await assert.rejects(db.query('SELECT * FROM vault.decrypted_secrets'));
  const row={id:randomUUID(),offer_key:randomUUID(),pricing_version:'vap-bp33-v1',currency:'MAD',service_code:'jardinage.tonte_pelouse',catalogue_version:'fixture',city:'rabat',scope:{context_id:'fxctx-'+'a'.repeat(32),session_id:'w41-session',outcome_type:'PRICE_READY'},vap_minor:30000,materials_minor:0,commission_minor:6000,client_total_minor:36000,expires_at:new Date(Date.now()+600000).toISOString()};
  const a=attest('offer',row,uid,env,row.id);
  await assert.rejects(db.query('SELECT public.mobile_estimator_offer_v1($1,$2)',[a.p_envelope+' ',a.p_mac]),/ATTESTATION_INVALID/);
  const expired=attest('offer',row,uid,env,row.id,Date.now()-61000);
  await assert.rejects(db.query('SELECT public.mobile_estimator_offer_v1($1,$2)',[expired.p_envelope,expired.p_mac]),/EXPIRED/);
  await assert.rejects(call('mobile_estimator_offer_v1','offer',row,row.id,other),/SCOPE/);
  assert.equal((await call('mobile_estimator_offer_v1','offer',row,row.id)).rows[0].result.ok,true);
  assert.equal((await call('mobile_estimator_offer_v1','offer',row,row.id)).rows[0].result.replayed,true);
  await assert.rejects(call('mobile_estimator_offer_v1','offer',{...row,city:'fes'},row.id),/IDEMPOTENCY_CONFLICT/);
  const c={p_context_id:row.scope.context_id,p_outcome_type:'PRICE_READY',p_service_code:row.service_code,p_session_id:row.scope.session_id,p_amount_mad:360,p_city_slug:'rabat',p_client_phone:'0612345678',p_description:'W41 isolated fixture',p_tracking_ref:'FX-W41TEST',p_guest_token_hash:'a'.repeat(64),p_offer_id:row.id};
  await assert.rejects(call('confirm_mobile_estimator_request_v2','confirm',{kind:'pricing',confirmation:{...c,p_amount_mad:1}}),/REJECTED/);
  const id=randomUUID(),result=(await call('confirm_mobile_estimator_request_v2','confirm',{kind:'pricing',confirmation:c},id)).rows[0].result;
  assert.equal(result.ok,true);
  assert.equal((await call('confirm_mobile_estimator_request_v2','confirm',{kind:'pricing',confirmation:c},id)).rows[0].result.request_id,result.request_id);
  await assert.rejects(call('confirm_mobile_estimator_request_v2','confirm',{kind:'pricing',confirmation:{...c,p_description:'changed'}},id),/IDEMPOTENCY_CONFLICT/);
  await db.exec('RESET ROLE');
  assert.equal((await db.query('SELECT count(*)::int n FROM service_requests')).rows[0].n,1);
  assert.equal((await db.query('SELECT client_profile_id FROM service_requests')).rows[0].client_profile_id,uid);
  const did=randomUUID(),mid=randomUUID();
  await db.query(`INSERT INTO fixeo_private.diagnostic_sessions_v1(id,owner_user_id,owner_key,source,city_slug,input,consent_version) VALUES($1,$2,$3,'client','rabat','{}','diagnostic-privacy-v1')`,[did,uid,'u:'+uid]);
  await db.query(`INSERT INTO fixeo_private.diagnostic_media_v1(id,session_id,kind,state,raw_path,clean_path,declared_mime,declared_bytes,validation_lease,lease_until) VALUES($1,$2,'photo','validating',$3,$4,'image/webp',100,gen_random_uuid(),now()+interval '1 minute')`,[mid,did,'raw/'+did+'/'+mid,'safe/'+did+'/'+mid+'.webp']);
  await db.query(`INSERT INTO fixeo_private.mobile_intelligence_receipts_v1 VALUES($1,'diagnostic',gen_random_uuid(),'fixture',$2,now())`,[uid,{session:{id:did}}]);
  await db.exec('SET ROLE authenticated');
  await assert.rejects(db.query("INSERT INTO storage.objects VALUES('diagnostic-private-v1','safe/arbitrary.webp')"));
  await db.query("INSERT INTO storage.objects VALUES('diagnostic-private-v1',$1)",['safe/'+did+'/'+mid+'.webp']);
  assert.equal((await db.query("UPDATE storage.objects SET name='replacement' RETURNING name")).rows.length,0);
  assert.equal((await db.query('DELETE FROM storage.objects RETURNING name')).rows.length,0);
  await db.exec('RESET ROLE');await db.query('DELETE FROM auth.sessions');await db.exec('SET ROLE authenticated');
  await assert.rejects(call('mobile_estimator_offer_v1','offer',row),/SESSION_REVOKED/);
 }finally{await db.close()}
});
