'use strict';
const {test}=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs');
const {PGlite}=require('@electric-sql/pglite');
const {persistPhoto}=require('../../api/mobile-intelligence-fn/diagnostic');
const {hash}=require('../../api/diagnostic/auth');
const {unwrap}=require('../../api/mobile-intelligence-fn/security');
const {beforeAction}=require('../../api/diagnostic/estimator-bridge');
const {unsealToken,sealToken}=require('../../api/estimator-v1/fixeo-estimator-token-v1');
const uid='aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaaa';
const env={NODE_ENV:'test',SUPABASE_URL:'https://kqyhusnbybsukbcaoqtu.supabase.co',FIXEO_STAGING_PROJECT_REF:'kqyhusnbybsukbcaoqtu',SUPABASE_ANON_KEY:'sb_publishable_fixture',FIXEO_W41_ATTESTATION_SECRET:'a'.repeat(64),VERCEL_URL:'w41-test.vercel.app',FIXEO_ESTIMATOR_SECRET:'fixture-secret-'.repeat(6),FIXEO_DIAGNOSTIC_SECRET:'fixture-diagnostic-'.repeat(6),FIXEO_DIAGNOSTIC_ORIGIN:'https://w41-test.vercel.app',FIXEO_DIAGNOSTIC_MODEL:'fixture'};
test('real persisted diagnostic lifecycle → canonical bridge; provenance, Safety exception, owner, revision and expiry',async()=>{
 const db=new PGlite();
 try {
  await db.exec(`CREATE ROLE anon; CREATE ROLE authenticated; CREATE ROLE service_role;
    CREATE SCHEMA auth; CREATE TABLE auth.users(id uuid PRIMARY KEY); CREATE TABLE public.service_requests(id uuid PRIMARY KEY);
    INSERT INTO auth.users VALUES('${uid}');`);
  await db.exec(fs.readFileSync('supabase/migrations/20260921174531_diagnostic_foundation_v1.sql','utf8'));
  const transport={user:async()=>uid,rpc:async(name,args)=>(await db.query('SELECT public.'+name+'('+Object.keys(args).map((k,i)=>k+'=> $'+(i+1)).join(',')+') value',Object.values(args))).rows[0].value};
  const mediaRows=new Map(); const media={store:async(path,bytes)=>mediaRows.set(path,bytes),download:async path=>mediaRows.get(path)};
  const bytes=Buffer.from('fixture-sanitized-image');
  const photo={bytes,mime:'image/webp',width:100,height:100,sha256:hash(bytes)};
  let calls=0;
  const provider={analyze:async({media:photos})=>{calls++;return {result:{trade:'plomberie',problem:'Selon votre description, fuite du robinet possible.',observations:[],hypotheses:['Joint à vérifier'],urgency:'moderate',urgency_reason:'Écoulement déclaré.',checks:['À vérifier sur place.'],possible_parts:[],question_ids:['water_spreading'],safety_signals:[]},photoEvidence:photos.map(m=>({media_id:m.id,status:'inconclusive',observations:[],safety_signals:[]})),usage:{}};}};
  const fetchImpl=async url=>({ok:true,json:async()=>url.includes('/auth/')?{id:uid}:[{id:uid,role:'client'}]});
  const req={headers:{authorization:'Bearer '+ 'a'.repeat(40)},body:{consent_version:'diagnostic-privacy-v1'}};
  const deps={env,transport,media,provider,fetchImpl};
  await assert.rejects(persistPhoto({...req,body:{}},photo,'Fuite du robinet','rabat',deps),/CONSENT/);
  const result=await persistPhoto(req,photo,'Fuite du robinet','rabat',deps);
  assert.equal(result.privacy.persisted,true);assert.equal(result.privacy.raw_photo_retained,false);
  assert.ok(result.diagnostic_reference);assert.equal(result.result.safety.stop,false);assert.equal(result.result.questions.length,0);
  assert.ok(result.result.facts.some(f=>f.provenance==='user_declared'));assert.equal(result.result.hypotheses[0].provenance,'ai_inferred');
  assert.equal(result.result.facts.some(f=>f.provenance==='user_confirmed'),false);
  const token=unwrap(result.diagnostic_reference,'diagnostic',uid,env),ref=unsealToken(token,env.FIXEO_ESTIMATOR_SECRET);
  const data=await transport.rpc('diagnostic_state_v1',{p_action:'get',p_actor:'u:'+uid,p_session_id:ref.session_id,p_payload:{}});
  assert.equal(data.run.usage.deferred_qualification[0].id,'water_spreading');
  const body={action:'start',entry_context:{diagnostic_token:token,known_inputs:{price:1}}};
  const trusted={headers:{authorization:req.headers.authorization,origin:env.FIXEO_DIAGNOSTIC_ORIGIN,'x-fixeo-diagnostic':'1'}};
  await beforeAction(trusted,{setHeader(){}},body,env.FIXEO_ESTIMATOR_SECRET,{env,transport});
  assert.deepEqual(body.entry_context.known_inputs,{});assert.equal(body.entry_context.city_slug,'rabat');
  await assert.rejects(beforeAction(trusted,{setHeader(){}},{action:'start',entry_context:{diagnostic_token:token}},env.FIXEO_ESTIMATOR_SECRET,{env,transport:{...transport,user:async()=> 'bbbbbbbb-bbbb-4bbb-8bbb-bbbbbbbbbbbb'}}),/DIAGNOSTIC_NOT_FOUND/);
  const expired=sealToken({...ref,expires_at:Date.now()-1},env.FIXEO_ESTIMATOR_SECRET);
  await assert.rejects(beforeAction(trusted,{setHeader(){}},{action:'start',entry_context:{diagnostic_token:expired}},env.FIXEO_ESTIMATOR_SECRET,{env,transport}),/EXPIRED/);
  await assert.rejects(beforeAction(trusted,{setHeader(){}},{action:'start',entry_context:{diagnostic_token:token.slice(0,-12)+'aaaaaaaaaaaa'}},env.FIXEO_ESTIMATOR_SECRET,{env,transport}));
  const stopped=await persistPhoto(req,photo,'Une odeur de gaz très forte dans la cuisine','rabat',deps);
  assert.equal(stopped.result.safety.stop,true);assert.equal(stopped.diagnostic_reference,null);assert.equal(calls,1);
  await transport.rpc('diagnostic_state_v1',{p_action:'update',p_actor:'u:'+uid,p_session_id:ref.session_id,p_payload:{revision:ref.revision,city_slug:'rabat',input:{description:'Nouveau problème',answers:{},safety_signals:[]}}});
  await assert.rejects(beforeAction(trusted,{setHeader(){}},{action:'start',entry_context:{diagnostic_token:token}},env.FIXEO_ESTIMATOR_SECRET,{env,transport}),/REVISION_CONFLICT/);
 }finally{await db.close();}
});
