'use strict';
const {test}=require('node:test');const assert=require('node:assert/strict');const fs=require('node:fs');const path=require('node:path');const {JSDOM}=require('jsdom');
const root=path.resolve(__dirname,'../..');
function setup(){const dom=new JSDOM('<body><button id="entry">Univers</button><textarea id="fxhf-need-input"></textarea><select id="fxhf-location"><option value="Fès">Fès</option></select></body>',{url:'https://www.fixeo.ma',runScripts:'outside-only'});const w=dom.window;w.HTMLDialogElement.prototype.showModal=function(){this.open=true;};w.HTMLDialogElement.prototype.close=function(){this.open=false;w.setTimeout(()=>this.dispatchEvent(new w.Event('close')),0);};w.eval(fs.readFileSync(path.join(root,'js/fixeo-cities.js'),'utf8'));w.eval(fs.readFileSync(path.join(root,'js/fixeo-discovery-v1.js'),'utf8'));return {dom,w,d:w.document};}
function click(d,text){const b=[...d.querySelectorAll('dialog button')].find(b=>b.textContent===text);assert.ok(b,text);b.click();}
const tick=()=>new Promise(r=>setTimeout(r,10));
test('eight universes offer specific needs; no price or request call before explicit continue',()=>{const {dom,w,d}=setup();try{let calls=0;w.FixeoEstimatorV2={open(){calls++;}};let count=0;for(const key of ['eau','electricite','confort','portes','travaux','installation','entretien','demenagement']){w.FixeoDiscovery.open(key,d.getElementById('entry'));count+=d.querySelectorAll('.fxd-choices button').length-1;assert.ok(d.querySelectorAll('.fxd-choices button').length>=7);click(d,'✕');}assert.ok(count>=60);assert.equal(calls,0);}finally{dom.window.close();}});
test('selected situation and city reach estimator; delayed close cannot unlock estimator',async()=>{const {dom,w,d}=setup();try{let context;w.FixeoEstimatorV2={open(c){context=c;d.body.style.overflow='hidden';return Promise.resolve({accepted:true});}};w.FixeoDiscovery.open('eau',d.getElementById('entry'));click(d,'Fuite sous un évier');click(d,'Continuer avec RAFI →');await tick();assert.equal(context.city,'Fès');assert.equal(context.metier_hint,'plomberie');assert.equal(context.description,'Fuite sous un évier');assert.equal(d.querySelector('dialog').open,false);assert.equal(d.body.style.overflow,'hidden');}finally{dom.window.close();}});
test('back preserves edited text and city; ambiguous situation sends no invented métier',async()=>{const {dom,w,d}=setup();try{let context;w.FixeoEstimatorV2={open(c){context=c;return Promise.resolve({accepted:true});}};w.FixeoDiscovery.open('travaux',d.getElementById('entry'));click(d,'Rénover une cuisine');const input=d.getElementById('fxd-description');input.value='Rénover ma cuisine de 12 m²';input.dispatchEvent(new w.Event('input'));const sel=d.getElementById('fxd-city');sel.value='Rabat';sel.dispatchEvent(new w.Event('change'));click(d,'← Retour aux situations');click(d,'Rénover une cuisine');assert.equal(d.getElementById('fxd-description').value,input.value);assert.equal(d.getElementById('fxd-city').value,'Rabat');click(d,'Continuer avec RAFI →');await tick();assert.equal(context.metier_hint,undefined);assert.equal(context.city,'Rabat');}finally{dom.window.close();}});
test('failed estimator opening retains the form and permits retry',async()=>{const {dom,w,d}=setup();try{w.FixeoEstimatorV2={open:()=>Promise.resolve({accepted:false})};w.FixeoDiscovery.open('eau',d.getElementById('entry'));click(d,'WC bouché');click(d,'Continuer avec RAFI →');await tick();assert.equal(d.querySelector('dialog').open,true);assert.equal(d.getElementById('fxd-description').value,'WC bouché');assert.ok(d.querySelector('.fxd-error').textContent);assert.equal(d.querySelector('.fxd-primary').disabled,false);}finally{dom.window.close();}});
test('free entry requires a description and close restores focus',()=>{const {dom,w,d}=setup();try{const entry=d.getElementById('entry');entry.focus();w.FixeoDiscovery.open('autre',entry);click(d,'Continuer avec RAFI →');assert.ok(d.querySelector('.fxd-error').textContent);click(d,'✕');assert.equal(d.activeElement,entry);assert.equal(d.body.style.overflow,'');}finally{dom.window.close();}});
