const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path');const api=require('../../api/enterprise-rafi.js');const root=path.join(__dirname,'../..');
test('J7 capacity is canonical and conservative',()=>{assert.deepEqual(api.workforceCapacity({control_tower:{worker_load:[]}}),{configured:0,available:0,available_worker_ids:[]});const c=api.workforceCapacity({control_tower:{worker_load:[{worker_id:'w1',status:'active',availability:'available',active_assignments:0,max_concurrent_jobs:1},{worker_id:'w2',status:'active',availability:'available',active_assignments:1,max_concurrent_jobs:1},{worker_id:'w3',status:'inactive',availability:'available',active_assignments:0,max_concurrent_jobs:2}]}});assert.equal(c.configured,3);assert.equal(c.available,1);assert.deepEqual(c.available_worker_ids,['w1']);});
test('J7 forbids internal assignment recommendation when capacity is zero',()=>{const context={control_tower:{worker_load:[]},operational_changes:[{change:'worsened',followup_kind:'workforce',target_type:'service_request',target_id:'r1',severity:4}],followups:[]};const a=api.nextBestActions(context);assert.equal(a[0].action_type,'propose_hybrid_dispatch');assert.match(a[0].reason,/aucune_capacite_interne_disponible/);assert.equal(a.some(x=>x.action_type==='propose_internal_assignment'),false);});
test('J7 permits internal assignment only with canonical eligible capacity',()=>{const context={control_tower:{worker_load:[{worker_id:'w1',status:'active',availability:'available',active_assignments:0,max_concurrent_jobs:1}]},operational_changes:[{change:'worsened',followup_kind:'workforce',target_type:'service_request',target_id:'r1',severity:4}],followups:[]};assert.equal(api.nextBestActions(context)[0].action_type,'propose_internal_assignment');});
test('J7 prompt hard guard prevents theoretical internal assignment',()=>{const s=fs.readFileSync(path.join(root,'api/enterprise-rafi.js'),'utf8');assert.match(s,/If no eligible internal worker exists, do NOT recommend or propose internal assignment/);assert.match(s,/N\\'émets aucune recommandation ou proposition d\\'assignation interne si available=0/);});
test('J7 introduces no new persistence scheduler or service role',()=>{const s=fs.readFileSync(path.join(root,'api/enterprise-rafi.js'),'utf8');assert.doesNotMatch(s,/CRON_SECRET|SUPABASE_SERVICE_ROLE_KEY|setInterval\s*\(/);});
test('J8.15 rejects model internal assignment when canonical capacity is zero',()=>{const context={control_tower:{worker_load:[]},operational_changes:[{change:'worsened',followup_kind:'workforce',target_type:'service_request',target_id:'11111111-1111-4111-8111-111111111111',severity:4}],followups:[]};const actions=[{type:'propose_internal_assignment',target:{request_id:'11111111-1111-4111-8111-111111111111'}},{type:'propose_hybrid_dispatch',target:{request_id:'11111111-1111-4111-8111-111111111111'}}];assert.deepEqual(api.enforceDecisionIntegrity(context,actions).map(x=>x.type),['propose_hybrid_dispatch']);});
test('J8.15 rejects model proposals not present in deterministic next best actions',()=>{const context={control_tower:{worker_load:[]},operational_changes:[{change:'worsened',followup_kind:'workforce',target_type:'service_request',target_id:'11111111-1111-4111-8111-111111111111',severity:4}],followups:[]};const actions=[{type:'decide_approval',target:{case_id:'22222222-2222-4222-8222-222222222222'}},{type:'propose_hybrid_dispatch',target:{request_id:'33333333-3333-4333-8333-333333333333'}}];assert.deepEqual(api.enforceDecisionIntegrity(context,actions),[]);});
test('J8.15 permits exact deterministic internal assignment only with eligible capacity',()=>{const rid='11111111-1111-4111-8111-111111111111',context={control_tower:{worker_load:[{worker_id:'w1',status:'active',availability:'available',active_assignments:0,max_concurrent_jobs:1}]},operational_changes:[{change:'worsened',followup_kind:'workforce',target_type:'service_request',target_id:rid,severity:4}],followups:[]};const actions=[{type:'propose_internal_assignment',target:{request_id:rid}}];assert.equal(api.enforceDecisionIntegrity(context,actions).length,1);});
