const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path');const r=path.join(__dirname,'../..'),rd=p=>fs.readFileSync(path.join(r,p),'utf8');

test('J8.21 V1 shell exposes all certified Enterprise modules',()=>{const h=rd('dashboard-enterprise.html');for(const id of ['enterprise-workspace','enterprise-control-tower','enterprise-sites','enterprise-workforce-module','enterprise-preventive-maintenance','enterprise-governance-module','enterprise-finance-module','enterprise-reporting','enterprise-team','enterprise-rafi-module'])assert.match(h,new RegExp('id="'+id+'"'));});
test('J8.21 premium navigation preserves RAFI first and single logout',()=>{const h=rd('dashboard-enterprise.html');assert.ok(h.indexOf('class="fxew-nav-rafi"')<h.indexOf('<nav>'));assert.equal((h.match(/id="enterprise-logout"/g)||[]).length,1);});
test('J8.21 RAFI human confirmation precedes every canonical action execution',()=>{const u=rd('js/fixeo-enterprise-rafi-ui.js');assert.ok(u.indexOf('win.confirm')>-1&&u.indexOf('win.confirm')<u.indexOf('actionApi().execute'));});
test('J8.21 RAFI integrity truth cross-domain and closed-loop guards remain present',()=>{const a=rd('api/enterprise-rafi.js'),u=rd('js/fixeo-enterprise-rafi-ui.js');for(const x of ['enforceDecisionIntegrity','operationalTruth','crossDomainSignals'])assert.match(a,new RegExp(x));assert.match(u,/hooks\.refreshOperations\(\);await loadBriefing\(\)/);});
test('J8.21 desktop camera and file picker remain distinct',()=>{const u=rd('js/fixeo-enterprise-rafi-ui.js');assert.match(u,/show\.addEventListener\('click',\(\)=>files\.click\(\)\)/);assert.match(u,/cameraBtn\.addEventListener\('click',openCamera\)/);});
test('J8.21 executive brief is full width and structured',()=>{const c=rd('css/fixeo-enterprise-workspace.css'),u=rd('js/fixeo-enterprise-rafi-ui.js');assert.match(c,/fxew-rafi-exec-summary p\{[^}]*width:100%;max-width:none/);for(const x of ['ÉTAT','RISQUE','PROCHAINE DÉCISION'])assert.match(u,new RegExp(x));});
test('J8.21 Finance intervention amount is no-wrap',()=>{const c=rd('css/fixeo-enterprise-workspace.css');assert.match(c,/fxew-finance-row>\.fxew-status\{[^}]*white-space:nowrap/);});
test('J8.21 workspace literal backslash-n regression remains absent',()=>{assert.doesNotMatch(rd('js/fixeo-enterprise-workspace.js'),/\\n/);});
test('J8.21 CMI/card payment is not represented as active',()=>{assert.doesNotMatch(rd('dashboard-enterprise.html'),/paiement par carte disponible|CMI actif|payer par carte/i);});
