'use strict';
const {test,before,after}=require('node:test'),assert=require('node:assert/strict'),F=require('./bloc7-fixture.cjs'),{createHandler}=require('../../api/control'),u=F.uuid;let db;const calls=[];
before(async()=>{db=await F.setup();await F.seed(db);await db.exec(`INSERT INTO public.claim_requests(id,artisan_id,requester_user_id,requester_name) VALUES('${u(80)}','${u(21)}','${u(6)}','Synthetic claimant')`);await F.actor(db,3);});after(async()=>db?.close());
const reply=(data,status=200)=>({ok:status<400,status,text:async()=>JSON.stringify(data)}),env={SUPABASE_URL:'https://abcdefghijklmnopqrst.supabase.co',SUPABASE_ANON_KEY:'sb_publishable_SYNTHETIC',FIXEO_STAGING_PROJECT_REF:'abcdefghijklmnopqrst'};
const handler=createHandler({env,fetchImpl:async(url,opts)=>{assert.equal(opts.headers.Authorization,'Bearer synthetic.not_a_real_token');if(url.endsWith('/user'))return reply({id:u(3)});const name=url.split('/').at(-1),args=JSON.parse(opts.body);calls.push(name);assert.match(name,/^control_[a-z_0-9]+$/);try{return reply((await db.query(`select public.${name}(${Object.keys(args).map((k,i)=>k+'=>$'+(i+1)).join(',')}) j`,Object.values(args))).rows[0].j);}catch(e){return reply({code:e.code,message:e.message},e.code==='42501'?403:422);}}});
async function invoke(op,body={},headers={authorization:'Bearer synthetic.not_a_real_token'}){const r={headers:{},setHeader(k,v){this.headers[k]=v;},status(n){this.statusCode=n;return this;},json(x){this.body=x;return this;}};await handler({method:'POST',url:'/api/control-v1/'+op,headers,body},r);return r;}
test('7.3 API re-reads evidence, rejects forged or expired intent and delegates exact canonical proposal',async()=>{const d=(await invoke('decisions')).body.decisions.find(x=>x.target_id===u(80));const body={decision_id:d.decision_id,evidence_fingerprint:d.evidence_fingerprint,valid_until:d.expires_at,capability:'claim.reject',target_id:u(80),payload:{reason:'Synthetic API review'}};
 assert.equal((await invoke('rafi/preview',{...body,evidence_fingerprint:'0'.repeat(64)})).body.code,'EVIDENCE_CHANGED');assert.equal((await invoke('rafi/preview',{...body,valid_until:'2020-01-01'})).body.code,'STALE_EVIDENCE');assert.equal((await invoke('rafi/preview',{...body,capability:'artisan.verify'})).body.code,'PROPOSAL_NOT_ADMISSIBLE');const p=await invoke('rafi/preview',body);assert.equal(p.statusCode,200);assert.equal(p.body.kind,'ActionProposal');assert.equal(p.headers['Cache-Control'],'private, no-store');assert.equal((await invoke('rafi/execute',{preview_id:p.body.preview_id,confirmed:false,idempotency_key:u(910)})).statusCode,428);assert.equal(calls.filter(x=>x==='control_rafi_proposal_v3').length,1);
});
test('7.4 API owner injection, unsupported actions and absent authentication are refused before mutation',async()=>{const n=calls.length;assert.equal((await invoke('rafi-followup',{operation:'create',owner_id:u(7)})).body.code,'INVALID_PAYLOAD');assert.equal((await invoke('rafi-followup',{operation:'repair'})).body.code,'INVALID_FOLLOWUP_COMMAND');assert.equal((await invoke('rafi-followup',{operation:'create',rule:'fabricated'})).body.code,'INVALID_RULE');assert.equal((await invoke('rafi-followups',{},{})).statusCode,401);assert.equal(calls.length,n);});
test('7.4 API follows, paginates, reads evidence and preserves idempotent operator command',async()=>{const d=(await invoke('decisions')).body.decisions.find(x=>x.target_id===u(80));const body={operation:'create',proof:d.canonical_proof,rule:d.decision_type,due_at:new Date(Date.now()+3600000).toISOString(),idempotency_key:u(920)};const a=await invoke('rafi-followup',body),b=await invoke('rafi-followup',body);assert.equal(a.statusCode,200);assert.deepEqual(a.body.followup,b.body.followup);const list=await invoke('rafi-followups',{limit:1});assert.equal(list.body.items.length,1);assert.equal(list.body.source_reads,1);assert.equal((await invoke('rafi-followup-evidence',{id:a.body.followup.id})).body.candidates.length,0);});
