'use strict';
const {test}=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),F=require('./bloc6-fixture.cjs'),B7=require('./bloc7-fixture.cjs');
test('7.3/7.4 Metadata/rollback preserves P0, business authorities, policies and all operator history',async()=>{const db=await F.setup();try{await F.seed(db);const meta=async()=>(await db.query(`SELECT jsonb_build_object('functions',(SELECT jsonb_agg(jsonb_build_array(n.nspname,proname,pg_get_function_identity_arguments(p.oid),md5(pg_get_functiondef(p.oid)),proacl,proconfig,proowner) ORDER BY p.oid) FROM pg_proc p JOIN pg_namespace n ON n.oid=p.pronamespace WHERE n.nspname IN('public','fixeo_private') AND proname NOT IN('control_action_execute_v1') AND proname NOT LIKE '%rafi%v3'), 'policies',(SELECT jsonb_agg(to_jsonb(p) ORDER BY schemaname,tablename,policyname) FROM pg_policies p),'relations',(SELECT jsonb_agg(jsonb_build_array(c.oid,relacl,relrowsecurity) ORDER BY c.oid) FROM pg_class c JOIN pg_namespace n ON n.oid=c.relnamespace WHERE n.nspname IN('public','fixeo_private') AND relkind IN('r','v') AND relname NOT LIKE 'rafi_%_v3')) j`)).rows[0].j;
 const definition=async()=>(await db.query("SELECT pg_get_functiondef('public.control_action_execute_v1(uuid,boolean,uuid)'::regprocedure) d")).rows[0].d;
 const before=await meta(),old=await definition();await db.exec(B7.sql);assert.deepEqual(await meta(),before);assert.equal((await definition()).replace(' PERFORM fixeo_private.rafi_guard_bound_preview_v3(a.id);\n',''),old);
 const grants=(await db.query(`SELECT n.nspname,p.proname,p.proconfig,pg_get_userbyid(p.proowner) owner,has_function_privilege('anon',p.oid,'EXECUTE') anon,has_function_privilege('authenticated',p.oid,'EXECUTE') authenticated,has_function_privilege('service_role',p.oid,'EXECUTE') service FROM pg_proc p JOIN pg_namespace n ON n.oid=p.pronamespace WHERE p.proname LIKE '%rafi%v3'`)).rows;
 assert.equal(grants.length,8);for(const g of grants){assert.equal(g.owner,'postgres');assert.deepEqual(g.proconfig,['search_path=""']);assert.equal(g.anon,false);assert.equal(g.service,false);assert.equal(g.authenticated,g.nspname==='public');}
 await db.exec(`INSERT INTO public.claim_requests(id,artisan_id,requester_user_id,requester_name) VALUES('${F.uuid(80)}','${F.uuid(21)}','${F.uuid(6)}','Synthetic claimant')`);await F.actor(db,3);
 const rpc=async(n,args)=>(await db.query(`SELECT public.${n}(${args.map((_,i)=>'$'+(i+1)).join(',')}) j`,args)).rows[0].j;
 const p=(await rpc('control_rafi_source_v3',['trust','all'])).observations.find(o=>o.kind==='claim.pending').proof;
 const f=await rpc('control_rafi_followup_v3',['create',null,null,p,'claim.pending',new Date(Date.now()+3600000).toISOString(),null,F.uuid(900)]);
 const preview=await rpc('control_rafi_proposal_v3',[p,'claim.pending','claim.reject',F.uuid(80),{reason:'Synthetic rollback check'},F.uuid(901)]);
 await db.exec('RESET ROLE');const history=async()=>(await db.query('SELECT jsonb_agg(to_jsonb(t) ORDER BY id) j FROM fixeo_private.authority_audit_events_v1 t')).rows[0].j;const audit=await history();
 await db.exec(fs.readFileSync(path.join(__dirname,'../../docs/control-os/bloc7/rollback.sql'),'utf8'));assert.deepEqual(await meta(),before);assert.equal(await definition(),old);assert.deepEqual(await history(),audit);assert.equal((await db.query('SELECT status FROM fixeo_private.rafi_followups_v3 WHERE id=$1',[f.followup.id])).rows[0].status,'open');assert.equal((await db.query('SELECT expires_at<=now() expired FROM fixeo_private.control_action_previews_v1 WHERE id=$1',[preview.preview_id])).rows[0].expired,true);
 assert.equal((await db.query('SELECT status FROM public.claim_requests WHERE id=$1',[F.uuid(80)])).rows[0].status,'pending');
 await db.exec(B7.sql);assert.deepEqual(await meta(),before);assert.deepEqual(await history(),audit);
 }finally{await db.close();}});
