'use strict';
const {test,before,after}=require('node:test'),assert=require('node:assert/strict'),F=require('./bloc6-fixture.cjs'),C=require('../../api/control/marketplace-cohorts');
const u=F.uuid,window={from:'2026-09-01',to:'2026-09-15'};let db;
const read=async f=>(await db.query('select public.control_marketplace_cohorts_v1($1) result',[{...window,...f}])).rows[0].result;
const current=x=>x.cohorts.find(c=>c.label==='current');
before(async()=>{db=await F.setup();await F.seed(db);});after(async()=>db?.close());
function tx(name,fn){test(name,async()=>{await db.exec('RESET ROLE;BEGIN');try{await fn();}finally{await db.exec('ROLLBACK;RESET ROLE');}});}
async function seed(){await db.exec(`INSERT INTO public.service_requests(id,city,service_category,description,status,created_at) VALUES
 ('${u(100)}','Fès','plomberie','Synthetic accepted cohort','assigned','2026-09-02T10:00Z'),
 ('${u(101)}','Fès','plomberie','Synthetic offered cohort','new','2026-09-03T10:00Z'),
 ('${u(102)}','Fès','plomberie','Synthetic unknown event','completed','2026-09-04T10:00Z'),
 ('${u(103)}','Fès','plomberie','Synthetic prior cohort','cancelled','2026-08-20T10:00Z'),
 ('${u(104)}','Fès','plomberie','Synthetic late acceptance','assigned','2026-09-05T10:00Z');
 INSERT INTO public.missions(id,request_id,artisan_profile_id,status,accepted_at) VALUES
 ('${u(200)}','${u(100)}','${u(20)}','pending','2026-09-02T11:00Z'),
 ('${u(201)}','${u(101)}','${u(20)}','offered',NULL),
 ('${u(202)}','${u(102)}','${u(20)}','done',NULL),
 ('${u(204)}','${u(104)}','${u(20)}','pending','2026-09-06T11:00Z');`);}
tx('6.3 Empty denominator and absent reviews/delay are unknown rather than rates of zero',async()=>{await F.actor(db,3);const raw=await read(),x=C.build(raw);assert.equal(current(x).requests.total,0);assert.equal(current(x).conversion.value,null);assert.equal(current(x).quality.rating_mean,null);assert.equal(current(x).dispatch.execution_delay,null);assert.equal(x.comparison.reason,'EMPTY_DENOMINATOR');assert.equal(x.comparison.volume_relative_change,null);});
tx('6.3 Fixed acceptance horizon, explicit unknown evidence and coherent denominator',async()=>{await seed();await F.actor(db,3);const x=C.build(await read());const c=current(x);assert.equal(c.requests.total,4);assert.equal(c.requests.mature,4);assert.equal(c.requests.unknown_acceptance,1);assert.equal(c.requests.observable_denominator,3);assert.equal(c.requests.accepted_within_horizon,1);assert.equal(c.requests.accepted_observed,2);assert.equal(c.requests.acceptance_p50_minutes,60);assert.equal(c.requests.delay_sample,1);assert.equal(c.conversion.value,null);assert.equal(x.comparison.reason,'PARTIAL_SOURCE');assert.equal(c.finance.due_balance,null);});
tx('6.3 Recent cohort is censored; late acceptance never retrospectively enters the 24h numerator',async()=>{await seed();await db.exec(`DELETE FROM public.missions WHERE id='${u(202)}';UPDATE public.service_requests SET status='new' WHERE id='${u(102)}';INSERT INTO public.service_requests(id,city,service_category,description,status,created_at) VALUES('${u(105)}','Fès','plomberie','Synthetic recent cohort','new',(now() AT TIME ZONE 'Africa/Casablanca')::date::timestamp AT TIME ZONE 'Africa/Casablanca'-interval '1 hour');`);await F.actor(db,3);const fixed=current(C.build(await read()));assert.equal(fixed.requests.accepted_within_horizon,1);assert.equal(fixed.conversion.value,0.25);const recent=C.build((await db.query('select public.control_marketplace_cohorts_v1($1) result',[{horizon_hours:168}])).rows[0].result);assert.ok(current(recent).requests.censored>=1);assert.equal(recent.comparison.reason,'CENSORED_COHORT',JSON.stringify({scope:recent.scope,windows:recent.cohorts.map(c=>({label:c.label,start:c.start_at,end:c.end_at,requests:c.requests})),undated:recent.undated_requests,icu:process.versions.icu}));});
tx('6.3 Internal and external proven events deduplicate at request grain',async()=>{await seed();await db.exec(`UPDATE public.missions SET status='cancelled' WHERE id='${u(200)}';INSERT INTO public.enterprise_request_context(service_request_id,enterprise_id,site_id,created_by) VALUES('${u(100)}','${u(30)}','${u(40)}','${u(4)}');INSERT INTO public.enterprise_internal_assignments(id,enterprise_id,service_request_id,worker_id,status,assigned_at) VALUES('${u(300)}','${u(30)}','${u(100)}','${u(60)}','assigned','2026-09-02T10:30Z');`);await F.actor(db,3);const c=current(await read());assert.equal(c.requests.external_within_horizon,1);assert.equal(c.requests.internal_within_horizon,1);assert.equal(c.requests.accepted_within_horizon,1);assert.equal(c.requests.acceptance_p50_minutes,30);});
tx('6.3 Sending time is an explicit dispatch proxy and does not become acceptance',async()=>{await seed();await db.exec(`UPDATE public.dispatch_notification_outbox SET notification_status='SENT',sent_at='2026-09-03T10:20Z' WHERE request_id='${u(101)}';`);await F.actor(db,3);const c=current(await read());assert.equal(c.dispatch.sent_sample,1);assert.equal(c.dispatch.first_sent_p50_minutes,20);assert.equal(c.dispatch.execution_delay,null);assert.equal(c.dispatch.offer_acceptance_rate,null);assert.equal(c.requests.accepted_within_horizon,1);});
tx('6.3 Date windows retain named Casablanca timezone across offset transitions',async()=>{await F.actor(db,3);const x=await read({from:'2026-02-10',to:'2026-03-10'});assert.equal(x.scope.days,28);assert.equal(x.scope.previous_from,'2026-01-13');assert.equal(x.scope.timezone,'Africa/Casablanca');assert.notEqual((Date.parse(x.scope.to_utc)-Date.parse(x.scope.from_utc))/86400000,28,'Civil window should include Ramadan offset change');});
tx('6.3 Direct cohort RPC denies anon and tenant/client users without returning financial facts',async()=>{for(const [n,role] of [[1,'anon'],[1,'authenticated'],[4,'authenticated'],[5,'authenticated'],[3,'service_role']]){await F.actor(db,n,role);await db.exec('SAVEPOINT denied');let err;try{await read();}catch(e){err=e;}await db.exec('ROLLBACK TO SAVEPOINT denied');assert.match(err?.message||'',/FORBIDDEN|permission denied/);}});
test('6.3 Wilson interval handles boundary proportions and a known 50/100 example',()=>{assert.equal(C.wilson(0,0),null);assert.equal(C.wilson(null,10),null);assert.equal(C.wilson(11,10),null);const x=C.wilson(50,100);assert.ok(Math.abs(x.lower-0.40383153)<1e-7);assert.ok(Math.abs(x.upper-0.59616847)<1e-7);assert.ok(C.wilson(0,10).lower>=0);assert.ok(C.wilson(10,10).upper<=1);});
tx('6.3 Quote conversion requires the presented exact version and coherent mission relation',async()=>{await seed();await db.exec(`INSERT INTO public.quotes(id,request_id,artisan_profile_id,proposed_price,status,review_status,quote_version,reviewed_version,presented_at) VALUES('${u(600)}','${u(100)}','${u(20)}',1000,'accepted','approved',1,1,'2026-09-02T10:30Z'),('${u(601)}','${u(101)}','${u(20)}',1000,'accepted','approved',2,2,'2026-09-03T10:30Z');UPDATE public.missions SET accepted_quote_id='${u(600)}',accepted_quote_version=1 WHERE id='${u(200)}';`);await F.actor(db,3);const q=current(await read()).quotes;assert.equal(q.presented_current_versions,2);assert.equal(q.converted_within_horizon,1);assert.equal(q.unknown_accepted_relation,1);assert.match(q.scope,/current.*versions/);});
tx('6.3 Assigned request with no executor proof stays an incomplete conversion source',async()=>{await seed();await db.exec(`DELETE FROM public.missions WHERE id='${u(202)}';`);await F.actor(db,3);const x=C.build(await read());assert.equal(current(x).requests.unknown_acceptance,1);assert.equal(current(x).conversion.value,null);});
function sample(a,b,extra={}){const now=new Date().toISOString();const c=(label,k)=>({label,start_at:label==='current'?'2026-09-01':'2026-08-18',end_at:label==='current'?'2026-09-15':'2026-09-01',requests:{total:100,mature:100,censored:0,unknown_acceptance:0,observable_denominator:100,accepted_within_horizon:k,external_within_horizon:k,internal_within_horizon:0}});return {contract_version:'marketplace-cohorts-v1',scope:{days:14,horizon_hours:24,timezone:'Africa/Casablanca',from:'2026-09-01',to:'2026-09-15',previous_from:'2026-08-18',from_utc:'2026-09-01',to_utc:'2026-09-15',previous_from_utc:'2026-08-18'},as_of:now,undated_requests:0,cohorts:[c('current',a),c('previous',b)],...extra};}
test('6.3 Trend abstains on small samples, overlap, stale data and malformed denominators',()=>{assert.equal(C.build(sample(50,49)).comparison.status,'INCONCLUSIVE');const separated=C.build(sample(10,90));assert.equal(separated.comparison.status,'OBSERVED_DIFFERENCE');assert.equal(separated.comparison.delta_percentage_points,-80);assert.equal(separated.execution_authorized,false);const small=sample(1,1);small.cohorts.forEach(c=>Object.assign(c.requests,{total:2,mature:2,observable_denominator:2}));assert.equal(C.build(small).comparison.reason,'SMALL_SAMPLE');assert.equal(C.build(sample(50,50,{as_of:new Date(Date.now()-61000).toISOString()})).status,'STALE');const bad=sample(50,50);bad.cohorts[0].requests.total=0;assert.equal(C.build(bad).status,'UNAVAILABLE');});
test('6.3 RAFI recommends factual cohort review only for sufficiently observed decline and never executes',()=>{const R=require('../../api/control/rafi-decisions');const build=data=>{const obs={kind:'marketplace.cohorts',count:100,target_type:'cohort',target_id:null,created_at:'2026-09-01',reference:'control_marketplace_cohorts_v1',facts:{cohorts:data,cube_context:true,all_cells:true}};return R.build(Object.fromEntries(R.SOURCES.map(s=>[s,R.sourceState(s,{contract_version:'rafi-observations-v1',source:s,as_of:new Date().toISOString(),observations:s==='network'?[obs]:[],total_observations:s==='network'?1:0,has_more:false})])));};const d=build(sample(10,90)).decisions[0];assert.equal(d.decision_type,'marketplace.conversion_review');assert.equal(d.priority,'P2');assert.equal(d.recommended_action.context.all_cells,true);assert.equal(d.actionability.capability,null);assert.equal(d.actionability.execution_authorized,false);assert.equal(d.impact.kind,'INFERENCE');assert.equal(build(sample(50,49)).decisions.length,0);assert.equal(build(sample(90,10)).decisions.length,0);const incomplete=sample(10,90);incomplete.cohorts[0].requests.censored=1;incomplete.cohorts[0].requests.total=101;assert.equal(build(incomplete).decisions.length,0);});

test('6.3 Canonical civil dates and exact UTC boundaries must both match, including offset transitions',()=>{
 const x=sample(10,90);x.scope={...x.scope,days:28,from:'2026-02-10',to:'2026-03-10',previous_from:'2026-01-13',from_utc:'2026-02-09T23:00:00Z',to_utc:'2026-03-10T00:00:00Z',previous_from_utc:'2026-01-12T23:00:00Z'};
 Object.assign(x.cohorts[0],{start_at:x.scope.from_utc,end_at:x.scope.to_utc});Object.assign(x.cohorts[1],{start_at:x.scope.previous_from_utc,end_at:x.scope.from_utc});assert.equal(C.build(x).comparison.status,'OBSERVED_DIFFERENCE');
 for(const change of [v=>v.scope.days=27,v=>v.scope.from='2026-02-30',v=>v.scope.previous_from='2026-01-12',v=>v.cohorts[1].end_at='2026-02-10T00:00:00Z',v=>delete v.scope.timezone]){const bad=structuredClone(x);change(bad);assert.equal(C.build(bad).comparison.reason,'INCOMPARABLE_OR_UNDATED');}
});
