'use strict';
const {test}=require('node:test'),assert=require('node:assert/strict');
const {createHandler}=require('../../api/control');
const id='00000000-0000-4000-8000-000000000001',env={SUPABASE_URL:'https://abcdefghijklmnopqrst.supabase.co',SUPABASE_ANON_KEY:'sb_publishable_SYNTHETIC',FIXEO_STAGING_PROJECT_REF:'abcdefghijklmnopqrst',VERCEL_ENV:'preview',VERCEL_URL:'test.vercel.app'};
const reply=(data,status=200)=>({ok:status<400,status,text:async()=>JSON.stringify(data)});
async function run(op,body,fetchImpl,headers={authorization:'Bearer synthetic.not_a_real_token'}){const res={headers:{},setHeader(k,v){this.headers[k]=v;},status(v){this.statusCode=v;return this;},json(v){this.body=v;return this;}};await createHandler({env,fetchImpl})({method:'POST',url:'/api/control-v1/'+op,headers,body},res);return res;}
const routes=[['dossier',{type:'request',id},'control_dossier_section_v1'],['dossier-section',{type:'worker',id,section:'timeline'},'control_dossier_section_v1'],['operations',{executor:'internal',origin:'enterprise',min_age:60},'control_operations_page_v1'],['search',{query:id},'control_search_all_v1'],['operation-context',{request_id:id},'control_operation_read_v1'],['hybrid-context',{request_id:id},'control_hybrid_read_v1'],['hybrid/preview',{capability:'enterprise.assign',target_id:id,payload:{worker_id:id,reason:'Synthetic'}},'control_hybrid_preview_v1'],['hybrid/execute',{preview_id:id,confirmed:true,idempotency_key:id},'control_hybrid_execute_v1']];
test('B34 API fixed allowlist routes preserve user JWT and never choose service-role access',async()=>{for(const [op,body,name] of routes){const calls=[];const res=await run(op,body,async(url,o)=>{calls.push({url,o});return reply(url.endsWith('/user')?{id}:{});});assert.equal(res.statusCode,200,op);assert.ok(calls[1].url.endsWith('/'+name),op);assert.equal(calls[1].o.headers.Authorization,'Bearer synthetic.not_a_real_token');assert.equal(calls[1].o.headers.apikey,'sb_publishable_SYNTHETIC');assert.equal(res.headers['Cache-Control'],'private, no-store');}});
test('B34 API authentication and cross-origin checks precede all RPC calls',async()=>{for(const [op,body] of routes){assert.equal((await run(op,body,()=>{throw Error('unexpected');},{})).statusCode,401);assert.equal((await run(op,body,()=>{throw Error('unexpected');},{authorization:'Bearer synthetic.not_a_real_token',origin:'https://bad.invalid'})).statusCode,403);}});
test('B34 API rejects arbitrary RPCs, payload fields and missing confirmations',async()=>{const fetchImpl=async()=>reply({id});for(const [op,body] of routes)assert.equal((await run(op,{...body,table:'users'},fetchImpl)).statusCode,400,op);assert.equal((await run('hybrid/preview',{capability:'enterprise.delete',target_id:id,payload:{}},fetchImpl)).statusCode,400);assert.equal((await run('hybrid/execute',{preview_id:id,confirmed:false,idempotency_key:id},fetchImpl)).statusCode,428);});
test('B34 API timeout and permission denial remain explicit errors, never empty healthy pages',async()=>{for(const [op,body] of routes.slice(0,6)){const res=await run(op,body,async url=>{if(url.endsWith('/user'))return reply({id});const e=Error('timeout');e.name='TimeoutError';throw e;});assert.equal(res.statusCode,503);assert.equal(res.body.code,'SOURCE_TIMEOUT');assert.equal(res.body.items,undefined);const denied=await run(op,body,async url=>url.endsWith('/user')?reply({id}):reply({code:'42501',message:'FORBIDDEN'},403));assert.equal(denied.statusCode,403);}});
test('B34 API preserves durable failed execution audit with conflict status',async()=>{const r=await run('hybrid/execute',{preview_id:id,confirmed:true,idempotency_key:id},async url=>reply(url.endsWith('/user')?{id}:{ok:false,code:'STALE_PREVIEW',audit_id:id}));assert.equal(r.statusCode,409);assert.equal(r.body.audit_id,id);});
