'use strict';
const {test,before,after}=require('node:test'),assert=require('node:assert/strict');
const F=require('./bloc6-fixture.cjs'),u=F.uuid;let db;
const window={from:'2026-09-01',to:'2026-09-15'};
const rpc=async(n,args)=>(await db.query(`select public.${n}(${args.map((_,i)=>'$'+(i+1)).join(',')}) result`,args)).rows[0].result;
const cube=(s='operations',f={},a=null,l=25)=>rpc('control_marketplace_cube_v1',[s,{...window,...f},a,l]);
const pop=(k='cohort',f={},a=null,l=25)=>rpc('control_marketplace_population_v1',[k,{...window,...f},a,l]);
const coverage=(f={},a=null,l=5)=>rpc('control_marketplace_coverage_v1',[{...window,...f},a,l]);
before(async()=>{db=await F.setup();await F.seed(db);});after(async()=>db?.close());
function tx(name,fn){test(name,async()=>{await db.exec('RESET ROLE; BEGIN');try{await fn();}finally{await db.exec('ROLLBACK; RESET ROLE');}});}
async function denied(fn,pattern){await db.exec('SAVEPOINT denied');let err;try{await fn();}catch(e){err=e;}await db.exec('ROLLBACK TO SAVEPOINT denied; RELEASE SAVEPOINT denied');assert.ok(err,'expected refusal');assert.match(err.message,pattern);}
async function requests(){await db.exec(`INSERT INTO public.service_requests(id,city,service_category,description,status,created_at,data_classification) VALUES
 ('${u(100)}',' Fès ','Plomberie','Synthetic local demand','new','2026-09-03T10:00Z','test'),
 ('${u(101)}','Fes','plomberie','Synthetic local demand','new','2026-09-04T10:00Z','test'),
 ('${u(102)}','Casablanca','électricité','Synthetic secondary skills','new','2026-09-05T10:00Z','test'),
 ('${u(103)}','Rabat','serrurerie','Synthetic no local profile','new','2026-08-01T10:00Z','test'),
 ('${u(104)}','','autre','Synthetic unknown dimension','new','2026-09-08T10:00Z','test'),
 ('${u(105)}','Fès','plomberie','Synthetic boundary','completed','2026-09-14T23:00Z','test');`);}
tx('6.1 Empty complete source yields exact zero cells, no invented coverage',async()=>{await F.actor(db,3);const x=await cube();assert.equal(x.total_cells,0);assert.deepEqual(x.items,[]);assert.equal(x.source_state,'FRESH');assert.equal((await coverage()).coverage_rate,null);});
tx('6.1 Normalized cell grain and Casablanca half-open days preserve raw provenance',async()=>{await requests();await F.actor(db,3);const x=await cube();assert.equal(x.total_cells,4);const fes=x.items.find(x=>x.city==='fes');assert.equal(fes.facts.cohort_requests,2);assert.equal(fes.facts.open,2);assert.equal(x.scope.to_utc,'2026-09-14T23:00:00+00:00');const p=await pop('cohort',{city:'Fes',trade:'plomberie'});assert.equal(p.total,2);assert.equal(p.items.find(x=>x.id===u(100)).facts.raw_city,' Fès ');assert.equal(p.items.find(x=>x.id===u(100)).facts.trade,'plomberie');});
tx('6.1 Stock includes old open requests while cohorts exclude them; unknown dimensions stay unknown',async()=>{await requests();await F.actor(db,3);const x=await cube();const rabat=x.items.find(x=>x.city==='rabat');assert.equal(rabat.facts.cohort_requests,0);assert.equal(rabat.facts.waiting,1);const unknown=x.items.find(x=>x.city===null);assert.equal(unknown.trade,null);assert.equal((await pop('open',{city:'__unknown__',trade:'__unknown__'})).total,1);});
tx('6.1 Multiactivity uses distinct artisans per cell, never infers dispatch eligibility or residual capacity',async()=>{await requests();await F.actor(db,3);const x=await cube('network');const c=x.items.find(x=>x.city==='casablanca');assert.equal(c.trade,'electricite');assert.equal(c.facts.referenced,1);assert.equal(c.facts.available_declared,1);assert.equal(c.facts.eligible,null);assert.equal(c.facts.coverage,null);assert.equal(c.facts.residual_capacity,null);assert.equal((await pop('profiles',{city:'Casablanca',trade:'électricité'})).items[0].id,u(20));});
tx('6.1 Claimable requires canonical flag, owner absence and no pending claim; verification is separate',async()=>{await requests();await db.exec(`UPDATE public.artisans SET city='Fès',service_category='plomberie',claimable=true WHERE id='${u(21)}'`);await F.actor(db,3);assert.equal((await pop('claimable',{city:'Fès',trade:'plomberie'})).total,1);assert.equal((await pop('verification_ready',{city:'Fès',trade:'plomberie'})).items[0].id,u(20));await db.exec(`RESET ROLE; INSERT INTO public.claim_requests(artisan_id,requester_user_id,requester_name) VALUES('${u(21)}','${u(6)}','Synthetic claimant')`);await F.actor(db,3);assert.equal((await pop('claimable',{city:'Fès',trade:'plomberie'})).total,0);});
tx('6.1 Exact populations, cursor scope and cell pagination do not skip or duplicate',async()=>{await requests();await F.actor(db,3);let cursor=null,keys=[];do{const x=await cube('operations',{},cursor,1);keys.push(...x.items.map(x=>x.key));cursor=x.has_more?x.next_cursor:null;}while(cursor);assert.equal(new Set(keys).size,4);const a=await pop('cohort',{},null,1),b=await pop('cohort',{},a.next_cursor,1);assert.notEqual(a.items[0].id,b.items[0].id);await denied(()=>pop('open',{},a.next_cursor),/INVALID_CURSOR/);const c=await cube('operations',{},null,1);await denied(()=>cube('network',{city:'Fes'},c.next_cursor),/INVALID_CURSOR/);});
tx('6.1 Offers do not become acceptances and request counts survive multiple missions',async()=>{await requests();await db.exec(`INSERT INTO public.missions(id,request_id,artisan_profile_id,status) VALUES('${u(200)}','${u(101)}','${u(20)}','offered'),('${u(201)}','${u(101)}','${u(21)}','expired');`);await F.actor(db,3);const x=await pop('cohort',{city:'Fès'});assert.equal(x.total,2);const r=x.items.find(x=>x.id===u(101)).facts;assert.equal(r.accepted_at,null);assert.equal(r.waiting,true);assert.equal(r.offers,1);});
tx('6.1 Missing parents remain UNKNOWN/NOT_FOUND and P0 remains enforced without writes',async()=>{await requests();await db.exec(`INSERT INTO public.missions(id,request_id,artisan_profile_id,status) VALUES('${u(200)}','${u(100)}','${u(20)}','done');DELETE FROM public.service_requests WHERE id='${u(100)}';`);const before=(await db.query(`select to_jsonb(m) j from public.missions m`)).rows;await F.actor(db,3);assert.equal((await cube()).unattributed_missions,1);assert.equal((await cube('operations',{city:'Fes'})).unattributed_missions,null);const facts=await rpc('control_finance_context_v1',['mission',u(200),null,25]);assert.equal(facts.facts.request_relation,'NOT_FOUND');assert.equal(facts.facts.due_balance,null);await denied(()=>rpc('control_action_preview_v1',['mission.settle',u(200),{final_price:500,reason:'Synthetic refused'},u(999)]),/REQUEST_NOT_FOUND/);await db.exec('RESET ROLE');await denied(()=>rpc('admin_settle_mission_v1',[u(200),500,null,'Synthetic refused']),/REQUEST_NOT_FOUND/);await db.exec('RESET ROLE');assert.deepEqual((await db.query(`select to_jsonb(m) j from public.missions m`)).rows,before);});
tx('6.1 Coverage explicitly calls canonical preview, bounded and no business execution',async()=>{await requests();await F.actor(db,3);const x=await coverage({city:'Fes',trade:'plomberie'},null,1);assert.equal(x.total_waiting,2);assert.equal(x.items.length,1);assert.equal(x.has_more,true);assert.equal(x.items[0].authority,'dispatch_preview_v22');const y=await coverage({city:'Fes',trade:'plomberie'},x.next_cursor,1);assert.notEqual(x.items[0].id,y.items[0].id);assert.equal(y.execution_authorized,false);await db.exec('RESET ROLE');assert.equal((await db.query('select count(*) n from public.missions')).rows[0].n,0);});
tx('6.1 Admin-only reads reject anon, tenant users, authenticated clients and service role',async()=>{for(const [n,role] of [[1,'anon'],[1,'authenticated'],[2,'authenticated'],[4,'authenticated'],[5,'authenticated'],[3,'service_role']]){await F.actor(db,n,role);for(const fn of [()=>cube(),()=>pop(),()=>coverage()])await denied(fn,/permission denied|FORBIDDEN/);}});
tx('6.1 Enterprise site and account boundaries remain enforced; no private worker labels or contacts',async()=>{await requests();await db.exec(`INSERT INTO public.enterprise_request_context(service_request_id,enterprise_id,site_id,created_by) VALUES('${u(101)}','${u(30)}','${u(40)}','${u(4)}');`);await F.actor(db,3);assert.equal((await pop('cohort',{enterprise_id:u(30),site_id:u(40)})).total,1);assert.equal((await pop('cohort',{enterprise_id:u(31)})).total,0);await denied(()=>cube('operations',{enterprise_id:u(30),site_id:u(41)}),/INVALID_TENANT_CONTEXT/);const x=await coverage({enterprise_id:u(30)});assert.equal(x.items[0].status,'ENTERPRISE_CONTEXT');assert.equal(x.items[0].facts.tenant_operator,false);assert.equal(x.items[0].has_eligible_candidate,null);assert.ok(!JSON.stringify(x).includes('PRIVATE'));});
tx('6.1 Invalid filters never silently broaden scope, unknown trade is explicit',async()=>{await F.actor(db,3);for(const f of [{from:'2026-09-02',to:'2026-09-01'},{to:'2035-01-01'},{from:'2025-01-01'},{from:'2026-09-01T12:00Z'},{classification:'bad'},{trade:'not-a-canonical-trade'},{rpc:'secret'},{city:{a:1}},{horizon_hours:2}])await denied(()=>cube('operations',f),/INVALID/);await denied(()=>coverage({},null,6),/INVALID_LIMIT/);await denied(()=>pop('profiles'),/DIMENSIONS_REQUIRED/);});
tx('6.1 SQL metadata seals helpers and grants only guarded read RPCs',async()=>{const rows=(await db.query(`SELECT n.nspname,p.proname,p.provolatile,p.prosecdef,p.proconfig,pg_get_userbyid(p.proowner) owner,has_function_privilege('anon',p.oid,'EXECUTE') anon,has_function_privilege('service_role',p.oid,'EXECUTE') service,has_function_privilege('authenticated',p.oid,'EXECUTE') authenticated FROM pg_proc p JOIN pg_namespace n ON n.oid=p.pronamespace WHERE p.proname LIKE 'control_marketplace_%'`)).rows;assert.ok(rows.length>=7);for(const x of rows){assert.ok(['s','i'].includes(x.provolatile));assert.equal(x.owner,'postgres');assert.ok(x.proconfig.includes('search_path=""'));assert.equal(x.anon,false);assert.equal(x.service,false);assert.equal(x.authenticated,x.nspname==='public');}});
