'use strict';
const {test,before,after}=require('node:test'),assert=require('node:assert/strict');
const {setup,seed,actor,uuid}=require('./bloc5-fixture.cjs');
let db;
const rpc=async(name,args)=>(await db.query(`select public.${name}(${args.map((_,i)=>'$'+(i+1)).join(',')}) result`,args)).rows[0].result;
const page=(filters={},after=null,limit=25)=>rpc('control_people_page_v1',[filters,after,limit]);
const context=(type,id,after=null,limit=25)=>rpc('control_people_context_v1',[type,uuid(id),after,limit]);
before(async()=>{db=await setup();await seed(db);});after(async()=>db?.close());
function tx(name,fn){test(name,async()=>{await db.exec('RESET ROLE; BEGIN');try{await fn();}finally{await db.exec('ROLLBACK; RESET ROLE');}});}
async function denied(fn,pattern){await db.exec('SAVEPOINT denied');let err;try{await fn();}catch(e){err=e;}await db.exec('ROLLBACK TO SAVEPOINT denied; RELEASE SAVEPOINT denied');assert.ok(err,'Expected refusal');assert.match(err.message,pattern);}
tx('5.1 People readers deny anon, non-admin, tenant owners and service role directly',async()=>{for(const [n,role] of [[1,'anon'],[1,'authenticated'],[2,'authenticated'],[4,'authenticated'],[5,'authenticated'],[3,'service_role']]){await actor(db,n,role);await denied(()=>page(),/permission denied|FORBIDDEN/);await denied(()=>context('enterprise',30),/permission denied|FORBIDDEN/);}});
tx('5.1 Reads are STABLE, guarded Admin, empty search_path with sealed private helper',async()=>{const rows=(await db.query(`select proname,provolatile,prosecdef,proconfig,pg_get_userbyid(proowner) owner,has_function_privilege('anon',oid,'EXECUTE') anon,has_function_privilege('service_role',oid,'EXECUTE') service,has_function_privilege('authenticated',oid,'EXECUTE') authenticated from pg_proc where proname in('control_people_facts_v1','control_people_page_v1','control_people_context_v1')`)).rows;assert.equal(rows.length,3);for(const x of rows){assert.equal(x.provolatile,'s');assert.equal(x.owner,'postgres');assert.equal(x.prosecdef,true);assert.ok(x.proconfig.includes('search_path=""'));assert.equal(x.anon,false);assert.equal(x.service,false);assert.equal(x.authenticated,x.proname!=='control_people_facts_v1');}});
tx('5.1 Exact totals and stable pagination reach every canonical object without duplicates',async()=>{await actor(db,3);let cursor=null,keys=[],total;do{const p=await page({},cursor,2);total=p.total;keys.push(...p.items.map(x=>x.key));cursor=p.next_cursor;}while(cursor);assert.equal(keys.length,total);assert.equal(new Set(keys).size,total);assert.ok(keys.some(x=>x.startsWith('worker:')));assert.ok(keys.some(x=>x.startsWith('client:')));});
tx('5.1 Secondary cities/trades match without duplicating profiles; canonical availability is not inferred',async()=>{await actor(db,3);const p=await page({type:'artisan',city:'Casablanca',trade:'electricite'});assert.equal(p.total,1);assert.equal(p.items[0].id,uuid(20));const unknown=await page({type:'artisan',state:'unknown'});assert.equal(unknown.total,0);assert.equal((await page({type:'artisan',state:'unavailable'})).items[0].id,uuid(21));assert.equal((await page({type:'artisan',state:'available'})).total,1);});
tx('5.1 Completeness records missing fields; it is distinct from verification and ownership',async()=>{await actor(db,3);const all=await page({type:'artisan'});const a=all.items.find(x=>x.id===uuid(20)),b=all.items.find(x=>x.id===uuid(21));assert.deepEqual(a.facts.missing_fields,[]);assert.equal(a.facts.verification_ready,true);assert.equal(a.facts.ownership,'claimed');assert.ok(b.facts.missing_fields.includes('phone'));assert.ok(b.facts.missing_fields.includes('description'));assert.equal(b.facts.ownership,'unclaimed');assert.equal(b.facts.verification_ready,false);assert.ok(!JSON.stringify(all).includes('PRIVATE PROFILE DESCRIPTION'));});
tx('5.1 Tenant and site filters cannot mix Enterprise A and B',async()=>{await actor(db,3);const p=await page({type:'worker',enterprise_id:uuid(30),site_id:uuid(40)});assert.equal(p.total,1);assert.equal(p.items[0].id,uuid(60));await denied(()=>page({enterprise_id:uuid(30),site_id:uuid(41)}),/FORBIDDEN/);await denied(()=>page({site_id:uuid(40)}),/FORBIDDEN/);const c=await context('enterprise',30);assert.ok(c.memberships.every(x=>x.enterprise_id===uuid(30)));assert.ok(!JSON.stringify(c).includes(uuid(52)));});
tx('5.1 Members and workforce stay separate; no private worker label, contact or Business data',async()=>{await actor(db,3);const p=await page({type:'worker'});const a=p.items.find(x=>x.id===uuid(60));assert.equal(a.facts.member_id,uuid(51));assert.equal(a.facts.residual_capacity,2);assert.equal(a.summary.max_concurrent_jobs,2);assert.ok(!JSON.stringify(p).includes('PRIVATE'));const e=await context('enterprise',30);assert.equal(e.facts.members,2);assert.equal(e.facts.workers,1);assert.equal(e.facts.tenant_dispatch_operator,false);for(const m of e.memberships)assert.deepEqual(Object.keys(m).sort(),['created_at','enterprise_id','id','role','status','user_id']);});
tx('5.1 Membership pagination, explicit site assignments and client membership links are factual',async()=>{await actor(db,3);const a=await context('enterprise',30,null,1),b=await context('enterprise',30,a.next_cursor,1);assert.equal(a.membership_total,2);assert.notEqual(a.memberships[0].id,b.memberships[0].id);assert.equal((await context('site',40)).membership_scope,'explicit_site_assignments_only');assert.equal((await context('site',40)).membership_total,1);assert.equal((await context('client',4)).memberships[0].enterprise_id,uuid(30));});
tx('5.1 Cursor is bound to filters; arbitrary fields, types, limits and missing objects are refused',async()=>{await actor(db,3);const a=await page({},null,1);await denied(()=>page({type:'artisan'},a.next_cursor),/INVALID_CURSOR/);for(const f of [{secret:true},{type:'personal_client'},{state:'healthy'},{query:123}])await denied(()=>page(f),/INVALID_FILTER/);await denied(()=>page({},null,0),/INVALID_FILTER/);await denied(()=>context('worker',99999),/NOT_FOUND/);await denied(()=>context('personal_client',1),/INVALID_FILTER/);});
tx('5.1 Empty filtered populations are real zeros, not source errors; missing classification is not fabricated',async()=>{await actor(db,3);const p=await page({city:'No such city'});assert.equal(p.total,0);assert.deepEqual(p.items,[]);assert.equal(p.source_state,'FRESH');assert.equal((await page({type:'client',classification:'production'})).total,0);});
