'use strict';
const {test}=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),{JSDOM}=require('jsdom');
const root=path.resolve(__dirname,'../..'),id='00000000-0000-4000-8000-000000000100',other='00000000-0000-4000-8000-000000000101';
const tick=()=>new Promise(r=>setImmediate(r));
function page(override){
 const dom=new JSDOM(fs.readFileSync(path.join(root,'admin.html'),'utf8'),{url:'https://isolated.invalid/admin.html?view=operations',runScripts:'outside-only',pretendToBeVisual:true}),w=dom.window,calls=[];w.setInterval=()=>0;
 w.FixeoControl={request:async(op,body)=>{calls.push({op,body});const value=await override?.(op,body);if(value!==undefined)return value;
  if(op==='dossier')return {entity_type:body.type,id:body.id,request_id:body.type==='request'?body.id:null,summary:{id:body.id,status:'new',city:'Fès',service_category:'plomberie'},provenance:'public.service_requests',as_of:new Date().toISOString()};
  if(op==='dossier-section')return {items:[],has_more:false,as_of:new Date().toISOString()};
  if(op==='operation-context')return {item:{id:body.request_id,status:'new',operational_state:'waiting',executor:'unassigned',origin:'client',active_offers:0,dispatch:{queued:0,sent_evidence:0,retry_count:0}},as_of:new Date().toISOString()};
  if(op==='operations'||op==='search')return {items:[],has_more:false,as_of:new Date().toISOString()};
  throw Error('Unexpected operation '+op);
 },command:async()=>{throw Error('UNEXPECTED_MUTATION');}};
 for(const file of ['admin-fixeo-dossier.js','admin-fixeo-operations.js'])w.eval(fs.readFileSync(path.join(root,'js',file),'utf8'));
 return {w,calls,close:()=>w.close()};
}
test('B34 Dossier deep link, focus trap, Escape and return focus are functional',async()=>{const p=page();try{const opener=p.w.document.getElementById('refresh');opener.focus();await p.w.FixeoDossier.open('request',id);assert.equal(new URL(p.w.location.href).searchParams.get('dossier'),'request:'+id);assert.equal(p.w.document.getElementById('drawer').getAttribute('aria-modal'),'true');assert.equal(p.w.document.activeElement.id,'drawer-close');const focusable=p.w.document.querySelectorAll('#drawer button:not([disabled])');focusable[focusable.length-1].focus();p.w.document.dispatchEvent(new p.w.KeyboardEvent('keydown',{key:'Tab',bubbles:true,cancelable:true}));assert.equal(p.w.document.activeElement.id,'drawer-close');p.w.document.dispatchEvent(new p.w.KeyboardEvent('keydown',{key:'Escape',bubbles:true}));assert.equal(p.w.document.getElementById('drawer').hidden,true);assert.equal(p.w.document.activeElement,opener);assert.equal(p.w.document.querySelector('.os').hasAttribute('inert'),false);}finally{p.close();}});
test('B34 independent dossier sections preserve identity and relations when timeline times out',async()=>{const p=page((op,b)=>{if(op==='dossier-section'&&b.section==='timeline')throw Error('SOURCE_TIMEOUT');});try{await p.w.FixeoDossier.open('request',id);assert.match(p.w.document.getElementById('drawer-summary').textContent,/public.service_requests/);assert.match(p.w.document.getElementById('dossier-timeline').textContent,/SOURCE ERROR.*SOURCE_TIMEOUT/);assert.match(p.w.document.getElementById('dossier-relations').textContent,/Aucun lien canonique/);assert.equal(p.calls.filter(x=>x.op.includes('execute')).length,0);}finally{p.close();}});
test('B34 relations paginate, preserve provenance, escape source text and navigate to a real dossier',async()=>{const p=page((op,b)=>{if(op==='dossier-section'&&b.section==='relations')return {items:[{type:'request',id:b.after?other:id,relation:'<img src=x>',source:'canonical FK',access:'accessible'}],has_more:!b.after,next_cursor:b.after?null:{key:'cursor'},as_of:new Date().toISOString()};});try{await p.w.FixeoDossier.open('client',id);assert.equal(p.w.document.querySelector('#dossier-relations img'),null);p.w.document.querySelector('[data-dossier-more="relations"]').click();await tick();await tick();assert.equal(p.w.document.querySelectorAll('#dossier-relations [data-dossier-type]').length,2);p.w.document.querySelectorAll('#dossier-relations [data-dossier-type]')[1].click();await tick();assert.equal(p.calls.filter(x=>x.op==='dossier').at(-1).body.id,other);}finally{p.close();}});
test('B34 late responses cannot overwrite the currently selected dossier',async()=>{let release;const p=page((op,b)=>{if(op==='dossier'&&b.id===id)return new Promise(r=>release=r);});try{const old=p.w.FixeoDossier.open('request',id);await tick();await p.w.FixeoDossier.open('request',other);release({entity_type:'request',id,summary:{name:'OBSOLETE'},as_of:new Date().toISOString()});await old;assert.ok(!p.w.document.getElementById('drawer-summary').textContent.includes('OBSOLETE'));assert.match(p.w.document.getElementById('drawer-sub').textContent,/000101/);}finally{p.close();}});
test('B34 hybrid context cannot display action controls without canonical tenant permission',async()=>{const p=page((op,b)=>{if(op==='dossier')return {entity_type:'request',id,request_id:id,summary:{status:'new'},enterprise_context:{enterprise_id:other},as_of:new Date().toISOString()};if(op==='hybrid-context')return {actionable:false,tenant_operator:false,unavailable_reason:'TENANT_DISPATCH_PERMISSION_REQUIRED',policy:{mode:'internal_only'},workers:[],source:'canonical workforce',as_of:new Date().toISOString(),rpc:{assign:'assign_enterprise_internal_worker_v1',retry:'retry_enterprise_hybrid_dispatch_v1'}};});try{await p.w.FixeoDossier.open('request',id);assert.equal(p.w.document.querySelectorAll('[data-rafi-prepare]').length,0);assert.match(p.w.document.getElementById('dossier-hybrid').textContent,/permission.*absente/);}finally{p.close();}});
test('B34 Operations source error is explicit and does not become a zero or an empty success',async()=>{const p=page(op=>{if(op==='operations')throw Error('SOURCE_TIMEOUT');});try{await p.w.FixeoOperations.refresh(true);assert.match(p.w.document.getElementById('operations-list').textContent,/SOURCE_TIMEOUT/);assert.match(p.w.document.getElementById('ops-count').textContent,/SOURCE ERROR/);assert.equal(p.w.document.getElementById('ops-more').hidden,true);}finally{p.close();}});
test('B34 RAFI Operations context preserves city/trade/tenant/site/classification in the server request',async()=>{const p=page();try{p.w.FixeoOperations.setContext({view:'operations',city:'Fès',trade:'plomberie',enterprise_id:id,site_id:other,classification:'unclassified'});await tick();const b=p.calls.find(x=>x.op==='operations').body;assert.equal(b.city,'Fès');assert.equal(b.trade,'plomberie');assert.equal(b.enterprise_id,id);assert.equal(b.site_id,other);assert.equal(b.classification,'unclassified');assert.match(p.w.document.getElementById('ops-context').textContent,/enterprise_id/);}finally{p.close();}});
test('B34 direct URL restores dossier through the canonical reader',async()=>{const p=page();try{p.w.history.replaceState({},'','/admin.html?view=operations&dossier=worker:'+id);p.w.FixeoDossier.fromRoute();await tick();await tick();assert.deepEqual(JSON.parse(JSON.stringify(p.calls.find(x=>x.op==='dossier').body)),{type:'worker',id});}finally{p.close();}});
