'use strict';
const {test,before,after}=require('node:test'),assert=require('node:assert/strict'),F=require('./bloc6-fixture.cjs'),M=require('../../api/control/marketplace-intelligence'),R=require('../../api/control/rafi-decisions');
const u=F.uuid;let db;
const cell=(o={},n={})=>({key:'fes:plomberie',city:'fes',trade:'plomberie',operations:{waiting:2,urgent_waiting:0,...o},network:{referenced:2,available_declared:0,availability_unknown:0,claimable:1,verification_ready:1,...n}});
test('6.2 Empty, partial and unknown sources create no fictional network opportunity',()=>{assert.deepEqual(M.opportunities([cell({waiting:0})]),[]);assert.deepEqual(M.opportunities([{...cell(),network:null}]),[]);assert.deepEqual(M.opportunities([cell({}, {referenced:null})]),[]);assert.ok(!M.opportunities([cell({}, {availability_unknown:1})]).some(x=>x.type==='availability'));});
test('6.2 Recruitment, temporary availability and activation stay facts/inferences/recommendations',()=>{const gap=M.opportunities([cell({urgent_waiting:1},{referenced:0,claimable:0,verification_ready:0})])[0];assert.equal(gap.type,'recruitment');assert.equal(gap.priority,'P1');assert.equal(gap.impact.kind,'INFERENCE');assert.equal(gap.recommended_action.population,'waiting');assert.equal(gap.execution_authorized,false);const items=M.opportunities([cell()]);assert.deepEqual(items.map(x=>x.type).sort(),['activate','availability','verify']);assert.ok(items.every(x=>x.evidence.kind==='FACT'&&x.recommended_action.kind==='RECOMMENDATION'));});
test('6.2 Stable priorities/identities and no causal revenue or invented staffing target',()=>{const a=M.opportunities([cell(),{...cell({urgent_waiting:1}),key:'rabat',city:'rabat'}]);const b=M.opportunities([{...cell({urgent_waiting:1}),key:'rabat',city:'rabat'},cell()]);assert.deepEqual(a,b);assert.equal(new Set(a.map(x=>x.id)).size,a.length);assert.ok(a.every(x=>['P1','P2','P3'].includes(x.priority)));assert.ok(a.every(x=>x.predicted_revenue===undefined&&x.recruitment_target===undefined));});
before(async()=>{db=await F.setup();await F.seed(db);});after(async()=>db?.close());
async function rpc(n,args){return(await db.query(`select public.${n}(${args.map((_,i)=>'$'+(i+1)).join(',')}) result`,args)).rows[0].result;}
function tx(name,fn){test(name,async()=>{await db.exec('RESET ROLE;BEGIN');try{await fn();}finally{await db.exec('ROLLBACK;RESET ROLE');}});}
tx('6.1/6.2 RAFI uses normalized Cube facts and routes to exact populations without new capabilities',async()=>{await db.exec(`INSERT INTO public.service_requests(id,city,service_category,description,status,urgency) VALUES('${u(100)}','Fès','plomberie','Synthetic activation','new','urgent'),('${u(101)}','Fes','plomberie','Synthetic normalized activation','new','normale');UPDATE public.artisans SET city='Fès',service_category='plomberie',claimable=true WHERE id='${u(21)}';`);await F.actor(db,3);const x=await rpc('control_marketplace_signals_v1',['network','all']);assert.equal(x.total_observations,1);const o=x.observations[0];assert.equal(o.count,2);assert.equal(o.city,'fes');assert.equal(o.facts.to_verify,1);assert.equal(o.facts.unclaimed,1);const states=Object.fromEntries(R.SOURCES.map(s=>[s,R.sourceState(s,s==='network'?x:{...x,source:s,observations:[],total_observations:0})]));const decisions=R.build(states).decisions;assert.ok(decisions.length>=3);assert.ok(decisions.every(d=>d.recommended_action.context.view==='intelligence'));assert.ok(decisions.every(d=>d.actionability.capability===null&&d.actionability.execution_authorized===false));assert.ok(decisions.some(d=>d.decision_type==='network.verify'));assert.ok(decisions.some(d=>d.decision_type==='network.activate'));assert.equal(new Set(decisions.map(x=>x.decision_id)).size,decisions.length);});
tx('6.2 Signal source rejects tenant/client identities and excludes private profile text',async()=>{await F.actor(db,1);await db.exec('SAVEPOINT denied');let error;try{await rpc('control_marketplace_signals_v1',['network','all']);}catch(e){error=e;}await db.exec('ROLLBACK TO SAVEPOINT denied');assert.match(error.message,/FORBIDDEN/);await F.actor(db,3);assert.ok(!JSON.stringify(await rpc('control_marketplace_signals_v1',['network','all'])).includes('PRIVATE'));});
tx('6.1 Measured 2000-request aggregation stays bounded by cells and makes no business writes',async()=>{await db.exec(`INSERT INTO public.service_requests(id,city,service_category,description,status) SELECT ('00000000-0000-4000-8000-'||lpad(n::text,12,'0'))::uuid,'Synthetic City '||(n%40),'plomberie','Synthetic performance population','new' FROM generate_series(1000,2999)n;`);const auditBefore=(await db.query('select count(*) n from fixeo_private.authority_audit_events_v1')).rows[0].n;await F.actor(db,3);const start=performance.now(),x=await rpc('control_marketplace_cube_v1',['operations',{},null,25]),duration=performance.now()-start;assert.equal(x.total_cells,40);assert.equal(x.items.length,25);assert.equal(x.has_more,true);assert.ok(JSON.stringify(x).length<100000);assert.ok(duration<4000,'Read exceeds API budget');console.log(JSON.stringify({gate:'6.1-performance',requests:2000,cells:40,page:25,ms:Math.round(duration),bytes:Buffer.byteLength(JSON.stringify(x))}));await db.exec('RESET ROLE');assert.equal((await db.query('select count(*) n from public.missions')).rows[0].n,0);assert.equal((await db.query('select count(*) n from fixeo_private.authority_audit_events_v1')).rows[0].n,auditBefore);});
