'use strict';
const {test}=require('node:test'),assert=require('node:assert/strict'),M=require('../../api/control/marketplace-intelligence'),{createHandler}=require('../../api/control');
const id='00000000-0000-4000-8000-000000000001',env={SUPABASE_URL:'https://abcdefghijklmnopqrst.supabase.co',SUPABASE_ANON_KEY:'sb_publishable_SYNTHETIC',FIXEO_STAGING_PROJECT_REF:'abcdefghijklmnopqrst'};
const reply=(data,status=200)=>({ok:status<400,status,text:async()=>JSON.stringify(data)});
test('B6 deployed and local routes reach the canonical handler and revised assets bypass old caches',()=>{
 const fs=require('node:fs'),path=require('node:path'),root=path.resolve(__dirname,'../..'),config=JSON.parse(fs.readFileSync(path.join(root,'vercel.json'),'utf8'));
 const server=fs.readFileSync(path.join(root,'api/server.js'),'utf8'),pattern=server.match(/app\.all\((\/\^\\\/api\\\/control-v1.*?\$\/), function/)[1],local=new RegExp(pattern.slice(1,-1));
 for(const op of ['marketplace','marketplace-population','marketplace-coverage','marketplace-cohorts']){const url='/api/control-v1/'+op;assert.equal(config.routes.find(r=>new RegExp(r.src).test(url))?.dest,'/api/control-fn/index.js');assert.ok(local.test(url));}
 const html=fs.readFileSync(path.join(root,'admin.html'),'utf8'),assets={'admin-fixeo-intelligence':'bloc6','admin-rafi-decision-center':'bloc7','admin-control-os-clean':'stability-b2','fixeo-control-client-v1':'admin-read-bootstrap-p1'};for(const [script,version] of Object.entries(assets))assert.ok(html.includes(script+'.js?v='+version),script);
});
const data=(source)=>({contract_version:M.VERSION,source,as_of:new Date().toISOString(),scope:{from:'2026-09-01',to:'2026-09-15'},scope_hash:'test-scope',items:[{key:'["fes","plomberie"]',city:'fes',trade:'plomberie',facts:{cohort_requests:2,waiting:1,referenced:1}}],total_cells:1,has_more:false,next_cursor:null,unattributed_missions:19});
async function run(op,body,fetchImpl,headers={authorization:'Bearer synthetic.not_a_real_token'}){const res={headers:{},setHeader(k,v){this.headers[k]=v;},status(s){this.statusCode=s;return this;},json(j){this.body=j;return this;}};await createHandler({env,fetchImpl})({method:'POST',url:'/api/control-v1/'+op,headers,body},res);return res;}
test('6.1 Cube API has three controlled parallel readers, public key/user JWT and no-store',async()=>{let active=0,max=0;const names=[];const r=await run('marketplace',{filters:{}},async(url,o)=>{if(url.endsWith('/user'))return reply({id});names.push(url.split('/').at(-1));assert.equal(o.headers.Authorization,'Bearer synthetic.not_a_real_token');assert.equal(o.headers.apikey,'sb_publishable_SYNTHETIC');active++;max=Math.max(max,active);await new Promise(r=>setImmediate(r));active--;return reply(data(JSON.parse(o.body).p_source));});assert.equal(r.statusCode,200);assert.equal(r.body.status,'FRESH');assert.equal(r.body.cells.length,1);assert.equal(max,3);assert.ok(names.every(n=>n==='control_marketplace_cube_v1'));assert.equal(r.headers['Cache-Control'],'private, no-store');});
test('6.1 Slow/error source preserves other facts with null, never zero',async()=>{const r=await run('marketplace',{},async(url,o)=>{if(url.endsWith('/user'))return reply({id});const s=JSON.parse(o.body).p_source;if(s==='network'){const e=Error();e.name='TimeoutError';throw e;}return reply(data(s));});assert.equal(r.body.status,'PARTIAL');assert.equal(r.body.sources.network.error,'SOURCE_TIMEOUT');assert.equal(r.body.cells[0].network,null);assert.equal(r.body.cells[0].operations.waiting,1);});
test('6.1 Any source Auth/ACL rejection fails the whole Admin response closed',async()=>{const r=await run('marketplace',{},async(url,o)=>url.endsWith('/user')?reply({id}):JSON.parse(o.body).p_source==='network'?reply({code:'42501',message:'FORBIDDEN'},403):reply(data(JSON.parse(o.body).p_source)));assert.equal(r.statusCode,403);assert.equal(r.body.cells,undefined);for(const op of ['marketplace','marketplace-population','marketplace-coverage'])assert.equal((await run(op,{},()=>{throw Error('unexpected');},{})).statusCode,401);});
test('6.1 API closed contracts reject table/RPC selection and bad identities',async()=>{for(const b of [{rpc:'private'},{filters:{table:'users'}},{filters:{enterprise_id:'not-uuid'}}])assert.equal((await run('marketplace',b,async()=>reply({id}))).statusCode,400);const calls=[];await run('marketplace-population',{kind:'waiting',filters:{city:'Fes'},after:null},async(url,o)=>{calls.push(url);return reply(url.endsWith('/user')?{id}:{items:[],total:0});});assert.ok(calls.at(-1).endsWith('/control_marketplace_population_v1'));});
test('6.1 Freshness, malformed provenance and concurrent pagination are explicit',()=>{const now=Date.now();assert.equal(M.sourceState('operations',{...data('operations'),as_of:new Date(now-61000).toISOString()},null,now).status,'STALE');assert.equal(M.sourceState('network',{...data('network'),total_cells:null},null,now).status,'UNAVAILABLE');const states=Object.fromEntries(M.SOURCES.map(s=>[s,M.sourceState(s,data(s))]));states.network.data.scope_hash='concurrent';const b=M.build(states);assert.equal(b.status,'PARTIAL');assert.equal(b.sources.network.error,'CONCURRENT_SOURCE_WINDOW');assert.equal(b.cells[0].network,null);});
test('6.3 Cohort API has a single fixed read RPC, with explicit timeout and malformed-source refusal',async()=>{let name;const r=await run('marketplace-cohorts',{filters:{horizon_hours:24}},async(url,o)=>{if(url.endsWith('/user'))return reply({id});name=url.split('/').at(-1);return reply({});});assert.equal(name,'control_marketplace_cohorts_v1');assert.equal(r.body.status,'UNAVAILABLE');assert.equal(r.body.error,'INVALID_COHORT_PROVENANCE');const e=await run('marketplace-cohorts',{},async url=>{if(url.endsWith('/user'))return reply({id});const error=Error();error.name='TimeoutError';throw error;});assert.equal(e.body.code,'SOURCE_TIMEOUT');assert.equal(e.body.cohorts,undefined);});
