'use strict';
const {test,before,after}=require('node:test'),assert=require('node:assert/strict');const {setup,seed,actor,uuid,guard}=require('./bloc5-fixture.cjs');let db,beforeFunctions,afterFunctions,beforeBusiness,orphanRemittance;let nonce=900;
const rpc=async(name,args)=>(await db.query(`select to_jsonb(public.${name}(${args.map((_,i)=>'$'+(i+1)).join(',')})) result`,args)).rows[0].result;
const page=(filters={},after=null,limit=25)=>rpc('control_finance_page_v1',[filters,after,limit]);const context=(type,n)=>rpc('control_finance_context_v1',[type,typeof n==='number'?uuid(n):n,null,25]);
const funcs=`select n.nspname,p.proname,pg_get_function_identity_arguments(p.oid) args,pg_get_userbyid(p.proowner) owner,p.prosecdef,p.proconfig,p.proacl::text acl,md5(pg_get_functiondef(p.oid)) hash from pg_proc p join pg_namespace n on n.oid=p.pronamespace where n.nspname in('public','fixeo_private') order by n.nspname,p.proname,args`;
const business=async()=>(await db.query(`select jsonb_build_object('missions',(select jsonb_agg(to_jsonb(m) order by id) from public.missions m),'requests',(select jsonb_agg(to_jsonb(r) order by id) from public.service_requests r),'ledger',(select jsonb_agg(to_jsonb(x) order by id) from public.commission_remittances_v1 x)) j`)).rows[0].j;
const preview=(cap,n,payload)=>rpc('control_action_preview_v1',[cap,uuid(n),{reason:'Synthetic finance evidence',...payload},uuid(++nonce)]);const execute=(p,k=uuid(++nonce))=>rpc('control_action_execute_v1',[p.preview_id,true,k]);
const declare=async(n=200,amount=10)=>execute(await preview('finance.declare',n,{amount,method:'cash',proof_reference:'SYNTHETIC-PROOF'}));
before(async()=>{db=await setup({financeGuard:false});await seed(db);await db.exec(`INSERT INTO public.service_requests(id,client_profile_id,city,service_category,description,status) VALUES('${uuid(100)}','${uuid(1)}','Fès','plomberie','Synthetic valid financial case','completed'),('${uuid(101)}','${uuid(1)}','Fès','plomberie','Synthetic engagement','assigned'),('${uuid(102)}','${uuid(1)}','Fès','plomberie','Synthetic price missing','completed'),('${uuid(103)}','${uuid(1)}','Fès','plomberie','Synthetic removed parent','completed');INSERT INTO public.missions(id,request_id,artisan_profile_id,status,completed_at,agreed_price,accepted_at) VALUES('${uuid(200)}','${uuid(100)}','${uuid(20)}','done',now(),1000,now()),('${uuid(201)}','${uuid(101)}','${uuid(20)}','pending',NULL,1000,now()),('${uuid(202)}','${uuid(102)}','${uuid(20)}','done',now(),1000,now()),('${uuid(203)}','${uuid(103)}','${uuid(20)}','done',now(),1000,now());SELECT public.admin_settle_mission_v1('${uuid(200)}',1000,NULL,'Synthetic valid settlement');SELECT public.admin_settle_mission_v1('${uuid(203)}',1000,NULL,'Synthetic valid settlement');INSERT INTO public.payments(mission_id,amount,status) VALUES('${uuid(200)}',800,'paid');`);
 orphanRemittance=(await rpc('admin_commission_remittance_v1',[uuid(203),'declare',null,null,10,'cash','SYNTHETIC-OLD-PROOF','Synthetic historical declaration'])).id;await db.exec(`DELETE FROM public.service_requests WHERE id='${uuid(103)}'`);
 beforeFunctions=(await db.query(funcs)).rows;beforeBusiness=await business();await db.exec(guard);afterFunctions=(await db.query(funcs)).rows;
});after(async()=>db?.close());
function tx(name,fn){test(name,async()=>{await db.exec('RESET ROLE;BEGIN');try{await fn();}finally{await db.exec('ROLLBACK;RESET ROLE');}});}
async function denied(fn,re){await db.exec('SAVEPOINT refusal');let e;try{await fn();}catch(x){e=x;}await db.exec('ROLLBACK TO SAVEPOINT refusal;RELEASE SAVEPOINT refusal');assert.ok(e,'Expected refusal');assert.match(e.message,re);}
tx('5.4 Finance guard changes exactly two bodies; owner/SD/search_path/ACL and business rows stay intact',async()=>{const changed=[];for(let i=0;i<beforeFunctions.length;i++){const {hash:a,...left}=beforeFunctions[i],{hash:b,...right}=afterFunctions[i];assert.deepEqual(left,right);if(a!==b)changed.push(left.proname);}assert.deepEqual(changed.sort(),['admin_commission_remittance_v1','control_action_preview_v1']);assert.deepEqual(await business(),beforeBusiness);assert.equal(afterFunctions.find(f=>f.proname==='admin_settle_mission_v1').hash,'c65636d6c39bc43e91818dc10f9f00fd');});
tx('5.4 Missing parent declaration/confirmation/correction are rejected by authority and preview before any write (former defect)',async()=>{for(let retry=0;retry<3;retry++){for(const op of ['declare','confirm','correct']){await denied(()=>rpc('admin_commission_remittance_v1',[uuid(203),op,orphanRemittance,1,10,'cash','SYNTHETIC PROOF','Synthetic invalid request']),/REQUEST_NOT_FOUND/);await actor(db,3);await denied(()=>preview('finance.'+op,203,op==='declare'?{amount:10,method:'cash',proof_reference:'SYNTHETIC PROOF'}:op==='correct'?{remittance_id:orphanRemittance,version:1,amount:10,method:'cash',proof_reference:'SYNTHETIC PROOF'}:{remittance_id:orphanRemittance,version:1}),/REQUEST_NOT_FOUND/);await db.exec('RESET ROLE');}}assert.deepEqual(await business(),beforeBusiness);assert.equal((await db.query('select count(*) n from fixeo_private.control_action_previews_v1')).rows[0].n,0);});
tx('5.4 P0 settlement remains a server refusal for the orphan, with no financial or mission mutation',async()=>{await denied(()=>rpc('admin_settle_mission_v1',[uuid(203),900,1000,'Synthetic invalid settlement']),/REQUEST_NOT_FOUND/);await actor(db,3);await denied(()=>preview('mission.settle',203,{final_price:900,expected_final_price:1000}),/REQUEST_NOT_FOUND/);await db.exec('RESET ROLE');assert.deepEqual(await business(),beforeBusiness);});
tx('5.4 Financial readers are Admin only; direct mutation authorities and ledger writes remain sealed',async()=>{for(const [n,r] of [[1,'anon'],[1,'authenticated'],[4,'authenticated'],[3,'service_role']]){await actor(db,n,r);await denied(()=>page(),/FORBIDDEN|permission denied/);await denied(()=>context('mission',200),/FORBIDDEN|permission denied/);}await actor(db,3);await denied(()=>rpc('admin_commission_remittance_v1',[uuid(200),'declare',null,null,10,'cash','proof','reviewed']),/permission denied/);await denied(()=>db.query('update public.commission_remittances_v1 set amount=1'),/permission denied/);});
tx('5.4 Missing request remains UNKNOWN; payments are not commissions and no zero balance is invented',async()=>{await actor(db,3);const p=await page();assert.equal(p.total,4);assert.equal(p.metrics.due,null);assert.equal(p.metrics.unknown_cases,1);const o=p.items.find(x=>x.id===uuid(203));assert.equal(o.facts.request_relation,'NOT_FOUND');assert.equal(o.facts.finance_state,'UNKNOWN');assert.equal(o.facts.due_balance,null);assert.equal(o.facts.can_reconcile,false);const f=(await context('mission',200)).facts;assert.equal(f.payments_count,1);assert.equal(f.confirmed_recorded,0);assert.match(f.payments_nature,/UNKNOWN/);assert.ok(f.due_gross>0);assert.equal((await page({queue:'price_required'})).total,1);assert.equal((await page({queue:'expected'})).total,1);});
tx('5.4 Declare, confirm and same-key replay preserve one ledger entry, audit and exact balance',async()=>{await actor(db,3);const d=await declare();assert.equal(d.ok,true);const p=await preview('finance.confirm',200,{remittance_id:d.result.id,version:1}),key=uuid(++nonce),c=await execute(p,key);assert.equal(c.ok,true);assert.deepEqual(await execute(p,key),c);const x=await context('remittance',d.result.id);assert.equal(x.selected.status,'confirmed');assert.equal(x.selected.proof_reference,'SYNTHETIC-PROOF');assert.equal(x.remittance_total,1);assert.equal(x.facts.confirmed_recorded,10);assert.equal(x.facts.due_balance,x.facts.due_gross-10);assert.ok(c.audit_id);const h=await rpc('control_review_history_v1',['remittance',d.result.id,null,25]);assert.equal(h.items.length,2);assert.ok(h.items.every(a=>a.reason==='Synthetic finance evidence'));assert.ok(!JSON.stringify(h).includes('SYNTHETIC-PROOF'));});
tx('5.4 Correction cancels and versions the original, appends replacement and retains attribution and proof',async()=>{await actor(db,3);const d=await declare(),c=await execute(await preview('finance.correct',200,{remittance_id:d.result.id,version:1,amount:9,method:'bank_transfer',proof_reference:'SYNTHETIC-CORRECTION'}));assert.equal(c.ok,true);assert.notEqual(c.result.id,d.result.id);const x=await context('mission',200);assert.equal(x.remittance_total,2);const old=x.remittances.find(a=>a.id===d.result.id),next=x.remittances.find(a=>a.id===c.result.id);assert.equal(old.status,'cancelled');assert.equal(old.version,2);assert.equal(old.amount,10);assert.equal(old.proof_reference,'SYNTHETIC-PROOF');assert.equal(next.supersedes_id,old.id);assert.equal(next.declared_by,uuid(3));assert.equal(next.amount,9);});
tx('5.4 Invalid correction rolls back cancellation and leaves no partial replacement or financial write',async()=>{await actor(db,3);const d=await declare();const p=await preview('finance.correct',200,{remittance_id:d.result.id,version:1,amount:9,method:'cash',proof_reference:'x'});const r=await execute(p);assert.equal(r.ok,false);assert.equal(r.code,'INVALID_PROOF_OR_AMOUNT');const c=await context('mission',200);assert.equal(c.remittance_total,1);assert.equal(c.remittances[0].status,'declared');assert.equal(c.remittances[0].version,1);});
tx('5.4 Cancellation preserves ledger history and replay while preventing stale confirmation',async()=>{await actor(db,3);const d=await declare(),stale=await preview('finance.confirm',200,{remittance_id:d.result.id,version:1}),cancel=await preview('finance.cancel',200,{remittance_id:d.result.id,version:1});const k=uuid(++nonce),r=await execute(cancel,k);assert.equal(r.ok,true);assert.deepEqual(await execute(cancel,k),r);const rejected=await execute(stale);assert.equal(rejected.ok,false);assert.match(rejected.code,/STALE_VERSION|REMITTANCE_CANCELLED/);assert.equal((await context('remittance',d.result.id)).selected.status,'cancelled');});
tx('5.4 Tenant/site mismatch, closed filters and cursor substitution are refused',async()=>{await actor(db,3);await denied(()=>page({enterprise_id:uuid(30),site_id:uuid(41)}),/FORBIDDEN/);await denied(()=>page({queue:'private_finance'}),/INVALID_FILTER/);const p=await page({},null,1);await denied(()=>page({queue:'due'},p.next_cursor),/INVALID_CURSOR/);await denied(()=>context('payments',200),/INVALID_FILTER/);});
