'use strict';
const {test,before,after}=require('node:test'),assert=require('node:assert/strict'),F=require('./bloc7-fixture.cjs'),u=F.uuid;let db;
before(async()=>{db=await F.setup();await F.seed(db);});after(async()=>db?.close());
const rpc=async(n,args)=>(await db.query(`SELECT public.${n}(${args.map((_,i)=>'$'+(i+1)).join(',')}) result`,args)).rows[0].result;
const tx=(name,fn)=>test(name,async()=>{await db.exec('BEGIN');try{await fn();}finally{await db.exec('ROLLBACK');}});
async function denied(fn,pattern){await db.exec('SAVEPOINT denied');let err;try{await fn();}catch(e){err=e;}await db.exec('ROLLBACK TO SAVEPOINT denied');assert.ok(err,'Unexpected success');assert.match(err.message,pattern);}
async function claim(){await db.exec(`RESET ROLE;INSERT INTO public.claim_requests(id,artisan_id,requester_user_id,requester_name) VALUES('${u(80)}','${u(21)}','${u(6)}','Synthetic claimant');`);await F.actor(db,3);return(await rpc('control_rafi_source_v3',['trust','all'])).observations.find(o=>o.kind==='claim.pending').proof;}
const propose=p=>rpc('control_rafi_proposal_v3',[p,'claim.pending','claim.reject',u(80),{reason:'Synthetic explicit review'},u(900)]);
tx('7.3 Source wrapper preserves canonical observations and adds stable verifiable evidence receipts',async()=>{const p=await claim();const old=await rpc('control_rafi_source_v1',['trust','all']),fresh=await rpc('control_rafi_source_v3',['trust','all']);assert.deepEqual(fresh.observations.map(({proof,...o})=>o),old.observations);assert.match(p.ref,/^obs_[a-f0-9]{32}$/);assert.match(p.token,/^[a-f0-9]{32}$/);assert.equal(fresh.evidence_contract,'rafi-evidence-v3');});
tx('7.3 Canonical preview and confirmation produce verified audited result; retry has one business effect',async()=>{const p=await claim(),x=await propose(p);assert.equal(x.kind,'ActionProposal');assert.equal(x.requires_confirmation,true);await denied(()=>rpc('control_rafi_execute_v3',[x.preview_id,false,u(901)]),/HUMAN_CONFIRMATION_REQUIRED/);const a=await rpc('control_rafi_execute_v3',[x.preview_id,true,u(901)]),b=await rpc('control_rafi_execute_v3',[x.preview_id,true,u(901)]);assert.equal(a.ok,true);assert.deepEqual(a,b);assert.equal(a.verified.id,u(80));assert.equal(a.evidence_ref,p.ref);await db.exec('RESET ROLE');assert.equal((await db.query(`SELECT status FROM public.claim_requests WHERE id='${u(80)}'`)).rows[0].status,'rejected');const audits=(await db.query(`SELECT count(*)::int n FROM fixeo_private.authority_audit_events_v1 WHERE target_id='${u(80)}' AND action='execute'`)).rows;assert.equal(audits[0].n,1);});
tx('7.3 Changed canonical evidence between preview and confirmation refuses without business writes',async()=>{const p=await claim(),x=await propose(p);await db.exec(`RESET ROLE;UPDATE public.claim_requests SET status='approved' WHERE id='${u(80)}';`);await F.actor(db,3);const r=await rpc('control_rafi_execute_v3',[x.preview_id,true,u(902)]);assert.equal(r.ok,false);assert.equal(r.code,'EVIDENCE_NOT_OBSERVED');assert.ok(r.audit_id);await db.exec('RESET ROLE');assert.equal((await db.query(`SELECT status FROM public.claim_requests WHERE id='${u(80)}'`)).rows[0].status,'approved');});
tx('7.3 Expired evidence, altered token, wrong target and unsupported authority are rejected',async()=>{const p=await claim();await denied(()=>propose({...p,observed_at:'2020-01-01T00:00Z',valid_until:'2020-01-01T00:01Z'}),/STALE_EVIDENCE/);await denied(()=>propose({...p,token:'0'.repeat(32)}),/EVIDENCE_CHANGED/);await denied(()=>rpc('control_rafi_proposal_v3',[p,'claim.pending','claim.reject',u(81),{reason:'Synthetic'},u(903)]),/INVALID_PROPOSAL_TARGET/);await denied(()=>rpc('control_rafi_proposal_v3',[p,'claim.pending','mission.settle',u(80),{final_price:10,reason:'Synthetic'},u(904)]),/PROPOSAL_NOT_ADMISSIBLE/);const x=await propose(p);await db.exec(`RESET ROLE;UPDATE fixeo_private.rafi_proposals_v3 SET expires_at=now()-interval '1 second' WHERE preview_id='${x.preview_id}';`);await F.actor(db,3);assert.equal((await rpc('control_rafi_execute_v3',[x.preview_id,true,u(905)])).code,'STALE_EVIDENCE');assert.equal((await rpc('control_action_execute_v1',[x.preview_id,true,u(905)])).code,'STALE_EVIDENCE');});
tx('7.3 Nonadmin, two tenants, anon and service role cannot read proofs or prepare/execute proposals',async()=>{const p=await claim(),x=await propose(p);for(const [n,role] of [[1,'authenticated'],[2,'authenticated'],[4,'authenticated'],[5,'authenticated'],[3,'anon'],[3,'service_role']]){await F.actor(db,n,role);for(const fn of [()=>rpc('control_rafi_source_v3',['trust','all']),()=>propose(p),()=>rpc('control_rafi_execute_v3',[x.preview_id,true,u(906)])])await denied(fn,/FORBIDDEN|permission denied/);}});
tx('7.3 Another Admin cannot execute a different operator proposal',async()=>{const p=await claim(),x=await propose(p);await db.exec(`RESET ROLE;UPDATE public.users SET role='admin' WHERE id='${u(7)}';`);await F.actor(db,7);await denied(()=>rpc('control_rafi_execute_v3',[x.preview_id,true,u(907)]),/PROPOSAL_NOT_FOUND/);});
