'use strict';
const {test,before,after}=require('node:test'),assert=require('node:assert/strict'),F=require('./bloc7-fixture.cjs'),u=F.uuid;let db;
before(async()=>{db=await F.setup();await F.seed(db);});after(async()=>db?.close());
const rpc=async(n,args)=>(await db.query(`SELECT public.${n}(${args.map((_,i)=>'$'+(i+1)).join(',')}) result`,args)).rows[0].result;
const tx=(name,fn)=>test(name,async()=>{await db.exec('BEGIN');try{await fn();}finally{await db.exec('ROLLBACK');}});
async function denied(fn,pattern){await db.exec('SAVEPOINT deny');let err;try{await fn();}catch(e){err=e;}await db.exec('ROLLBACK TO SAVEPOINT deny');assert.ok(err);assert.match(err.message,pattern);}
const due=()=>new Date(Date.now()+3600000).toISOString();
async function seed(){await db.exec(`RESET ROLE;INSERT INTO public.claim_requests(id,artisan_id,requester_user_id,requester_name) VALUES('${u(80)}','${u(21)}','${u(6)}','Synthetic claimant');`);await F.actor(db,3);return(await rpc('control_rafi_source_v3',['trust','all'])).observations.find(o=>o.kind==='claim.pending').proof;}
const write=(op,id,version,proof,rule,at,audit,key)=>rpc('control_rafi_followup_v3',[op,id,version,proof,rule,at,audit,key]);
tx('7.4 Explicit followup creation is idempotent and pure reads neither persist nor resolve anything',async()=>{const p=await seed(),at=due(),args=['create',null,null,p,'claim.pending',at,null,u(901)];const a=await write(...args),b=await write(...args);assert.deepEqual(a,b);assert.equal(a.followup.status,'open');const list=await rpc('control_rafi_followups_v3',[null,1]);assert.equal(list.items.length,1);assert.equal(list.items[0].delta,'UNCHANGED');assert.equal(list.source_reads,1);const again=await rpc('control_rafi_followups_v3',[null,1]);assert.deepEqual(list,again);await db.exec('RESET ROLE');assert.equal((await db.query(`SELECT status FROM public.claim_requests WHERE id='${u(80)}'`)).rows[0].status,'pending');assert.equal((await db.query('SELECT count(*)::int n FROM fixeo_private.rafi_followups_v3')).rows[0].n,1);});
tx('7.4 Acknowledgement and rescheduling change operator metadata only and require exact version',async()=>{const p=await seed(),f=(await write('create',null,null,p,'claim.pending',due(),null,u(902))).followup;const a=await write('acknowledge',f.id,1,null,null,null,null,u(903));assert.equal(a.followup.status,'acknowledged');assert.equal(a.followup.version,2);await denied(()=>write('reschedule',f.id,1,null,null,due(),null,u(904)),/STALE_FOLLOWUP/);await denied(()=>write('acknowledge',f.id,1,null,null,null,null,u(902)),/IDEMPOTENCY_CONFLICT/);const next=await write('reschedule',f.id,2,null,null,due(),null,u(905));assert.equal(next.followup.version,3);});
tx('7.4 Missing/deleted evidence stays UNKNOWN and cannot close a followup',async()=>{const p=await seed(),f=(await write('create',null,null,p,'claim.pending',due(),null,u(906))).followup;await db.exec(`RESET ROLE;DELETE FROM public.claim_requests WHERE id='${u(80)}';`);await F.actor(db,3);const x=await rpc('control_rafi_followups_v3',[null,25]);assert.equal(x.items[0].status,'open');assert.equal(x.items[0].delta,'UNKNOWN');await denied(()=>write('resolve',f.id,1,null,null,null,null,u(907)),/CANONICAL_RESOLUTION_PROOF_REQUIRED/);});
tx('7.4 Resolution needs a successful canonical event plus compatible current state; retry preserves audit',async()=>{const p=await seed(),f=(await write('create',null,null,p,'claim.pending',due(),null,u(908))).followup;await denied(()=>write('resolve',f.id,1,null,null,null,f.last_audit_id,u(909)),/CANONICAL_RESOLUTION_PROOF_REQUIRED/);const preview=await rpc('control_rafi_proposal_v3',[p,'claim.pending','claim.reject',u(80),{reason:'Synthetic review'},u(910)]),result=await rpc('control_rafi_execute_v3',[preview.preview_id,true,u(911)]);assert.equal(result.ok,true);const evidence=await rpc('control_rafi_followup_evidence_v3',[f.id]);assert.ok(evidence.candidates.some(e=>e.id===result.audit_id));const args=['resolve',f.id,1,null,null,null,result.audit_id,u(912)];const a=await write(...args),b=await write(...args);assert.deepEqual(a,b);assert.equal(a.followup.status,'resolved');assert.equal(a.followup.resolution_audit_id,result.audit_id);});
tx('7.4 A valid but unrelated event or an active business state cannot prove resolution',async()=>{const p=await seed(),f=(await write('create',null,null,p,'claim.pending',due(),null,u(913))).followup;await db.exec('RESET ROLE');const audit=(await db.query(`SELECT fixeo_private.authority_audit_v1('claim','${u(80)}','Test isolated canonical event','review','succeeded') id`)).rows[0].id;await F.actor(db,3);await denied(()=>write('resolve',f.id,1,null,null,null,audit,u(914)),/RESOLUTION_NOT_PROVEN/);});
tx('7.4 Two operator owners and tenants are isolated; private storage grants stay sealed',async()=>{const p=await seed(),f=(await write('create',null,null,p,'claim.pending',due(),null,u(915))).followup;await db.exec(`RESET ROLE;UPDATE public.users SET role='admin' WHERE id='${u(7)}';`);await F.actor(db,7);assert.equal((await rpc('control_rafi_followups_v3',[null,25])).total,0);await denied(()=>write('acknowledge',f.id,1,null,null,null,null,u(916)),/FOLLOWUP_NOT_FOUND/);await denied(()=>rpc('control_rafi_followup_evidence_v3',[f.id]),/FOLLOWUP_NOT_FOUND/);for(const n of [1,2,4,5]){await F.actor(db,n);await denied(()=>rpc('control_rafi_followups_v3',[null,25]),/FORBIDDEN/);await denied(()=>write('create',null,null,p,'claim.pending',due(),null,u(917)),/FORBIDDEN/);}await F.actor(db,3);await denied(()=>db.query('SELECT * FROM fixeo_private.rafi_followups_v3'),/permission denied/);});
