'use strict';
const {test}=require('node:test'),assert=require('node:assert/strict'),B=require('../../api/control/rafi-briefing'),{createHandler}=require('../../api/control');
const uid='00000000-0000-4000-8000-000000000003',now=new Date().toISOString();
const decision=n=>({decision_id:'rafi_'+n,signal_id:'rafi_'+n,priority:'P1',title:'Priorité '+n,reason:['Fait sourcé'],evidence_refs:[{evidence_id:'ev_'+n}],impact:{kind:'INFERENCE',text:'Impact possible'},recommendation:{action_id:'dossier.open'},expires_at:now});
const snap={status:'FRESH',generated_at:now,decisions:Array.from({length:20},(_,i)=>decision(i)),sources:{operations:{status:'FRESH'}}};
const env={SUPABASE_URL:'https://abcdefghijklmnopqrst.supabase.co',SUPABASE_ANON_KEY:'sb_publishable_SYNTHETIC',FIXEO_STAGING_PROJECT_REF:'abcdefghijklmnopqrst',VERCEL_ENV:'preview',VERCEL_URL:'test.vercel.app'};
const reply=(data,status=200)=>({ok:status<400,status,text:async()=>JSON.stringify(data)});
test('7.2 Briefing limits five priorities and exposes unverified sources without healthy-zero claims',()=>{const b=B.briefing({...snap,status:'PARTIAL',sources:{operations:{status:'FRESH'},finance:{status:'UNAVAILABLE',error:'SOURCE_TIMEOUT'}}});assert.equal(b.priorities.length,5);assert.equal(b.unverified[0].source,'finance');assert.match(b.message,/partielle/);assert.equal(b.execution_authorized,false);assert.equal(b.llm_required,false);});
test('7.2 Dossier context retains canonical lifecycle distinctions, nulls and excludes private text',()=>{const c=B.context({entity_type:'mission',id:uid,as_of:now,provenance:'public.missions',summary:{id:uid,status:'done',request_status:null,final_price:null,description:'PRIVATE',business_profit:999,urgency:'urgent'}},{decisions:[]});assert.deepEqual(c.missing,['request_status','final_price']);assert.ok(!JSON.stringify(c).includes('PRIVATE'));assert.equal(c.facts.find(f=>f.field==='urgency').provenance,'USER_DECLARED');assert.equal(c.execution_authorized,false);});
test('7.2 Missing/disabled model and incomplete evidence never call provider and keep deterministic briefing',async()=>{for(const config of [{}, {FIXEO_ADMIN_RAFI_AI_ENABLED:'1'}, {FIXEO_ADMIN_RAFI_AI_ENABLED:'1',OPENAI_API_KEY:'synthetic',FIXEO_ADMIN_RAFI_MODEL:'synthetic'}]){const b=B.briefing({...snap,status:'PARTIAL'});const r=await B.synthesis(b,{env:config,fetchImpl:()=>{throw Error('Unexpected call');}});assert.equal(r.status,'DETERMINISTIC');assert.equal(r.sentences.length,3);}});
const configured={FIXEO_ADMIN_RAFI_AI_ENABLED:'1',FIXEO_ADMIN_RAFI_MODEL:'synthetic',OPENAI_API_KEY:'SYNTHETIC_NEVER_REAL'};
test('7.2 Optional model selects grounded sentences without creating text or changing priority',async()=>{const b=B.briefing(snap);let sent;const r=await B.synthesis(b,{env:configured,fetchImpl:async(url,o)=>{assert.equal(url,'https://api.openai.com/v1/responses');sent=JSON.parse(o.body);assert.equal(sent.store,false);assert.ok(o.signal);return reply({status:'completed',output:[{content:[{type:'output_text',text:JSON.stringify({sentence_ids:['rafi_0:title','rafi_1:reason0']})}]}]});}});assert.equal(r.status,'GROUNDED_SELECTION');assert.equal(r.sentences[0].text,'Priorité 0');assert.equal(sent.max_output_tokens,300);assert.equal(r.execution_authorized,false);});
test('7.2 Prompt injection, forged evidence/action IDs, oversized output and provider failure fall back',async()=>{const outputs=[{sentence_ids:['forged']},{sentence_ids:['rafi_0:title'],action:'UPDATE missions'},{sentence_ids:['rafi_0:title','rafi_0:title']},{sentence_ids:[]}];for(const output of outputs){const r=await B.synthesis(B.briefing(snap),{env:configured,fetchImpl:async()=>reply({status:'completed',output:[{content:[{type:'output_text',text:JSON.stringify(output)}]}]})});assert.equal(r.status,'DETERMINISTIC');}for(const fetchImpl of [async()=>{throw Error('TimeoutError');},async()=>reply({},429),async()=>({ok:true,text:async()=>'x'.repeat(40000)})])assert.equal((await B.synthesis(B.briefing(snap),{env:configured,fetchImpl})).status,'DETERMINISTIC');});
test('7.2 Admin synthesis endpoint authenticates and uses only five bounded canonical readers',async()=>{let calls=0;const res={setHeader(){},status(n){this.statusCode=n;return this;},json(x){this.body=x;return this;}};await createHandler({env,fetchImpl:async(url,o)=>{calls++;if(url.endsWith('/user'))return reply({id:uid});const source=JSON.parse(o.body).p_source;return reply({contract_version:'rafi-observations-v1',source,as_of:now,observations:[],total_observations:0,has_more:false});}})({method:'POST',url:'/api/control-v1/rafi-synthesis',headers:{authorization:'Bearer synthetic.not_a_real_token'},body:{}},res);assert.equal(res.statusCode,200);assert.equal(calls,6);assert.equal(res.body.synthesis.status,'DETERMINISTIC');assert.equal(res.body.briefing.priorities.length,0);});

test('7.2 Workforce capacity evidence stays in authorized bounded context and never authorizes assignment',()=>{const h={as_of:new Date().toISOString(),enterprise_id:uid,site_id:uid,workers_has_more:true,source:'Canonical B4 workforce',workers:[{id:uid,site_match:true,skill_match:true,reasons:['capacity_full'],active_assignments:2,max_concurrent_jobs:2,availability:'available',eligible:false}]};const x=B.workforce(h);assert.equal(x.status,'PARTIAL');assert.equal(x.signals.length,1);assert.equal(x.signals[0].execution_authorized,false);assert.equal(x.global_population,'UNKNOWN');assert.equal(B.workforce({...h,workers:[{...h.workers[0],site_match:false}]}).signals.length,0);assert.equal(B.workforce({...h,as_of:'2020-01-01'}).signals[0].state,'unknown');});
