'use strict';
const {test,before,after}=require('node:test'),assert=require('node:assert/strict');const {setup,seed,actor,uuid}=require('./bloc5-fixture.cjs');let db,qid;let nonce=400;
const rpc=async(name,args)=>(await db.query(`select to_jsonb(public.${name}(${args.map((_,i)=>'$'+(i+1)).join(',')})) result`,args)).rows[0].result;
const page=(filters={},after=null,limit=25)=>rpc('control_quotes_page_v1',[filters,after,limit]);const context=(type,id)=>rpc('control_quote_context_v1',[type,id]);
before(async()=>{db=await setup();await seed(db);await db.exec(`INSERT INTO public.service_requests(id,client_profile_id,city,service_category,description,status,idempotency_key) VALUES('${uuid(100)}','${uuid(1)}','Fès','plomberie','Synthetic request','new','synthetic:100'),('${uuid(101)}','${uuid(1)}','Fès','plomberie','QUOTE_REQUIRED text alone is not proof','new','synthetic:101'),('${uuid(102)}','${uuid(1)}','Fès','plomberie','Synthetic proven quote request','new','diagnostic-quote:${uuid(500)}');INSERT INTO fixeo_private.diagnostic_sessions_v1(id,owner_user_id,owner_key,state,city_slug,input,consent_version,service_request_id,booking_context) VALUES('${uuid(500)}','${uuid(1)}','u:${uuid(1)}','bound','fes','{"private":"DO NOT EXPOSE INPUT"}','diagnostic-privacy-v1','${uuid(102)}','{"kind":"quote","private":"DO NOT EXPOSE BOOKING"}');`);await actor(db,2);qid=(await rpc('submit_artisan_quote_v2',[uuid(100),1000,'Synthetic repair scope','Synthetic supplies','1 hour',null])).id;await db.exec('RESET ROLE');});after(async()=>db?.close());
function tx(name,fn){test(name,async()=>{await db.exec('RESET ROLE;BEGIN');try{await fn();}finally{await db.exec('ROLLBACK;RESET ROLE');}});}
async function denied(fn,re){await db.exec('SAVEPOINT refusal');let e;try{await fn();}catch(x){e=x;}await db.exec('ROLLBACK TO SAVEPOINT refusal;RELEASE SAVEPOINT refusal');assert.ok(e);assert.match(e.message,re);}
const preview=(cap,payload)=>rpc('control_action_preview_v1',[cap,qid,{reason:'Synthetic review',...payload},uuid(++nonce)]);const execute=p=>rpc('control_action_execute_v1',[p.preview_id,true,uuid(++nonce)]);
tx('5.3 Quote registers and context are Admin only, not tenant-member or service-role grants',async()=>{for(const [n,r] of [[1,'anon'],[1,'authenticated'],[4,'authenticated'],[3,'service_role']]){await actor(db,n,r);await denied(()=>page(),/FORBIDDEN|permission denied/);await denied(()=>context('quote',qid),/FORBIDDEN|permission denied/);}});
tx('5.3 No quote, matching description and no price are insufficient for QUOTE_REQUIRED',async()=>{await actor(db,3);const a=await page({queue:'quote_required'}),b=await page({queue:'unqualified'});assert.equal(a.total,1);assert.equal(a.items[0].id,uuid(102));assert.equal(b.total,1);assert.equal(b.items[0].id,uuid(101));const c=await context('request',uuid(101));assert.equal(c.facts.requirement.state,'UNKNOWN');const d=await context('request',uuid(102));assert.equal(d.facts.requirement.authority,'create_diagnostic_quote_request_v1');assert.equal(d.facts.requirement.session_id,uuid(500));assert.ok(!JSON.stringify(d).includes('DO NOT EXPOSE'));});
tx('5.3 Queue and exact filtered metrics reflect submitted state without making it client-visible',async()=>{await actor(db,3);const p=await page({queue:'review',city:'Fès'});assert.equal(p.total,1);assert.equal(p.items[0].id,qid);assert.equal(p.items[0].facts.pipeline,'FIXEO_REVIEW');assert.equal(p.metrics.quotes,1);assert.equal(p.metrics.quote_required,1);await actor(db,1);assert.equal((await db.query('select id from public.quotes where id=$1',[qid])).rows.length,0);await denied(()=>rpc('accept_quote_v2',[qid]),/FIXEO_REVIEW_REQUIRED/);});
tx('5.3 Exact version review creates canonical presentation, reason and audit, then client acceptance links a real mission',async()=>{await actor(db,3);const p=await preview('quote.approve',{version:1,expires_at:new Date(Date.now()+3600000).toISOString()}),r=await execute(p);assert.equal(r.ok,true);assert.ok(r.audit_id);assert.equal((await page({queue:'presented'})).total,1);const c=await context('quote',qid);assert.equal(c.facts.review_reason,'Synthetic review');assert.equal(c.facts.reviewed_version,1);assert.equal(c.accepted_missions.length,0);await actor(db,1);const m=await rpc('accept_quote_v2',[qid]);assert.equal((await rpc('accept_quote_v2',[qid])).id,m.id);await actor(db,3);assert.equal((await page({queue:'accepted'})).items[0].id,qid);assert.equal((await context('quote',qid)).accepted_missions[0].id,m.id);});
tx('5.3 Quote revision after preview invalidates review, preserving client and notification gates',async()=>{await actor(db,3);const p=await preview('quote.approve',{version:1});await actor(db,2);await rpc('submit_artisan_quote_v2',[uuid(100),1100,'Changed synthetic scope',null,null,null]);await actor(db,3);const r=await execute(p);assert.equal(r.ok,false);assert.match(r.code,/STALE/);assert.equal((await page({queue:'presented'})).total,0);const c=await context('quote',qid);assert.equal(c.facts.reviewed_version,null);await actor(db,1);await denied(()=>rpc('accept_quote_v2',[qid]),/FIXEO_REVIEW_REQUIRED/);});
tx('5.3 Approved expiry stays explicit and blocks client acceptance without rewriting quote state',async()=>{await actor(db,3);assert.equal((await execute(await preview('quote.approve',{version:1}))).ok,true);await db.exec('RESET ROLE');await db.query('update public.quotes set expires_at=now()-interval \'1 second\' where id=$1',[qid]);await actor(db,3);assert.equal((await page({queue:'expired'})).total,1);assert.equal((await context('quote',qid)).facts.expiration_state,'EXPIRED');await actor(db,1);await denied(()=>rpc('accept_quote_v2',[qid]),/QUOTE_EXPIRED/);});
tx('5.3 Legacy accepted quote without versioned mission stays a readable unresolved relation',async()=>{await db.exec(`INSERT INTO public.quotes(id,request_id,artisan_profile_id,proposed_price,status,review_status) VALUES('${uuid(600)}','${uuid(101)}','${uuid(20)}',1000,'accepted','legacy_unreviewed')`);await actor(db,3);const p=await page({queue:'accepted'});assert.equal(p.total,1);assert.equal((await context('quote',uuid(600))).accepted_missions.length,0);await actor(db,1);await denied(()=>rpc('accept_quote_v2',[uuid(600)]),/LEGACY_RECONCILIATION_REQUIRED/);});
tx('5.3 Invalid stages, cursor scope and private entity requests are refused',async()=>{await actor(db,3);await denied(()=>page({queue:'personal_quotes'}),/INVALID_FILTER/);await denied(()=>context('personal_quote',qid),/INVALID_FILTER/);await denied(()=>page({}, {scope:'wrong',key:'quote:'+qid}),/INVALID_CURSOR/);assert.equal((await page({city:'No such city'})).metrics.quotes,0);});
