'use strict';
const {test}=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),{JSDOM}=require('jsdom');
const root=path.resolve(__dirname,'../..'),id='00000000-0000-4000-8000-000000000100',tick=()=>new Promise(r=>setImmediate(r));
const response=()=>({status:'FRESH',generated_at:new Date().toISOString(),scope:{from:'2026-09-01',to:'2026-09-15',timezone:'Africa/Casablanca'},total_cells:1,has_more:false,sources:{operations:{status:'FRESH'},network:{status:'UNAVAILABLE',error:'SOURCE_TIMEOUT'},commerce:{status:'FRESH'}},unattributed_missions:19,cells:[{key:'x',city:'<img src=x>',trade:'plomberie',operations:{waiting:3,open:4,cohort_requests:5},network:null,commerce:{quotes_presented:0,quotes_review:0,quotes_expired:0}}]});
function page(override){const dom=new JSDOM('<section id="sec-intelligence"></section>',{url:'https://fixeo.ma/admin.html?view=intelligence',runScripts:'outside-only'}),w=dom.window,calls=[],opened=[];w.FixeoControl={request:async(op,b)=>{calls.push({op,b});const r=override?.(op,b);if(r!==undefined)return r;if(op==='marketplace')return response();if(op==='marketplace-population')return {items:[{type:'request',id,facts:{status:'new',raw_city:'Fès'}}],total:1,as_of:new Date().toISOString(),has_more:false};throw Error('UNEXPECTED');}};w.FixeoDossier={open:(...args)=>opened.push(args)};w.eval(fs.readFileSync(path.join(root,'js/admin-fixeo-intelligence.js'),'utf8'));return {w,calls,opened,close:()=>dom.window.close()};}
test('6.1 Cube UI escapes dimensions, distinguishes stock/cohort and keeps failed network unknown',async()=>{const p=page();try{await p.w.FixeoIntelligence.refresh();assert.equal(p.w.document.querySelector('img'),null);assert.match(p.w.document.getElementById('intel-cells').textContent,/UNKNOWN profils/);assert.match(p.w.document.getElementById('intel-sources').textContent,/SOURCE_TIMEOUT/);p.w.document.querySelector('[data-intel-cell]').click();assert.match(p.w.document.getElementById('intel-detail').textContent,/absence de devis ≠ devis requis/);assert.match(p.w.document.getElementById('intel-integrity').textContent,/19.*UNKNOWN/);}finally{p.close();}});
test('6.1 Population preserves normalized context and opens the acquired Universal Dossier',async()=>{const p=page();try{await p.w.FixeoIntelligence.refresh();p.w.document.querySelector('[data-intel-cell]').click();p.w.document.querySelector('[data-intel-pop=waiting]').click();await tick();assert.equal(p.calls.at(-1).b.filters.trade,'plomberie');p.w.document.querySelector('[data-intel-dossier]').click();assert.deepEqual(p.opened[0],['request',id]);assert.ok(p.calls.every(c=>!c.op.includes('execute')&&!c.op.includes('preview')));}finally{p.close();}});
test('6.1 Source failure clears current facts and never fabricates a healthy empty Cube',async()=>{let fail=false;const p=page(()=>{if(fail)throw Error('SOURCE_TIMEOUT');});try{await p.w.FixeoIntelligence.refresh();fail=true;await p.w.FixeoIntelligence.refresh(true);assert.match(p.w.document.getElementById('intel-cells').textContent,/SOURCE ERROR.*SOURCE_TIMEOUT/);assert.equal(p.w.document.querySelectorAll('[data-intel-cell]').length,0);assert.equal(p.w.document.getElementById('intel-state').textContent,'UNAVAILABLE');}finally{p.close();}});
test('6.1 Concurrent refresh ignores late answers to older filters',async()=>{let release;const p=page((op,b)=>op==='marketplace'&&b.filters.city==='old'?new Promise(r=>release=r):undefined);try{const old=p.w.FixeoIntelligence.setContext({city:'old'});await tick();await p.w.FixeoIntelligence.setContext({city:'new'});release({...response(),cells:[{key:'old',city:'OBSOLETE'}]});await old;assert.doesNotMatch(p.w.document.getElementById('intel-cells').textContent,/OBSOLETE/);}finally{p.close();}});
