'use strict';
const {test}=require('node:test'),assert=require('node:assert/strict');
const {createHandler}=require('../../api/control');
const id='00000000-0000-4000-8000-000000000001',env={SUPABASE_URL:'https://abcdefghijklmnopqrst.supabase.co',SUPABASE_ANON_KEY:'sb_publishable_SYNTHETIC',FIXEO_STAGING_PROJECT_REF:'abcdefghijklmnopqrst',VERCEL_ENV:'preview',VERCEL_URL:'test.vercel.app'};
const reply=(data,status=200)=>({ok:status<400,status,text:async()=>JSON.stringify(data)});
const routes=[['people',{type:'worker',enterprise_id:id},'control_people_page_v1'],['people-context',{type:'enterprise',id},'control_people_context_v1'],['trust',{queue:'claims'},'control_trust_page_v1'],['trust-context',{type:'claim',id},'control_trust_context_v1'],['review-history',{type:'claim',id},'control_review_history_v1'],['quotes',{queue:'review'},'control_quotes_page_v1'],['quote-context',{type:'quote',id},'control_quote_context_v1'],['finance',{queue:'due'},'control_finance_page_v1'],['finance-context',{type:'mission',id},'control_finance_context_v1']];
async function run(op,body,fetchImpl,headers={authorization:'Bearer synthetic.not_a_real_token'}){const res={headers:{},setHeader(k,v){this.headers[k]=v;},status(v){this.statusCode=v;return this;},json(v){this.body=v;return this;}};await createHandler({env,fetchImpl})({method:'POST',url:'/api/control-v1/'+op,headers,body},res);return res;}
test('B5 register APIs use exact read RPCs with user JWT, public key and no-store',async()=>{for(const [op,body,rpc] of routes){const calls=[];const r=await run(op,body,async(url,o)=>{calls.push({url,o});return reply(url.endsWith('/user')?{id}:{items:[],total:0});});assert.equal(r.statusCode,200);assert.ok(calls[1].url.endsWith('/'+rpc));assert.equal(calls[1].o.headers.Authorization,'Bearer synthetic.not_a_real_token');assert.equal(calls[1].o.headers.apikey,'sb_publishable_SYNTHETIC');assert.equal(r.headers['Cache-Control'],'private, no-store');}});
test('B5 register Auth and cross-origin refusals precede every database read',async()=>{for(const [op,body] of routes){assert.equal((await run(op,body,()=>{throw Error('unexpected');},{})).statusCode,401);assert.equal((await run(op,body,()=>{throw Error('unexpected');},{authorization:'Bearer synthetic.not_a_real_token',origin:'https://untrusted.invalid'})).statusCode,403);}});
test('B5 read errors stay explicit and never return a fabricated total zero',async()=>{for(const [op,body] of routes){for(const failure of ['SOURCE_TIMEOUT','FORBIDDEN']){const r=await run(op,body,async url=>{if(url.endsWith('/user'))return reply({id});if(failure==='FORBIDDEN')return reply({code:'42501',message:'FORBIDDEN'},403);const e=Error();e.name='TimeoutError';throw e;});assert.equal(r.body.code,failure);assert.equal(r.body.total,undefined);assert.equal(r.body.items,undefined);}}});
test('B5 closed payloads refuse SQL/table injection and private entity types',async()=>{for(const [op,body] of routes)assert.equal((await run(op,{...body,rpc:'read_private'},async()=>reply({id}))).statusCode,400);assert.equal((await run('people-context',{type:'personal_client',id},async()=>reply({id}))).statusCode,400);assert.equal((await run('people',{enterprise_id:'invalid'},async()=>reply({id}))).statusCode,400);});
