'use strict';
const {test,before,after}=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path');
const {baseline,migrate,actor,uuid,sql}=require('./bloc34-fixture.cjs');
let db,oldFunctions,oldSecurity;
const rpc=async(name,args)=>(await db.query(`select public.${name}(${args.map((_,i)=>'$'+(i+1)).join(',')}) result`,args)).rows[0].result;
const dossier=(type,id,section='identity',after=null,limit=25)=>rpc('control_dossier_section_v1',[type,uuid(id),section,after,limit]);
const queue=(filters={},after=null,limit=25)=>rpc('control_operations_page_v1',[filters,after,limit]);
const preview=(cap='enterprise.assign',id=100,worker=60)=>rpc('control_hybrid_preview_v1',[cap,uuid(id),{reason:'Synthetic local certification',...(cap==='enterprise.assign'?{worker_id:uuid(worker)}:{})},uuid(900)]);
const execute=(p,key=901)=>rpc('control_hybrid_execute_v1',[p.preview_id,true,uuid(key)]);
const fingerprintSql=`select n.nspname,p.proname,pg_get_function_identity_arguments(p.oid) args,md5(pg_get_functiondef(p.oid)) hash,p.proacl::text acl,pg_get_userbyid(p.proowner) owner from pg_proc p join pg_namespace n on n.oid=p.pronamespace where n.nspname in('public','fixeo_private') and p.prokind='f' order by n.nspname,p.proname,args`;
const securitySql=`select c.relname,c.relacl::text,c.relrowsecurity,(select jsonb_agg(to_jsonb(p) order by p.policyname) from pg_policies p where p.schemaname=n.nspname and p.tablename=c.relname) policies from pg_class c join pg_namespace n on n.oid=c.relnamespace where n.nspname in('public','fixeo_private') and c.relkind in('r','v') order by n.nspname,c.relname`;
before(async()=>{
 db=await baseline();await migrate(db);await db.exec(fs.readFileSync(path.join(__dirname,'../../supabase/migrations/20260929021750_control_os_b2_rafi_reads.sql'),'utf8'));
 oldFunctions=(await db.query(fingerprintSql)).rows;oldSecurity=(await db.query(securitySql)).rows;await db.exec(sql);
 await db.exec(`INSERT INTO auth.users(id) SELECT ('${uuid(0).slice(0,-1)}'||n)::uuid FROM generate_series(1,4) n;
 INSERT INTO public.users(id,role,full_name) VALUES('${uuid(1)}','client','Synthetic Client'),('${uuid(2)}','artisan','Synthetic Artisan'),('${uuid(3)}','admin','Synthetic Operator'),('${uuid(4)}','client','Synthetic Owner');
 INSERT INTO public.profiles(id,role) SELECT id,role FROM public.users;
 SELECT set_config('request.jwt.claims','{"sub":"${uuid(3)}","role":"authenticated"}',false);
 ALTER TABLE public.service_requests DISABLE TRIGGER USER;
 INSERT INTO public.service_requests(id,client_profile_id,city,service_category,description,status,urgency,created_at,data_classification) VALUES
 ('${uuid(100)}','${uuid(1)}','Fès','plomberie','Synthetic request','new','urgent',now()-interval '2 days','test'),
 ('${uuid(101)}',NULL,'Rabat','electricite','Synthetic guest','new',NULL,now(),'test'),
 ('${uuid(102)}','${uuid(1)}','Fès','plomberie','Synthetic request two','new','normale',now(),'test');
 ALTER TABLE public.service_requests ENABLE TRIGGER USER;
 INSERT INTO public.artisans(id,owner_user_id,full_name,phone,city,service_category,claimed,claim_status,onboarding_completed,availability) VALUES('${uuid(20)}','${uuid(2)}','Synthetic Artisan','+000000000001','Fès','plomberie',true,'approved',true,'available');
 INSERT INTO public.enterprise_accounts(id,name,status) VALUES('${uuid(30)}','Synthetic A','active'),('${uuid(31)}','Synthetic B','active');
 INSERT INTO public.enterprise_sites(id,enterprise_id,name,city,status) VALUES('${uuid(40)}','${uuid(30)}','Synthetic A site','Fès','active'),('${uuid(41)}','${uuid(31)}','Synthetic B site','Rabat','active');
 INSERT INTO public.enterprise_members(id,enterprise_id,user_id,role,status) VALUES('${uuid(50)}','${uuid(30)}','${uuid(4)}','owner','active'),('${uuid(51)}','${uuid(30)}','${uuid(2)}','viewer','active');
 INSERT INTO public.enterprise_workforce_workers(id,enterprise_id,member_id,display_label,all_sites,created_by) VALUES('${uuid(60)}','${uuid(30)}','${uuid(51)}','PRIVATE EMPLOYEE LABEL',true,'${uuid(4)}');
 INSERT INTO public.enterprise_workforce_skills(enterprise_id,worker_id,service_category,skill_level,active) VALUES('${uuid(30)}','${uuid(60)}','plomberie',3,true);
 INSERT INTO public.enterprise_request_context(enterprise_id,site_id,service_request_id,created_by) VALUES('${uuid(30)}','${uuid(40)}','${uuid(100)}','${uuid(4)}'),('${uuid(30)}','${uuid(40)}','${uuid(102)}','${uuid(4)}');
 INSERT INTO public.enterprise_dispatch_policies(id,enterprise_id,mode,status) VALUES('${uuid(70)}','${uuid(30)}','internal_only','active');`);
});
after(async()=>db?.close());
function tx(name,fn){test(name,async()=>{await db.exec('RESET ROLE; BEGIN');try{await fn();}finally{await db.exec('ROLLBACK; RESET ROLE');}});}
async function denied(fn,pattern){await db.exec('SAVEPOINT denied');let err;try{await fn();}catch(e){err=e;}await db.exec('ROLLBACK TO SAVEPOINT denied; RELEASE SAVEPOINT denied');assert.ok(err,'Expected refusal');assert.match(err.message,pattern);}
async function grantOperator(){await db.exec(`RESET ROLE; INSERT INTO public.enterprise_members(id,enterprise_id,user_id,role,status) VALUES('${uuid(52)}','${uuid(30)}','${uuid(3)}','operations_manager','active');`);await actor(db,3);}
tx('B34 preserves every existing function, owner, grant, table, RLS and policy',async()=>{const after=(await db.query(fingerprintSql)).rows;for(const row of oldFunctions)assert.deepEqual(after.find(x=>x.nspname===row.nspname&&x.proname===row.proname&&x.args===row.args),row);assert.deepEqual((await db.query(securitySql)).rows,oldSecurity);});
tx('B34 functions have exact ACLs, admin guards and empty search_path',async()=>{const names=['control_dossier_section_v1','control_operations_page_v1','control_operation_read_v1','control_search_all_v1','control_hybrid_read_v1','control_hybrid_preview_v1','control_hybrid_execute_v1'];const rows=(await db.query(`select p.proname,p.prosecdef,p.proconfig,pg_get_userbyid(p.proowner) owner,has_function_privilege('anon',p.oid,'EXECUTE') anon,has_function_privilege('service_role',p.oid,'EXECUTE') service,has_function_privilege('authenticated',p.oid,'EXECUTE') authenticated from pg_proc p where p.proname=ANY($1)`,[names])).rows;assert.equal(rows.length,7);for(const x of rows){assert.ok(x.prosecdef);assert.equal(x.owner,'postgres');assert.ok(x.proconfig.includes('search_path=""'));assert.equal(x.anon,false);assert.equal(x.service,false);assert.equal(x.authenticated,true);}});
tx('B34 all new endpoints reject anon, non-admin and service_role direct RPC access',async()=>{for(const [id,role] of [[1,'anon'],[1,'authenticated'],[2,'authenticated'],[3,'service_role']]){await actor(db,id,role);for(const fn of [()=>dossier('request',100),()=>queue(),()=>rpc('control_operation_read_v1',[uuid(100)]),()=>rpc('control_search_all_v1',['Fès','all',null,25]),()=>rpc('control_hybrid_read_v1',[uuid(100)]),()=>preview(),()=>rpc('control_hybrid_execute_v1',[uuid(888),true,uuid(889)])])await denied(fn,/permission denied|FORBIDDEN/);}});
tx('Dossier direct ID works independently of loaded lists and exposes only canonical projection',async()=>{await actor(db,3);const d=await dossier('request',100);assert.equal(d.id,uuid(100));assert.equal(d.summary.status,'new');assert.equal(d.request_id,uuid(100));assert.equal(d.field_sources.enterprise_id,'public.enterprise_request_context');for(const forbidden of ['guest_token_hash','client_phone','description','PRIVATE EMPLOYEE LABEL'])assert.ok(!JSON.stringify(d).includes(forbidden));});
tx('Dossier supports all 13 types; missing objects remain NOT_FOUND',async()=>{await actor(db,3);for(const [t,id] of [['client',1],['artisan',20],['enterprise',30],['site',40],['worker',60]])assert.equal((await dossier(t,id)).entity_type,t);for(const t of ['mission','quote','claim','internal_assignment','pricing_offer','diagnostic_summary','remittance'])await denied(()=>dossier(t,9999),/NOT_FOUND/);await denied(()=>dossier('personal_client',1),/UNSUPPORTED_ENTITY/);});
tx('Dossier relationships use canonical IDs and stable keyset pagination without duplicates',async()=>{await actor(db,3);const ids=new Set();let cursor=null;do{const d=await dossier('request',100,'relations',cursor,1);assert.equal(d.items.length,1);assert.ok(!ids.has(d.items[0].key));ids.add(d.items[0].key);assert.equal(d.items[0].access,'accessible');cursor=d.next_cursor;}while(cursor);assert.equal(ids.size,3);const client=await dossier('client',1,'relations');assert.deepEqual(client.items.map(x=>x.id),[uuid(100),uuid(102)]);});
tx('Dossier pagination refuses cursors from another entity or section',async()=>{await actor(db,3);const p=await dossier('request',100,'relations',null,1);await denied(()=>dossier('request',102,'relations',p.next_cursor,1),/INVALID_CURSOR/);await denied(()=>dossier('request',100,'timeline',p.next_cursor,1),/INVALID_CURSOR/);});
tx('Timeline distinguishes canonical timestamps from audits; actor attribution and raw snapshots are safe',async()=>{await db.exec(`INSERT INTO fixeo_private.authority_audit_events_v1(target_type,target_id,authority,action,result,actor_id,actor_role,correlation_id,change) VALUES('request','${uuid(100)}','Synthetic Authority','review','succeeded','${uuid(3)}','admin','${uuid(900)}','{"private_before_image":"PRIVATE SECRET ROW"}');`);await actor(db,3);const r=await dossier('request',100,'timeline');assert.ok(r.items.some(x=>x.evidence==='CANONICAL_TIMESTAMP'));const a=r.items.find(x=>x.evidence==='AUDIT');assert.equal(a.actor_id,uuid(3));assert.equal(a.correlation_id,uuid(900));assert.ok(!JSON.stringify(r).includes('PRIVATE SECRET ROW'));});
tx('Timeline tied timestamps paginate with stable key, no event loss',async()=>{await db.exec(`INSERT INTO fixeo_private.authority_audit_events_v1(id,occurred_at,target_type,target_id,authority,action,result,actor_role,correlation_id) SELECT ('00000000-0000-4000-8000-'||lpad(n::text,12,'0'))::uuid,now(),'request','${uuid(100)}','Synthetic','review','succeeded','server','${uuid(900)}' FROM generate_series(700,703) n;`);await actor(db,3);let cursor=null,keys=[];do{const r=await dossier('request',100,'timeline',cursor,2);keys.push(...r.items.map(x=>x.key));cursor=r.next_cursor;}while(cursor);assert.equal(keys.length,5);assert.equal(new Set(keys).size,5);});
tx('Operations filters canonical origins, ages, urgency and tenant/site boundaries',async()=>{await actor(db,3);assert.equal((await queue({origin:'enterprise',city:'Fès',trade:'plomberie',min_age:1440})).items.length,1);assert.equal((await queue({urgency:'unknown'})).items[0].id,uuid(101));assert.equal((await queue({origin:'guest'})).items[0].id,uuid(101));await denied(()=>queue({enterprise_id:uuid(30),site_id:uuid(41)}),/FORBIDDEN/);await denied(()=>queue({executor:'unknown_positive'}),/INVALID_FILTER/);await denied(()=>queue({injected_field:'x'}),/INVALID_FILTER/);});
tx('Operations distinguishes an offer, an assignment and an actual notification',async()=>{await db.exec(`INSERT INTO public.missions(id,request_id,artisan_profile_id,status) VALUES('${uuid(80)}','${uuid(101)}','${uuid(20)}','offered');`);await actor(db,3);const r=(await queue({origin:'guest'})).items[0];assert.equal(r.executor,'unassigned');assert.equal(r.operational_state,'offered');assert.equal(r.dispatch.sent_evidence,0);assert.equal(r.hybrid,null);assert.equal(r.sla,null);});
tx('Operations pages reach every row without inferring a global total',async()=>{await actor(db,3);let cursor=null,ids=[];do{const r=await queue({},cursor,1);ids.push(...r.items.map(x=>x.id));assert.equal(r.global_total,null);cursor=r.next_cursor;}while(cursor);assert.equal(ids.length,3);assert.equal(new Set(ids).size,3);});
tx('Global search pages across universes and exact workforce IDs without private labels',async()=>{await actor(db,3);const one=await rpc('control_search_all_v1',[uuid(60),'all',null,25]);assert.equal(one.items.length,1);assert.equal(one.items[0].type,'worker');assert.ok(!JSON.stringify(one).includes('PRIVATE EMPLOYEE LABEL'));const a=await rpc('control_search_all_v1',['Fès','all',null,1]);const b=await rpc('control_search_all_v1',['Fès','all',a.next_cursor,1]);assert.notEqual(a.items[0].key,b.items[0].key);await denied(()=>rpc('control_search_all_v1',['x','all',null,1]),/INVALID_SEARCH/);});
tx('Global Admin reads minimal capacity but cannot prepare tenant mutations without membership',async()=>{await actor(db,3);const r=await rpc('control_hybrid_read_v1',[uuid(100)]);assert.equal(r.tenant_operator,false);assert.equal(r.actionable,false);assert.equal(r.workers[0].eligible,true);assert.ok(!JSON.stringify(r).includes('PRIVATE EMPLOYEE LABEL'));assert.ok(!Object.hasOwn(r,'fingerprint'));await denied(()=>preview(),/TENANT_DISPATCH_PERMISSION_REQUIRED/);});
tx('Hybrid eligibility explains real skill, availability, membership, site and capacity constraints',async()=>{await db.exec(`UPDATE public.enterprise_workforce_workers SET availability='unavailable',all_sites=false WHERE id='${uuid(60)}';UPDATE public.enterprise_workforce_skills SET active=false WHERE worker_id='${uuid(60)}';`);await actor(db,3);const w=(await rpc('control_hybrid_read_v1',[uuid(100)])).workers[0];assert.equal(w.eligible,false);for(const reason of ['not_available','site_mismatch','skill_mismatch'])assert.ok(w.reasons.includes(reason));});
tx('Hybrid confirmation performs canonical assignment exactly once with durable audit and replay',async()=>{await grantOperator();const p=await preview();const r=await execute(p);assert.equal(r.ok,true,JSON.stringify(r));assert.equal(r.verified.status,'assigned');assert.ok(r.audit_id);assert.deepEqual(await execute(p),r);await db.exec('RESET ROLE');const n=(await db.query('select count(*) n from public.enterprise_internal_assignments where service_request_id=$1',[uuid(100)])).rows[0].n;assert.equal(Number(n),1);const audit=(await db.query('select actor_id,authority,action from fixeo_private.authority_audit_events_v1 where id=$1',[r.audit_id])).rows[0];assert.equal(audit.actor_id,uuid(3));assert.equal(audit.action,'enterprise.assign');});
tx('Hybrid preview alone writes no business state or offers',async()=>{await grantOperator();await preview();await db.exec('RESET ROLE');for(const table of ['enterprise_internal_assignments','enterprise_internal_dispatch_offers','dispatch_execution_queue'])assert.equal(Number((await db.query('select count(*) n from public.'+table)).rows[0].n),0);});
tx('Hybrid execution requires explicit confirmation and refuses another actor preview',async()=>{await grantOperator();const p=await preview();await denied(()=>rpc('control_hybrid_execute_v1',[p.preview_id,false,uuid(902)]),/HUMAN_CONFIRMATION_REQUIRED/);await actor(db,4);await denied(()=>execute(p),/FORBIDDEN/);});
tx('Hybrid stale capacity or policy refuses with a durable failed audit; no repair mutation',async()=>{await grantOperator();const p=await preview();await db.exec(`RESET ROLE; UPDATE public.enterprise_workforce_workers SET availability='unavailable' WHERE id='${uuid(60)}';`);await actor(db,3);const r=await execute(p);assert.equal(r.ok,false);assert.equal(r.code,'STALE_PREVIEW');assert.ok(r.audit_id);assert.deepEqual(await execute(p),r);});
tx('Hybrid revoked tenant permission refuses execution and cached replay',async()=>{await grantOperator();const p=await preview();await execute(p);await db.exec(`RESET ROLE; UPDATE public.enterprise_members SET status='suspended' WHERE id='${uuid(52)}';`);await actor(db,3);await denied(()=>execute(p),/TENANT_DISPATCH_PERMISSION_REQUIRED/);});
tx('Hybrid internal_only retry calls canonical engine without external dispatch',async()=>{await grantOperator();const p=await preview('enterprise.retry');const r=await execute(p);assert.equal(r.ok,true,JSON.stringify(r));await db.exec('RESET ROLE');assert.equal(Number((await db.query('select count(*) n from public.dispatch_execution_queue')).rows[0].n),0);assert.equal(Number((await db.query('select count(*) n from public.enterprise_internal_dispatch_offers')).rows[0].n),1);});
tx('Hybrid idempotency key cannot be rebound to another preview',async()=>{await grantOperator();const a=await preview(),b=await preview();assert.equal((await execute(a)).ok,true);await denied(()=>execute(b),/IDEMPOTENCY_CONFLICT/);});
tx('Hybrid policy external_only disables internal assignment',async()=>{await db.exec(`UPDATE public.enterprise_dispatch_policies SET mode='external_only' WHERE id='${uuid(70)}'`);await grantOperator();await denied(()=>preview(),/WORKER_NOT_ELIGIBLE/);});
tx('All dossier families preserve their minimal fields and FK paths including Pricing, Diagnostic and Finance',async()=>{
 await db.exec(`INSERT INTO public.quotes(id,request_id,artisan_profile_id,proposed_price,status) VALUES('${uuid(200)}','${uuid(101)}','${uuid(20)}',100,'pending');
 INSERT INTO public.fixeo_pricing_offers_v1(id,offer_key,pricing_version,currency,service_code,catalogue_version,city,scope,vap_minor,materials_minor,commission_minor,client_total_minor,expires_at) VALUES('${uuid(201)}','${uuid(202)}','vap-bp33-v1','MAD','plomberie','synthetic-v1','Rabat','{"synthetic":true}',10000,0,public.fixeo_vap_commission_minor_v1(10000),10000+public.fixeo_vap_commission_minor_v1(10000),now()+interval '1 day');
 INSERT INTO fixeo_private.diagnostic_sessions_v1(id,owner_key,owner_user_id,source,state,city_slug,input,consent_version,service_request_id) VALUES('${uuid(203)}','u:${uuid(1)}','${uuid(1)}','homepage','bound','rabat','{"private_media":"PRIVATE_MEDIA"}','diagnostic-privacy-v1','${uuid(101)}');
 INSERT INTO public.missions(id,request_id,artisan_profile_id,status) VALUES('${uuid(204)}','${uuid(101)}','${uuid(20)}','offered');
 INSERT INTO public.commission_remittances_v1(id,mission_id,amount,method,proof_reference,declared_by) VALUES('${uuid(205)}','${uuid(204)}',10,'cash','PRIVATE_PROOF','${uuid(3)}');
 INSERT INTO public.claim_requests(id,artisan_id,requester_user_id,status) VALUES('${uuid(206)}','${uuid(20)}','${uuid(1)}','pending');`);
 await actor(db,3);for(const [type,id] of [['quote',200],['pricing_offer',201],['diagnostic_summary',203],['mission',204],['remittance',205],['claim',206]]){const d=await dossier(type,id);assert.equal(d.id,uuid(id));for(const secret of ['PRIVATE_OWNER_KEY','PRIVATE_MEDIA','PRIVATE_PROOF'])assert.ok(!JSON.stringify(d).includes(secret),type);}
 assert.equal((await dossier('diagnostic_summary',203,'relations')).items[0].id,uuid(101));assert.equal((await dossier('remittance',205,'relations')).items[0].id,uuid(204));
 await grantOperator();assert.equal((await execute(await preview())).ok,true);const a=(await dossier('request',100,'relations')).items.find(x=>x.type==='internal_assignment');assert.ok(a);const d=await rpc('control_dossier_section_v1',['internal_assignment',a.id,'identity',null,25]);assert.equal(d.summary.worker_id,uuid(60));
});
tx('Hybrid expired preview and cross-tenant worker are refused before business writes',async()=>{await grantOperator();await denied(()=>preview('enterprise.assign',100,999),/WORKER_NOT_ELIGIBLE/);const p=await preview();await db.exec(`RESET ROLE; UPDATE fixeo_private.control_action_previews_v1 SET expires_at=now()-interval '1 second' WHERE id='${p.preview_id}'`);await actor(db,3);await denied(()=>execute(p),/PREVIEW_EXPIRED/);});
test('B34 rollback removes only additive functions and preserves the original security contract',async()=>{await db.exec(fs.readFileSync(path.join(__dirname,'../../docs/control-os/bloc34/rollback.sql'),'utf8'));assert.deepEqual((await db.query(fingerprintSql)).rows,oldFunctions);assert.deepEqual((await db.query(securitySql)).rows,oldSecurity);});
