'use strict';
const {test,before,after}=require('node:test'),assert=require('node:assert/strict');
const {setup,seed,actor,uuid}=require('./bloc5-fixture.cjs');let db;
const rpc=async(name,args)=>(await db.query(`select public.${name}(${args.map((_,i)=>'$'+(i+1)).join(',')}) result`,args)).rows[0].result;
const page=(filters={},after=null,limit=25)=>rpc('control_trust_page_v1',[filters,after,limit]);
const context=(type,n,after=null,limit=25)=>rpc('control_trust_context_v1',[type,uuid(n),after,limit]);
before(async()=>{db=await setup();await seed(db);await db.exec(`INSERT INTO public.claim_requests(id,artisan_id,requester_user_id,requester_name,requester_phone,onboarding_data) VALUES('${uuid(80)}','${uuid(21)}','${uuid(6)}','Synthetic claimant','PRIVATE CONTACT','{"secret":"PRIVATE ONBOARDING"}'),('${uuid(81)}',NULL,'${uuid(7)}','Missing artisan','','{}');INSERT INTO public.service_requests(id,city,service_category,description,status) VALUES('${uuid(999)}','Fès','plomberie','Synthetic historical request','completed');INSERT INTO public.missions(id,request_id,artisan_profile_id,status) VALUES('${uuid(70)}','${uuid(999)}','${uuid(20)}','done');INSERT INTO public.reviews(id,mission_id,artisan_id,rating,verified,client_phone,review_text) VALUES('${uuid(90)}','${uuid(70)}','${uuid(20)}',4,true,'PRIVATE CLIENT CONTACT','PRIVATE REVIEW TEXT'),('${uuid(91)}','${uuid(70)}','${uuid(20)}',3,false,'PRIVATE CLIENT CONTACT','PRIVATE REVIEW TEXT');DELETE FROM public.service_requests WHERE id='${uuid(999)}';`);});after(async()=>db?.close());
function tx(name,fn){test(name,async()=>{await db.exec('RESET ROLE;BEGIN');try{await fn();}finally{await db.exec('ROLLBACK;RESET ROLE');}});}
async function denied(fn,re){await db.exec('SAVEPOINT refusal');let e;try{await fn();}catch(x){e=x;}await db.exec('ROLLBACK TO SAVEPOINT refusal;RELEASE SAVEPOINT refusal');assert.ok(e);assert.match(e.message,re);}
tx('5.2 Trust readers deny anon, non-admin, tenant owners and direct service role',async()=>{for(const [n,r] of [[1,'anon'],[1,'authenticated'],[4,'authenticated'],[3,'service_role']]){await actor(db,n,r);await denied(()=>page(),/FORBIDDEN|permission denied/);await denied(()=>context('claim',80),/FORBIDDEN|permission denied/);await denied(()=>rpc('control_review_history_v1',['claim',uuid(80),null,25]),/FORBIDDEN|permission denied/);}});
tx('5.2 Claim evidence preserves missing relations and never calls provided contact verified',async()=>{await actor(db,3);assert.equal((await page({queue:'claims',state:'pending'})).total,2);const a=await context('claim',80),b=await context('claim',81);assert.equal(a.facts.requester_exists,true);assert.equal(a.facts.contact_provided,true);assert.equal(a.facts.contact_verified,null);assert.equal(b.facts.artisan_relation,'NOT_FOUND');assert.equal(b.facts.ownership_conflict,null);assert.ok(!JSON.stringify(a).includes('PRIVATE'));});
tx('5.2 Ready for verification is separate from non-verified, incomplete and claimed',async()=>{await actor(db,3);assert.equal((await page({queue:'verification',state:'ready'})).total,1);assert.equal((await page({queue:'verification',state:'unverified'})).total,2);const p=await page({queue:'completeness'});assert.equal(p.total,1);assert.equal(p.items[0].id,uuid(21));assert.ok(p.items[0].facts.missing_fields.includes('phone'));});
tx('5.2 Conflicting canonical and legacy flags remain a distinct factual register',async()=>{await db.exec(`ALTER TABLE public.artisans DISABLE TRIGGER USER;update public.artisans set verified=false,is_verified=true where id='${uuid(20)}';ALTER TABLE public.artisans ENABLE TRIGGER USER;`);await actor(db,3);const p=await page({queue:'conflicts'});assert.equal(p.total,1);assert.equal(p.items[0].summary.verified,false);assert.equal(p.items[0].facts.verification_conflict,true);});
tx('5.2 Review rows stay distinct, paginated, linked to mission; missing request is NOT_FOUND',async()=>{await actor(db,3);const p=await page({queue:'reviews'},null,1),q=await page({queue:'reviews'},p.next_cursor,1);assert.equal(p.total,2);assert.equal(p.total_kind,'review_rows');assert.notEqual(p.items[0].key,q.items[0].key);assert.equal(p.items[0].id,q.items[0].id);const c=await context('mission',70);assert.equal(c.reviews.length,2);assert.ok(c.reviews.every(v=>v.request_relation==='NOT_FOUND'));assert.ok(!JSON.stringify(c).includes('PRIVATE'));assert.equal((await page({queue:'reviews',state:'verified'})).total,1);});
tx('5.2 Cursor scope, queue/state and malformed filters fail closed',async()=>{await actor(db,3);const p=await page({},null,1);await denied(()=>page({queue:'verification'},p.next_cursor),/INVALID_CURSOR/);for(const f of [{queue:'reviews',state:'pending'},{queue:'conflicts',state:'ready'},{queue:'private_business'},{rpc:'evil'}])await denied(()=>page(f),/INVALID_FILTER/);await denied(()=>context('client',1),/INVALID_FILTER/);});
tx('5.2 Governed claim approval requires reason, durable audit and replay; it does not verify the artisan',async()=>{await actor(db,3);await denied(()=>rpc('control_action_preview_v1',['claim.approve',uuid(80),{reason:''},uuid(300)]),/INVALID_ACTION_PAYLOAD/);const p=await rpc('control_action_preview_v1',['claim.approve',uuid(80),{reason:'Synthetic reviewed evidence'},uuid(300)]);const a=await rpc('control_action_execute_v1',[p.preview_id,true,uuid(301)]);assert.equal(a.ok,true);assert.ok(a.audit_id);const b=await rpc('control_action_execute_v1',[p.preview_id,true,uuid(301)]);assert.deepEqual(a,b);const history=await rpc('control_review_history_v1',['claim',uuid(80),null,25]);assert.equal(history.items.length,1);assert.equal(history.items[0].reason,'Synthetic reviewed evidence');assert.equal(history.items[0].audit_id,a.audit_id);assert.equal(history.items[0].actor_id,uuid(3));const d=await rpc('control_dossier_section_v1',['artisan',uuid(21),'identity',null,25]);assert.equal(d.summary.claimed,true);assert.equal(d.summary.verified,false);assert.equal(d.summary.onboarding_completed,false);await db.exec('RESET ROLE');assert.equal((await db.query('select count(*) n from fixeo_private.authority_audit_events_v1 where id=$1',[a.audit_id])).rows[0].n,1);});
tx('5.2 Stale claim decisions refuse ownership transfer and leave the business row intact',async()=>{await actor(db,3);const p=await rpc('control_action_preview_v1',['claim.approve',uuid(80),{reason:'Synthetic reviewed evidence'},uuid(310)]);await db.exec(`RESET ROLE;update public.claim_requests set status='rejected' where id='${uuid(80)}'`);await actor(db,3);const a=await rpc('control_action_execute_v1',[p.preview_id,true,uuid(311)]);assert.equal(a.ok,false);assert.match(a.code,/STALE/);const d=await rpc('control_dossier_section_v1',['artisan',uuid(21),'identity',null,25]);assert.equal(d.summary.claimed,false);});
