'use strict';
// Real Admin UI → real API handler → canonical SQL in an isolated migrated database.
const fs=require('node:fs'),path=require('node:path'),http=require('node:http'),assert=require('node:assert/strict'),{chromium}=require('playwright');
const F=require('./bloc7-fixture.cjs'),{createHandler}=require('../../api/control'),u=F.uuid,root=path.resolve(__dirname,'../..'),out=path.join(root,'docs/control-os/bloc7/evidence/browser');
let db,server,browser,fault=null,executions=0;const checks=[],errors=[],backendErrors=[];
const reply=(data,status=200)=>({ok:status<400,status,text:async()=>JSON.stringify(data)});
(async()=>{try{
 db=await F.setup();await F.seed(db);await db.exec(`INSERT INTO public.service_requests(id,city,service_category,description,status,created_at,client_profile_id,urgency) VALUES
 ('${u(100)}','Fès','plomberie','Synthetic waiting browser request','new','2026-09-05T10:00Z','${u(1)}','urgent'),
 ('${u(101)}','Fès','plomberie','Synthetic accepted browser request','assigned','2026-09-05T10:00Z','${u(1)}','normale'),
 ('${u(102)}','Fès','plomberie','Synthetic parent removed','completed','2026-09-05T10:00Z','${u(1)}','normale'),
 ('${u(103)}','Fès','plomberie','Synthetic comparison request','cancelled','2026-08-20T10:00Z','${u(1)}','normale');
 INSERT INTO public.missions(id,request_id,artisan_profile_id,status,accepted_at) VALUES('${u(200)}','${u(101)}','${u(20)}','pending','2026-09-05T11:00Z'),('${u(201)}','${u(102)}','${u(20)}','done','2026-09-05T11:00Z');
 DELETE FROM public.service_requests WHERE id='${u(102)}';UPDATE public.artisans SET city='Fès',service_category='plomberie',claimable=true WHERE id='${u(21)}';`);
 await db.exec(`INSERT INTO public.claim_requests(id,artisan_id,requester_user_id,requester_name) VALUES('${u(80)}','${u(21)}','${u(6)}','Synthetic claimant');`);await F.actor(db,3);
 const handler=createHandler({env:{SUPABASE_URL:'https://abcdefghijklmnopqrst.supabase.co',SUPABASE_ANON_KEY:'sb_publishable_SYNTHETIC',FIXEO_STAGING_PROJECT_REF:'abcdefghijklmnopqrst'},fetchImpl:async(url,o)=>{
  if(url.endsWith('/user'))return reply({id:u(3)});const name=url.split('/').at(-1),args=JSON.parse(o.body);assert.match(name,/^control_[a-z0-9_]+_v[13]$/);const keys=Object.keys(args);assert.ok(keys.every(k=>/^p_[a-z_]+$/.test(k)));
  if(/_execute_v[13]$/.test(name))executions++;
  if(fault==='trust'&&name==='control_rafi_source_v3'&&args.p_source==='trust')return reply({message:'SOURCE_TIMEOUT'},503);
  if(fault==='followups'&&name==='control_rafi_followups_v3')return reply({message:'SOURCE_TIMEOUT'},503);
  if(fault==='network'&&name==='control_marketplace_cube_v1'&&args.p_source==='network'||fault==='cohorts'&&name==='control_marketplace_cohorts_v1')return reply({message:'SOURCE_TIMEOUT'},503);
  try{return reply((await db.query(`select public.${name}(${keys.map((k,i)=>k+'=> $'+(i+1)).join(',')}) result`,Object.values(args))).rows[0].result);}catch(e){backendErrors.push({name,code:e.code,message:e.message});return reply({code:e.code,message:e.message},e.code==='42501'?403:422);}
 }});
 server=http.createServer(async(req,res)=>{const pathname=new URL(req.url,'http://localhost').pathname;
  if(pathname.startsWith('/api/control-v1/')){let raw='';for await(const c of req)raw+=c;const adapter={setHeader:(k,v)=>res.setHeader(k,v),status(s){res.statusCode=s;return this;},json(v){res.setHeader('Content-Type','application/json');res.end(JSON.stringify(v));}};return handler({method:req.method,url:pathname,headers:{authorization:req.headers.authorization},body:JSON.parse(raw||'{}')},adapter);}
  if(pathname==='/admin.html'){let html=fs.readFileSync(path.join(root,'admin.html'),'utf8').replace(/<script\b[^>]*>[\s\S]*?<\/script>/gi,'').replace(/<link[^>]+(?:fonts.googleapis|preconnect)[^>]*>/gi,'');
   const boot=`window.FIXEO_ISOLATED=true;window.FixeoSupabaseClient={client:{auth:{getSession:async()=>({data:{session:{access_token:'synthetic.isolated.token',user:{id:'${u(3)}'}}}})},from:table=>{if(table!=='users')throw Error('UNEXPECTED_DIRECT_READ');return{select:()=>({eq:()=>({single:async()=>({data:{role:'admin'}})})})};}}};`;
   html=html.replace('</body>',`<script>${boot}</script>`+['fixeo-control-client-v1.js','admin-fixeo-intelligence.js','admin-fixeo-registers.js','admin-fixeo-dossier.js','admin-fixeo-operations.js','admin-rafi-followups.js','admin-rafi-decision-center.js','admin-control-os-clean.js'].map(x=>`<script src="/js/${x}"></script>`).join('')+'</body>');res.setHeader('Content-Type','text/html');return res.end(html);}
  const file=path.resolve(root,'.'+decodeURIComponent(pathname));if(!file.startsWith(root+path.sep)||!fs.existsSync(file)||!fs.statSync(file).isFile()){res.statusCode=404;return res.end();}res.setHeader('Content-Type',file.endsWith('.css')?'text/css':file.endsWith('.js')?'application/javascript':file.endsWith('.png')?'image/png':'application/octet-stream');fs.createReadStream(file).pipe(res);
 });
 await new Promise(r=>server.listen(0,'127.0.0.1',r));browser=await chromium.launch({headless:true});const page=await browser.newPage({viewport:{width:1440,height:1000}});page.on('pageerror',e=>errors.push(e.message));await page.route('**/*',r=>r.request().url().startsWith('http://127.0.0.1:')?r.continue():r.abort());fs.mkdirSync(out,{recursive:true});
 await page.goto('http://127.0.0.1:'+server.address().port+'/admin.html?view=rafi');await page.waitForFunction(()=>document.getElementById('rafi-state')?.textContent==='FRESH');
 const claim=await page.evaluate(id=>FixeoRafi.decisionsFor('claim',id)[0],u(80));assert.ok(claim.canonical_proof);await page.evaluate(id=>FixeoRafi.openDecision(id),claim.decision_id);await page.waitForSelector('[data-rafi-follow]');
 assert.match(await page.locator('.rafi-explain').innerText(),/Pourquoi maintenant/);assert.match(await page.locator('.rafi-explain').innerText(),/Règle claim.pending/);assert.match(await page.locator('.rafi-explain').textContent(),/CANONICAL/);checks.push('rule_evidence_provenance_inference_and_canonical_dossier');
 await page.locator('[data-rafi-follow]').click();await page.getByRole('button',{name:'Confirmer le suivi',exact:true}).click();await page.waitForSelector('[data-follow-ack]');assert.match(await page.locator('#rafi-followups').innerText(),/À suivre/);assert.equal(executions,0);checks.push('explicit_followup_creation_no_business_execution');
 await page.locator('[data-follow-ack]').click();await page.getByRole('button',{name:'Confirmer le suivi',exact:true}).click();await page.waitForFunction(()=>document.getElementById('rafi-followups').textContent.includes('Pris en compte'));checks.push('acknowledgement_operator_metadata_only');
 await page.locator('[data-follow-proof]').click();await page.waitForSelector('dialog[open]');assert.match(await page.locator('dialog.rafi-follow-dialog').innerText(),/Aucun événement canonique/);await page.getByRole('button',{name:'Revenir',exact:true}).click();checks.push('no_resolution_without_canonical_event');
 await page.evaluate(id=>FixeoRafi.openDecision(id),claim.decision_id);await page.waitForSelector('[data-rafi-prepare="claim.reject"]');await page.locator('[data-rafi-prepare="claim.reject"]').click();await page.locator('textarea[name=reason]').fill('Synthetic governed review after examining evidence');await page.getByRole('button',{name:'Vérifier les préconditions et voir l’aperçu'}).click();await page.waitForSelector('dialog[open]');assert.equal(executions,0);await page.getByRole('button',{name:'Confirmer et exécuter',exact:true}).click();await page.waitForFunction(()=>!document.querySelector('dialog[open]'));await page.waitForFunction(()=>document.getElementById('drawer').textContent.includes('rejected'));assert.equal(executions,1);checks.push('evidence_bound_preview_human_confirmation_canonical_result');await page.evaluate(()=>FixeoDossier.close());
 await page.locator('#rafi-followups-load').click();await page.waitForFunction(()=>document.getElementById('rafi-followups').textContent.includes('Évolution inconnue'));assert.match(await page.locator('#rafi-followups').innerText(),/Évolution inconnue/);assert.match(await page.locator('#rafi-followups').innerText(),/Pris en compte/);checks.push('disappeared_signal_never_auto_closes');
 await page.locator('[data-follow-proof]').click();await page.waitForSelector('dialog select[name=audit]');await page.getByRole('button',{name:'Confirmer le suivi',exact:true}).click();await page.waitForFunction(()=>document.getElementById('rafi-followups').textContent.includes('Clôturé sur preuve'));checks.push('resolution_requires_canonical_audit_and_current_state');
 await page.locator('#rafi-synthesis').click();await page.waitForFunction(()=>document.getElementById('rafi-synthesis-result').textContent.includes('Synthèse déterministe'));checks.push('optional_AI_disabled_grounded_brief_remains_available');
 fault='followups';await page.locator('#rafi-followups-load').click();await page.waitForFunction(()=>document.getElementById('rafi-followups').textContent.includes('indisponibles'));assert.match(await page.locator('#rafi-followups').innerText(),/Aucun statut métier/);fault=null;await page.locator('#rafi-followups-load').click();await page.waitForSelector('.rafi-follow-row');checks.push('followup_error_is_not_empty_or_resolved');
 fault='trust';await page.evaluate(()=>FixeoRafi.load());await page.waitForFunction(()=>document.getElementById('rafi-state').textContent==='PARTIAL');assert.match(await page.locator('#rafi-sources').innerText(),/UNAVAILABLE/);fault=null;await page.evaluate(()=>FixeoRafi.load());await page.waitForFunction(()=>document.getElementById('rafi-state').textContent==='FRESH');checks.push('independent_source_error_and_recovery');
 for(const width of [1440,1280,1024,768,390]){await page.setViewportSize({width,height:900});assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),'overflow '+width);await page.screenshot({path:path.join(out,'rafi-'+width+'.png')});checks.push('responsive_'+width);}
 await page.evaluate(()=>FixeoAdmin.navigate('operations'));await page.waitForSelector('.operation-main .rafi-inline-priority');checks.push('existing_list_uses_loaded_RAFI_priority_no_extra_source');
 assert.deepEqual(errors,[]);assert.deepEqual(backendErrors,[]);assert.equal(executions,1);checks.push('no_runtime_SQL_errors_one_confirmed_isolated_business_action');const result={status:'PASS',checks,executions,environment:'isolated synthetic SQL, real UI and handler; no Production account or fixture'};fs.writeFileSync(path.join(out,'results.json'),JSON.stringify(result,null,2));console.log(JSON.stringify({status:'PASS',checks:checks.length,executions}));
 }catch(e){console.error(e.stack);if(backendErrors.length)console.error(JSON.stringify(backendErrors));process.exitCode=1;}finally{await browser?.close();if(server)await new Promise(r=>server.close(r));await db?.close();}})();
