'use strict';
// Full Bloc 5 UI against the migrated isolated PostgreSQL fixture. No external writes.
const fs=require('node:fs'),path=require('node:path'),http=require('node:http'),assert=require('node:assert/strict'),{chromium}=require('playwright');
const F=require('./bloc5-fixture.cjs'),{createHandler}=require('../../api/control');
const root=path.resolve(__dirname,'../..'),out=path.join(root,'docs/control-os/bloc5/evidence/browser'),u=F.uuid;let db,server,browser,executions=0,fault=false;
const checks=[],errors=[],backendErrors=[];
const ok=data=>({ok:true,status:200,text:async()=>JSON.stringify(data)});
(async()=>{try{
 db=await F.setup();await F.seed(db);
 await db.exec(`INSERT INTO public.service_requests(id,client_profile_id,city,service_category,description,status) VALUES('${u(100)}','${u(1)}','Fès','plomberie','Synthetic quote request','new'),('${u(101)}','${u(1)}','Fès','plomberie','Synthetic financial case','completed'),('${u(102)}','${u(1)}','Fès','plomberie','Synthetic removed parent','completed');INSERT INTO public.missions(id,request_id,artisan_profile_id,status,completed_at) VALUES('${u(200)}','${u(101)}','${u(20)}','done',now()),('${u(201)}','${u(102)}','${u(20)}','done',now());SELECT public.admin_settle_mission_v1('${u(200)}',1000,NULL,'Synthetic valid price');DELETE FROM public.service_requests WHERE id='${u(102)}';INSERT INTO public.claim_requests(id,artisan_id,requester_user_id,requester_name) VALUES('${u(80)}','${u(21)}','${u(6)}','Demandeur synthétique');`);
 const rpc=async(name,args)=>(await db.query(`select to_jsonb(public.${name}(${args.map((_,i)=>'$'+(i+1)).join(',')})) result`,args)).rows[0].result;
 const remittance=(await rpc('admin_commission_remittance_v1',[u(200),'declare',null,null,10,'cash','SYNTHETIC BROWSER PROOF','Synthetic declaration'])).id;
 await F.actor(db,2);const quote=(await rpc('submit_artisan_quote_v2',[u(100),1000,'Réparation synthétique isolée','Fournitures synthétiques','1 heure',null])).id;await F.actor(db,3);
 const handler=createHandler({env:{SUPABASE_URL:'https://abcdefghijklmnopqrst.supabase.co',SUPABASE_ANON_KEY:'sb_publishable_SYNTHETIC',VERCEL_ENV:'preview',VERCEL_URL:'isolated.invalid',FIXEO_STAGING_PROJECT_REF:'abcdefghijklmnopqrst'},fetchImpl:async(url,o)=>{
  if(url.endsWith('/user'))return ok({id:u(3)});
  const name=url.split('/').at(-1),args=JSON.parse(o.body);assert.match(name,/^control_[a-z0-9_]+_v1$/);const keys=Object.keys(args);assert.ok(keys.every(k=>/^p_[a-z_]+$/.test(k)));
  if(fault&&name==='control_finance_context_v1')return{ok:false,status:503,text:async()=>JSON.stringify({message:'SOURCE_TIMEOUT'})};
  if(name.endsWith('_execute_v1'))executions++;
  try{return ok((await db.query(`select public.${name}(${keys.map((k,i)=>k+'=> $'+(i+1)).join(',')}) result`,Object.values(args))).rows[0].result);}catch(e){backendErrors.push({name,args,code:e.code,message:e.message});return{ok:false,status:e.code==='42501'?403:422,text:async()=>JSON.stringify({code:e.code,message:e.message})};}
 }});
 server=http.createServer(async(req,res)=>{const pathname=new URL(req.url,'http://localhost').pathname;
  if(pathname.startsWith('/api/control-v1/')){let raw='';for await(const chunk of req)raw+=chunk;const adapter={setHeader:(k,v)=>res.setHeader(k,v),status(s){res.statusCode=s;return this;},json(v){res.setHeader('Content-Type','application/json');res.end(JSON.stringify(v));}};return handler({method:req.method,url:pathname,headers:{authorization:req.headers.authorization},body:JSON.parse(raw||'{}')},adapter);}
  if(pathname==='/admin.html'){
   let html=fs.readFileSync(path.join(root,'admin.html'),'utf8').replace(/<script\b[^>]*>[\s\S]*?<\/script>/gi,'').replace(/<link[^>]+(?:fonts.googleapis|preconnect)[^>]*>/gi,'');
   const boot=`window.FIXEO_ISOLATED=true;window.FixeoSupabaseClient={client:{auth:{getSession:async()=>({data:{session:{access_token:'synthetic.isolated.token',user:{id:'${u(3)}'}}}})},from:table=>{if(table!=='users')throw Error('UNEXPECTED_DIRECT_READ');return{select:()=>({eq:()=>({single:async()=>({data:{role:'admin'}})})})};}}};`;
   html=html.replace('</body>',`<script>${boot}</script>`+['fixeo-control-client-v1.js','admin-fixeo-registers.js','admin-fixeo-dossier.js','admin-fixeo-operations.js','admin-rafi-decision-center.js','admin-control-os-clean.js'].map(x=>`<script src="/js/${x}"></script>`).join('')+'</body>');res.setHeader('Content-Type','text/html');return res.end(html);
  }
  const file=path.resolve(root,'.'+decodeURIComponent(pathname));if(!file.startsWith(root+path.sep)||!fs.existsSync(file)||!fs.statSync(file).isFile()){res.statusCode=404;return res.end();}res.setHeader('Content-Type',file.endsWith('.css')?'text/css':file.endsWith('.js')?'application/javascript':file.endsWith('.png')?'image/png':'application/octet-stream');fs.createReadStream(file).pipe(res);
 });
 await new Promise(r=>server.listen(0,'127.0.0.1',r));browser=await chromium.launch({headless:true});const page=await browser.newPage({viewport:{width:1440,height:1000}});page.on('pageerror',e=>errors.push(e.message));
 await page.route('**/*',route=>route.request().url().startsWith('http://127.0.0.1:')?route.continue():route.abort());
 const goto=async view=>{await page.evaluate(v=>{FixeoDossier.close();FixeoAdmin.navigate(v);},view);await page.waitForFunction(v=>document.getElementById('register-'+v+'-state').textContent.startsWith('FRESH'),view);};
 const dossier=async(type,id)=>{await page.evaluate(({type,id})=>FixeoDossier.open(type,id),{type,id});await page.waitForSelector('#dossier-register');};
 const cancel=async()=>{await page.getByRole('button',{name:'Vérifier les préconditions et voir l’aperçu'}).click();await page.waitForSelector('dialog[open]');assert.equal(executions,0);await page.getByRole('button',{name:'Revenir',exact:true}).click();await page.waitForFunction(()=>document.getElementById('rafi-action-result').textContent.includes('annulée'));assert.equal(executions,0);};
 fs.mkdirSync(out,{recursive:true});await page.goto('http://127.0.0.1:'+server.address().port+'/admin.html?view=network');await page.waitForSelector('#network-list .register-row');assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));assert.ok(!(await page.locator('#network-list').innerText()).includes('PRIVATE EMPLOYEE'));checks.push('people_desktop_real_read_projection');await page.screenshot({path:path.join(out,'people-desktop.png')});
 await page.evaluate(eid=>FixeoRegisters.setContext('network',{type:'worker',enterprise_id:eid}),u(30));await page.waitForFunction(()=>document.querySelectorAll('#network-list .register-row').length===1);await page.locator('#network-list .register-row').click();await page.waitForSelector('#dossier-register');assert.match(await page.locator('#dossier-register').innerText(),/Membership canonique/);assert.ok(!(await page.locator('#drawer').innerText()).includes('PRIVATE EMPLOYEE'));await page.getByRole('button',{name:'Ouvrir Operations dans cette entreprise',exact:true}).click();await page.waitForFunction(()=>document.getElementById('ops-context').textContent.includes('enterprise_id'));checks.push('enterprise_workforce_dossier_and_operations_context');
 await goto('trust');await page.locator('#trust-list [data-id="'+u(80)+'"]').click();await page.waitForSelector('#dossier-register');assert.match(await page.locator('#dossier-register').innerText(),/Contact vérifié/);await page.getByRole('button',{name:'Préparer l’approbation',exact:true}).click();await page.locator('textarea[name=reason]').fill('Revue synthétique isolée du claim');await cancel();checks.push('claims_evidence_prepare_confirmation_cancel');await page.screenshot({path:path.join(out,'trust-dossier-desktop.png')});
 await goto('reservations');await page.locator('#reservations-list [data-id="'+quote+'"]').click();await page.waitForSelector('#dossier-register');assert.match(await page.locator('#drawer-facts').innerText(),/Réparation synthétique isolée/);await page.getByRole('button',{name:'Préparer l’approbation',exact:true}).click();await page.locator('textarea[name=reason]').fill('Périmètre synthétique relu');await page.locator('[name=expires_at]').fill('2030-01-01T12:00');await cancel();checks.push('quote_scope_version_expiry_prepare_cancel');
 await goto('finance');assert.match(await page.locator('#f-validated').innerText(),/UNKNOWN/);await dossier('mission',u(200));await page.getByRole('button',{name:'Préparer une déclaration de reversement',exact:true}).click();await page.locator('[name=amount]').fill('9');await page.locator('[name=proof_reference]').fill('SYNTHETIC BROWSER NEW PROOF');await page.locator('textarea[name=reason]').fill('Déclaration synthétique relue');await cancel();checks.push('finance_declaration_governed_cancel');
 await dossier('remittance',remittance);await page.waitForSelector('[data-rafi-prepare="finance.confirm"]');assert.match(await page.locator('#dossier-register').innerText(),/SYNTHETIC BROWSER PROOF/);await page.getByRole('button',{name:'Préparer le rapprochement',exact:true}).click();await page.locator('textarea[name=reason]').fill('Preuve synthétique relue');assert.equal(await page.locator('[name=proof_reviewed]').isChecked(),false);await page.locator('[name=proof_reviewed]').check();await cancel();checks.push('remittance_proof_review_and_no_silent_mutation');await page.screenshot({path:path.join(out,'finance-dossier-desktop.png')});
 await dossier('mission',u(201));assert.match(await page.locator('#dossier-register').innerText(),/UNKNOWN/);assert.match(await page.locator('#dossier-register').innerText(),/NOT_FOUND/);assert.equal(await page.locator('[data-rafi-prepare]').count(),0);assert.match(await page.locator('#dossier-operation').innerText(),/NOT_FOUND/);checks.push('orphan_relation_unknown_without_action');
 fault=true;await dossier('mission',u(200));await page.waitForSelector('#dossier-register .error');assert.match(await page.locator('#dossier-register').innerText(),/SOURCE_TIMEOUT/);assert.match(await page.locator('#drawer-summary').innerText(),/public.missions/);fault=false;await page.getByRole('button',{name:'Relire Finance',exact:true}).click();await page.waitForSelector('[data-rafi-prepare="finance.declare"]');checks.push('finance_independent_error_and_retry');
 await page.setViewportSize({width:390,height:844});assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));await page.screenshot({path:path.join(out,'finance-dossier-mobile.png')});for(const view of ['network','trust','reservations','finance']){await goto(view);assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),view+' overflow');}await page.screenshot({path:path.join(out,'finance-mobile.png')});checks.push('all_four_registers_mobile_390_no_overflow');
 assert.deepEqual(errors,[]);assert.deepEqual(backendErrors,[{name:'control_operation_read_v1',args:{p_request_id:u(102)},code:'P0001',message:'NOT_FOUND'}]);assert.equal(executions,0);checks.push('only_expected_missing_parent_refusal_no_runtime_error_or_business_execution');
 const result={status:'PASS',checks,executions,source:'Isolated synthetic database with exact migrations, real Admin UI and canonical read RPCs; no Production credentials'};fs.writeFileSync(path.join(out,'results.json'),JSON.stringify(result,null,2));console.log(JSON.stringify({status:'PASS',checks:checks.length,executions}));
 }catch(e){console.error(e.stack);process.exitCode=1;}finally{await browser?.close();if(server)await new Promise(r=>server.close(r));await db?.close();}})();
