'use strict';
// Real Admin UI → real API handler → canonical SQL in an isolated migrated database.
const fs=require('node:fs'),path=require('node:path'),http=require('node:http'),assert=require('node:assert/strict'),{chromium}=require('playwright');
const F=require('./bloc7-fixture.cjs'),{createHandler}=require('../../api/control'),u=F.uuid,root=path.resolve(__dirname,'../..'),out=path.join(root,'docs/control-os/bloc6/evidence/browser');
let db,server,browser,fault=null,executions=0;const checks=[],errors=[],backendErrors=[];
const reply=(data,status=200)=>({ok:status<400,status,text:async()=>JSON.stringify(data)});
(async()=>{try{
 db=await F.setup();await F.seed(db);await db.exec(`INSERT INTO public.service_requests(id,city,service_category,description,status,created_at,client_profile_id,urgency) VALUES
 ('${u(100)}','Fès','plomberie','Synthetic waiting browser request','new','2026-09-05T10:00Z','${u(1)}','urgent'),
 ('${u(101)}','Fès','plomberie','Synthetic accepted browser request','assigned','2026-09-05T10:00Z','${u(1)}','normale'),
 ('${u(102)}','Fès','plomberie','Synthetic parent removed','completed','2026-09-05T10:00Z','${u(1)}','normale'),
 ('${u(103)}','Fès','plomberie','Synthetic comparison request','cancelled','2026-08-20T10:00Z','${u(1)}','normale');
 INSERT INTO public.missions(id,request_id,artisan_profile_id,status,accepted_at) VALUES('${u(200)}','${u(101)}','${u(20)}','pending','2026-09-05T11:00Z'),('${u(201)}','${u(102)}','${u(20)}','done','2026-09-05T11:00Z');
 DELETE FROM public.service_requests WHERE id='${u(102)}';UPDATE public.artisans SET city='Fès',service_category='plomberie',claimable=true WHERE id='${u(21)}';`);
 const handler=createHandler({env:{SUPABASE_URL:'https://abcdefghijklmnopqrst.supabase.co',SUPABASE_ANON_KEY:'sb_publishable_SYNTHETIC',FIXEO_STAGING_PROJECT_REF:'abcdefghijklmnopqrst'},fetchImpl:async(url,o)=>{
  if(url.endsWith('/user'))return reply({id:u(3)});const name=url.split('/').at(-1),args=JSON.parse(o.body);assert.match(name,/^control_[a-z0-9_]+_v[13]$/);const keys=Object.keys(args);assert.ok(keys.every(k=>/^p_[a-z_]+$/.test(k)));
  if(name.endsWith('_execute_v1'))executions++;
  if(fault==='network'&&name==='control_marketplace_cube_v1'&&args.p_source==='network'||fault==='cohorts'&&name==='control_marketplace_cohorts_v1')return reply({message:'SOURCE_TIMEOUT'},503);
  try{return reply((await db.query(`select public.${name}(${keys.map((k,i)=>k+'=> $'+(i+1)).join(',')}) result`,Object.values(args))).rows[0].result);}catch(e){backendErrors.push({name,code:e.code,message:e.message});return reply({code:e.code,message:e.message},e.code==='42501'?403:422);}
 }});
 server=http.createServer(async(req,res)=>{const pathname=new URL(req.url,'http://localhost').pathname;
  if(pathname.startsWith('/api/control-v1/')){let raw='';for await(const c of req)raw+=c;const adapter={setHeader:(k,v)=>res.setHeader(k,v),status(s){res.statusCode=s;return this;},json(v){res.setHeader('Content-Type','application/json');res.end(JSON.stringify(v));}};return handler({method:req.method,url:pathname,headers:{authorization:req.headers.authorization},body:JSON.parse(raw||'{}')},adapter);}
  if(pathname==='/admin.html'){let html=fs.readFileSync(path.join(root,'admin.html'),'utf8').replace(/<script\b[^>]*>[\s\S]*?<\/script>/gi,'').replace(/<link[^>]+(?:fonts.googleapis|preconnect)[^>]*>/gi,'');
   const boot=`window.FIXEO_ISOLATED=true;window.FixeoSupabaseClient={client:{auth:{getSession:async()=>({data:{session:{access_token:'synthetic.isolated.token',user:{id:'${u(3)}'}}}})},from:table=>{if(table!=='users')throw Error('UNEXPECTED_DIRECT_READ');return{select:()=>({eq:()=>({single:async()=>({data:{role:'admin'}})})})};}}};`;
   html=html.replace('</body>',`<script>${boot}</script>`+['fixeo-control-client-v1.js','admin-fixeo-intelligence.js','admin-fixeo-registers.js','admin-fixeo-dossier.js','admin-fixeo-operations.js','admin-rafi-decision-center.js','admin-control-os-clean.js'].map(x=>`<script src="/js/${x}"></script>`).join('')+'</body>');res.setHeader('Content-Type','text/html');return res.end(html);}
  const file=path.resolve(root,'.'+decodeURIComponent(pathname));if(!file.startsWith(root+path.sep)||!fs.existsSync(file)||!fs.statSync(file).isFile()){res.statusCode=404;return res.end();}res.setHeader('Content-Type',file.endsWith('.css')?'text/css':file.endsWith('.js')?'application/javascript':file.endsWith('.png')?'image/png':'application/octet-stream');fs.createReadStream(file).pipe(res);
 });
 await new Promise(r=>server.listen(0,'127.0.0.1',r));browser=await chromium.launch({headless:true});const page=await browser.newPage({viewport:{width:1440,height:1000}});page.on('pageerror',e=>errors.push(e.message));await page.route('**/*',r=>r.request().url().startsWith('http://127.0.0.1:')?r.continue():r.abort());fs.mkdirSync(out,{recursive:true});
 await page.goto('http://127.0.0.1:'+server.address().port+'/admin.html?view=intelligence');await page.waitForFunction(()=>document.getElementById('intel-state')?.textContent==='FRESH');assert.equal(await page.locator('[data-intel-cell]').count(),1);assert.match(await page.locator('#intel-integrity').innerText(),/1 mission.*UNKNOWN/);assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));checks.push('desktop_cube_real_API_SQL_and_orphan_unattributed');await page.screenshot({path:path.join(out,'cube-desktop.png')});
 await page.locator('[data-intel-cell]').click();assert.match(await page.locator('#intel-activation').innerText(),/FAIT.*INFERENCE/s);await page.locator('[data-intel-pop=waiting]').first().click();await page.waitForSelector('#intel-people [data-intel-dossier]');assert.equal(await page.locator('#intel-people [data-intel-dossier]').count(),1);await page.locator('#intel-people [data-intel-dossier]').click();await page.waitForSelector('#dossier-operation');assert.match(await page.locator('#drawer').innerText(),/public.service_requests/);checks.push('exact_population_to_acquired_dossier_and_operations');await page.evaluate(()=>FixeoDossier.close());
 await page.locator('[data-intel-pop=verification_ready]').click();await page.waitForFunction(id=>document.querySelector('#intel-people [data-intel-dossier]')?.dataset.id===id,u(20));await page.locator('#intel-people [data-intel-dossier]').click();await page.waitForSelector('[data-rafi-prepare="artisan.verify"]');await page.locator('[data-rafi-prepare="artisan.verify"]').click();await page.locator('textarea[name=reason]').fill('Synthetic verification review, no execution');await page.getByRole('button',{name:'Vérifier les préconditions et voir l’aperçu'}).click();await page.waitForSelector('dialog[open]');await page.getByRole('button',{name:'Revenir',exact:true}).click();assert.equal(executions,0);checks.push('activation_to_real_Trust_preview_confirmation_cancel');await page.evaluate(()=>FixeoDossier.close());
 await page.locator('[data-intel-coverage]').click();await page.waitForFunction(()=>document.getElementById('intel-coverage').textContent.includes('CHECKED'));assert.match(await page.locator('#intel-coverage').innerText(),/dispatch_preview_v22/);assert.equal(executions,0);checks.push('bounded_canonical_coverage_read_no_dispatch');
 await page.locator('[data-intel-cohorts]').click();await page.waitForFunction(()=>document.getElementById('intel-cohorts').textContent.includes('Comparaison'));assert.match(await page.locator('#intel-cohorts').innerText(),/SMALL_SAMPLE/);assert.match(await page.locator('#intel-cohorts').innerText(),/Wilson/);assert.match(await page.locator('#intel-cohorts').innerText(),/Délai d’exécution UNKNOWN/);checks.push('cohorts_horizon_denominators_delays_uncertainty');await page.locator('#intel-cohorts').scrollIntoViewIfNeeded();await page.screenshot({path:path.join(out,'cohorts-desktop.png')});
 fault='cohorts';await page.locator('[data-intel-cohorts]').click();await page.waitForFunction(()=>document.getElementById('intel-cohorts').textContent.includes('SOURCE ERROR'));assert.equal(await page.locator('[data-intel-cell]').count(),1);fault=null;checks.push('cohort_error_preserves_other_sources');
 fault='network';await page.evaluate(()=>FixeoIntelligence.refresh(true));await page.waitForFunction(()=>document.getElementById('intel-state').textContent==='PARTIAL');assert.match(await page.locator('#intel-cells').innerText(),/UNKNOWN profils/);fault=null;await page.evaluate(()=>FixeoIntelligence.refresh(true));await page.waitForFunction(()=>document.getElementById('intel-state').textContent==='FRESH');checks.push('partial_network_not_zero_and_recovery');
 await page.evaluate(()=>FixeoAdmin.navigate('rafi'));await page.waitForFunction(()=>document.querySelectorAll('#rafi-network-plan [data-rafi-decision]').length>0);await page.locator('#rafi-network-plan [data-rafi-decision]').first().click();await page.getByRole('button',{name:'Ouvrir Marketplace Intelligence filtré'}).click();await page.waitForFunction(()=>document.getElementById('intel-state').textContent==='FRESH');assert.ok((await page.locator('#intel-cells').innerText()).includes('fes'));checks.push('RAFI_to_normalized_intelligence_context');
 await page.setViewportSize({width:390,height:844});await page.locator('[data-intel-cell]').first().click();assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));await page.screenshot({path:path.join(out,'cube-mobile.png')});await page.locator('[data-intel-cohorts]').click();await page.waitForFunction(()=>document.getElementById('intel-cohorts').textContent.includes('Comparaison'));await page.locator('#intel-cohorts').scrollIntoViewIfNeeded();assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));await page.screenshot({path:path.join(out,'cohorts-mobile.png')});checks.push('mobile_390_cube_and_cohorts_no_overflow');
 assert.deepEqual(errors,[]);assert.deepEqual(backendErrors,[]);assert.equal(executions,0);checks.push('no_runtime_SQL_error_or_business_execution');const result={status:'PASS',checks,executions,environment:'isolated synthetic SQL, real UI and handler; no Production account or fixture'};fs.writeFileSync(path.join(out,'results.json'),JSON.stringify(result,null,2));console.log(JSON.stringify({status:'PASS',checks:checks.length,executions}));
 }catch(e){console.error(e.stack);if(backendErrors.length)console.error(JSON.stringify(backendErrors));process.exitCode=1;}finally{await browser?.close();if(server)await new Promise(r=>server.close(r));await db?.close();}})();
