'use strict';
const {test}=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path');
const {JSDOM}=require('jsdom');const R=require('../../api/control/rafi-decisions');
const root=path.resolve(__dirname,'../..'),id='00000000-0000-4000-8000-000000000001';
const tick=()=>new Promise(resolve=>setImmediate(resolve));
function fixture(kind='request.waiting'){
 const now=Date.now(),as_of=new Date(now).toISOString();
 const observation={kind,target_type:kind==='network.cohort'?'cohort':'request',target_id:kind==='network.cohort'?null:id,city:'Fès',service_category:'plomberie',count:2,created_at:new Date(now-180*60000).toISOString(),reference:'public.service_requests',facts:kind==='network.cohort'?{profiles:2,available_profiles:0,to_verify:1,unclaimed:1,urgent_count:1,total_waiting:2,location_known:true,verify_ids:[id],claim_ids:[id]}:{status:'new',urgency:'urgent'}};
 return R.build(Object.fromEntries(R.SOURCES.map(s=>[s,R.sourceState(s,{contract_version:'rafi-observations-v1',source:s,as_of,total_observations:s===(kind==='network.cohort'?'network':'operations')?1:0,observations:s===(kind==='network.cohort'?'network':'operations')?[observation]:[],has_more:false},null,now)])),{now});
}
function page(snapshot=fixture(),override){
 const dom=new JSDOM(fs.readFileSync(path.join(root,'admin.html'),'utf8'),{url:'https://test.vercel.app/admin.html',runScripts:'outside-only',pretendToBeVisual:true});
 const calls=[],w=dom.window;w.setInterval=()=>0;
 w.FixeoAdmin={navigate:view=>calls.push({navigate:view})};
 w.FixeoControl={request:async(operation,body)=>{calls.push({operation,body});if(override){const value=await override(operation,body);if(value!==undefined)return value;}
   if(operation==='decisions')return snapshot;
   if(operation==='dossier')return {entity_type:body.type,id:body.id,as_of:new Date().toISOString(),summary:{id:body.id,status:'new',city:'Fès',service_category:'plomberie'},relations:[],timeline:[]};
   if(operation==='dossier-section')return {items:[],has_more:false,as_of:new Date().toISOString()};
   if(operation==='operations')return {items:[],has_more:false,next_cursor:null,as_of:new Date().toISOString()};
   if(operation==='network-context')return {items:[{id,city:'Fès',name:'Synthetic Profile'}],has_more:false,next_cursor:null};
   throw Error('Unexpected read '+operation);
 },command:async()=>{throw Error('Unexpected mutation');}};
 for(const file of ['admin-fixeo-dossier.js','admin-fixeo-operations.js','admin-rafi-decision-center.js'])w.eval(fs.readFileSync(path.join(root,'js',file),'utf8'));
 return {dom,w,calls,close:()=>w.close()};
}
test('RAFI UI renders computed top priority, explainability and escaping without executing actions',async()=>{const data=fixture();data.decisions[0].title='<img src=x onerror=alert(1)> urgence';const p=page(data);try{await p.w.FixeoRafi.load();assert.equal(p.w.document.querySelector('#rafi-brief').textContent,data.decisions[0].title);assert.equal(p.w.document.querySelector('#rafi-brief img'),null);await p.w.FixeoRafi.openDecision(data.decisions[0].decision_id);const text=p.w.document.querySelector('#drawer').textContent;for(const expected of ['Pourquoi maintenant','INFÉRENCE','FAITS','request.dispatch','Suivi / audit'])assert.ok(text.includes(expected),expected);assert.equal(p.calls.filter(c=>c.operation==='dossier').length,1);}finally{p.close();}});
test('RAFI UI contextual network navigation retains exact filters and uses the paged RPC',async()=>{const data=fixture('network.cohort'),p=page(data);try{await p.w.FixeoRafi.load();const d=data.decisions.find(d=>d.decision_type==='network.verify');await p.w.FixeoRafi.openDecision(d.decision_id);p.w.document.querySelector('[data-rafi-context]').click();await tick();const call=p.calls.find(c=>c.operation==='network-context');assert.equal(call.body.city,'Fès');assert.equal(call.body.trade,'plomberie');assert.equal(call.body.state,'unverified');assert.equal(call.body.classification,'all');assert.equal(p.w.document.getElementById('network-list').hidden,true);p.w.document.querySelector('[data-rafi-clear-context]').click();assert.equal(p.w.document.getElementById('network-list').hidden,false);}finally{p.close();}});
test('RAFI UI last completed dossier cannot overwrite a more recent selection',async()=>{let release;const p=page(fixture(),async(op,body)=>{if(op==='dossier'&&body.id===id)return new Promise(resolve=>release=resolve);});try{const first=p.w.FixeoRafi.openDossier('request',id);await tick();await p.w.FixeoRafi.openDossier('request','other');release({summary:{name:'OBSOLETE'},relations:[],timeline:[]});await first;assert.ok(!p.w.document.getElementById('drawer-summary').textContent.includes('OBSOLETE'));assert.ok(p.w.document.getElementById('drawer-sub').textContent.includes('other'));}finally{p.close();}});
test('RAFI UI network failure retains explicitly stale observations; permission denial clears them',async()=>{let failure=null;const p=page(fixture(),async op=>{if(op==='decisions'&&failure)throw Error(failure);});try{await p.w.FixeoRafi.load();failure='SOURCE_TIMEOUT';await p.w.FixeoRafi.load();assert.equal(p.w.document.getElementById('rafi-state').textContent,'STALE');failure='FORBIDDEN';await p.w.FixeoRafi.load();assert.equal(p.w.document.getElementById('rafi-state').textContent,'UNAVAILABLE');assert.equal(p.w.document.querySelectorAll('[data-rafi-decision]').length,0);}finally{p.close();}});
test('RAFI UI presents independent priority and universe filters with explicit empty state',async()=>{const p=page(fixture());try{await p.w.FixeoRafi.load();const field=p.w.document.getElementById('rafi-priority-filter');field.value='P3';field.dispatchEvent(new p.w.Event('change',{bubbles:true}));assert.match(p.w.document.getElementById('rafi-plan').textContent,/Aucune autre décision/);}finally{p.close();}});
test('An empty cached briefing expires in RAFI and Control Tower without becoming a healthy zero',async()=>{const data=fixture();data.decisions=[];data.status='FRESH';for(const s of Object.values(data.sources)){s.as_of=new Date(Date.now()-61000).toISOString();s.status='FRESH';}const p=page(data);try{await p.w.FixeoRafi.load();assert.equal(p.w.document.getElementById('rafi-state').textContent,'STALE');assert.equal(p.w.document.querySelectorAll('.rafi-source[data-state="STALE"]').length,5);assert.match(p.w.document.getElementById('overview-signals').textContent,/Lecture périmée/);assert.ok(!p.w.document.getElementById('overview-priority').textContent.includes('Aucune priorité RAFI détectée'));}finally{p.close();}});
test('Admin shell loads only active-surface lists and the canonical RAFI briefing',async()=>{
 const p=page(fixture()),tables=[];p.w.FixeoControl.summary=async()=>({});
 p.w.FixeoSupabaseClient={client:{auth:{getSession:async()=>({data:{session:{user:{id}}}})},from:table=>({select(){return this;},eq(){return this;},single:async()=>({data:{role:'admin'}}),order(){return this;},limit(){return this;},abortSignal:async()=>{tables.push(table);return {data:[]};}})}};
 try{p.w.eval(fs.readFileSync(path.join(root,'js/admin-control-os-clean.js'),'utf8'));p.w.dispatchEvent(new p.w.Event('load'));await tick();await tick();assert.deepEqual([...new Set(tables)],['missions']);tables.length=0;p.w.FixeoAdmin.navigate('rafi');await tick();assert.deepEqual(tables,[]);p.w.FixeoAdmin.navigate('operations');await tick();await tick();assert.deepEqual(tables,[]);assert.ok(p.calls.some(c=>c.operation==='operations'));assert.ok(p.w.document.getElementById('sec-operations').classList.contains('active'));assert.ok(p.calls.some(c=>c.operation==='decisions'));}finally{p.close();}
});
test('RAFI command retry keeps the same preview and idempotency key after an uncertain response',async()=>{
 const dom=new JSDOM('<body></body>',{runScripts:'outside-only'}),w=dom.window,requests=[];let failed=false;
 w.HTMLDialogElement.prototype.showModal=function(){this.open=true;};w.HTMLDialogElement.prototype.close=function(){this.open=false;};
 w.FixeoSupabaseClient={client:{auth:{getSession:async()=>({data:{session:{access_token:'synthetic.token',user:{id}}}})}}};
 w.AbortSignal=AbortSignal;w.fetch=async(url,o)=>{const body=JSON.parse(o.body);requests.push({url,body});if(url.endsWith('preview'))return {ok:true,json:async()=>({preview_id:id,current:{id,status:'new'},target:{id,type:'request'},preconditions:['admin'],effect:{},expires_at:new Date(Date.now()+300000).toISOString()})};if(!failed){failed=true;throw Error('NETWORK_RESPONSE_LOST');}return {ok:true,json:async()=>({ok:true,verified:{id},audit_id:id,correlation_id:id,idempotency_key:body.idempotency_key})};};
 w.eval(fs.readFileSync(path.join(root,'js/fixeo-control-client-v1.js'),'utf8'));
 try{let result=w.FixeoControl.command('artisan.verify',id,{});await tick();w.document.querySelector('dialog button.primary').click();await assert.rejects(result,/NETWORK_RESPONSE_LOST/);result=w.FixeoControl.command('artisan.verify',id,{});await tick();w.document.querySelector('dialog button.primary').click();await result;assert.equal(requests.filter(r=>r.url.endsWith('preview')).length,1);const executions=requests.filter(r=>r.url.endsWith('execute'));assert.equal(executions.length,2);assert.equal(executions[0].body.idempotency_key,executions[1].body.idempotency_key);assert.equal(executions[0].body.preview_id,executions[1].body.preview_id);}finally{w.close();}
});
