'use strict';
const {test,before,after}=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path');
const {baseline,migrate,actor,uuid,sql}=require('./bloc34-fixture.cjs'),{JSDOM}=require('jsdom');
const root=path.resolve(__dirname,'../..'),engine=require('../../api/control/rafi-decisions');
const guard=fs.readFileSync(path.join(root,'supabase/migrations/20260929142337_control_os_b34_settlement_integrity_guard.sql'),'utf8');
const statuses=['cancelled','offered','expired','pending','expired','pending','done','offered','pending','offered','cancelled','offered','offered','offered','done','done','offered','offered','offered'];
let db,oldPreview,oldFunctions,oldSecurity,oldRows;
const rpc=async(name,args)=>(await db.query(`select public.${name}(${args.map((_,i)=>'$'+(i+1)).join(',')}) result`,args)).rows[0].result;
const dossier=(i,section='identity')=>rpc('control_dossier_section_v1',['mission',uuid(i),section,null,25]);
const payload={final_price:100,expected_final_price:null,reason:'Synthetic local parent integrity'};
const preview=(id=206)=>rpc('control_action_preview_v1',['mission.settle',uuid(id),payload,uuid(901)]);
const execute=(p,key=902)=>rpc('control_action_execute_v1',[p.preview_id,true,uuid(key)]);
const functions=`select n.nspname,p.proname,pg_get_function_identity_arguments(p.oid) args,md5(pg_get_functiondef(p.oid)) hash,p.proacl::text acl,p.prosecdef,p.proconfig,pg_get_userbyid(p.proowner) owner from pg_proc p join pg_namespace n on n.oid=p.pronamespace where n.nspname in('public','fixeo_private') and p.prokind='f' order by n.nspname,p.proname,args`;
const security=`select c.relname,c.relacl::text,c.relrowsecurity,(select jsonb_agg(to_jsonb(p) order by p.policyname) from pg_policies p where p.schemaname=n.nspname and p.tablename=c.relname) policies from pg_class c join pg_namespace n on n.oid=c.relnamespace where n.nspname in('public','fixeo_private') and c.relkind in('r','v') order by n.nspname,c.relname`;
async function business(){return (await db.query(`select jsonb_build_object('missions',(select jsonb_agg(to_jsonb(m) order by id) from public.missions m),'requests',(select jsonb_agg(to_jsonb(r) order by id) from public.service_requests r),'remittances',(select jsonb_agg(to_jsonb(x) order by id) from public.commission_remittances_v1 x)) state`)).rows[0].state;}
async function denied(fn,pattern){await db.exec('SAVEPOINT refusal');let error;try{await fn();}catch(e){error=e;}await db.exec('ROLLBACK TO SAVEPOINT refusal; RELEASE SAVEPOINT refusal');assert.ok(error,'Expected refusal');assert.match(error.message,pattern);}
function tx(name,fn){test(name,async()=>{await db.exec('RESET ROLE; BEGIN');try{await actor(db,3);await fn();}finally{await db.exec('ROLLBACK; RESET ROLE');}});}
before(async()=>{
 db=await baseline();await migrate(db,{settlementGuard:false});
 await db.exec(fs.readFileSync(path.join(root,'supabase/migrations/20260929021750_control_os_b2_rafi_reads.sql'),'utf8'));
 await db.exec(`INSERT INTO auth.users(id) VALUES('${uuid(1)}'),('${uuid(2)}'),('${uuid(3)}');
 INSERT INTO public.users(id,role,full_name) VALUES('${uuid(1)}','client','Synthetic client'),('${uuid(2)}','artisan','Synthetic artisan'),('${uuid(3)}','admin','Synthetic admin');
 INSERT INTO public.profiles(id,role) VALUES('${uuid(1)}','client');
 SELECT set_config('request.jwt.claims','{"sub":"${uuid(3)}","role":"authenticated"}',false);
 ALTER TABLE public.service_requests DISABLE TRIGGER USER;
 INSERT INTO public.service_requests(id,client_profile_id,service_category,city,description,status) VALUES ${statuses.map((_,i)=>`('${uuid(100+i)}','${uuid(1)}','plomberie','Local','Synthetic historical request','new')`).join(',')};
 ALTER TABLE public.service_requests ENABLE TRIGGER USER;
 INSERT INTO public.artisans(id,owner_user_id,full_name,phone,city,service_category) VALUES('${uuid(20)}','${uuid(2)}','Synthetic artisan','+000000000001','Local','plomberie');
 -- Local historical setup only; all triggers are restored before guard/execution tests.
 ALTER TABLE public.missions DISABLE TRIGGER USER;
 INSERT INTO public.missions(id,request_id,artisan_profile_id,status) VALUES ${statuses.map((s,i)=>`('${uuid(200+i)}','${uuid(100+i)}','${uuid(20)}','${s}')`).join(',')};
 ALTER TABLE public.missions ENABLE TRIGGER USER;
 DELETE FROM public.service_requests;
 INSERT INTO public.service_requests(id,client_profile_id,service_category,city,description,status) VALUES('${uuid(119)}','${uuid(1)}','plomberie','Local','Synthetic valid request','completed');
 INSERT INTO public.missions(id,request_id,artisan_profile_id,status,completed_at) VALUES('${uuid(219)}','${uuid(119)}','${uuid(20)}','done',now());`);
 await db.exec(sql);await actor(db,3);oldPreview=await preview();await db.exec('RESET ROLE');
 oldFunctions=(await db.query(functions)).rows;oldSecurity=(await db.query(security)).rows;oldRows=await business();await db.exec(guard);
});
after(async()=>db?.close());
tx('P0 migration modifies only two canonical function bodies, preserving owner/ACL/RLS and every business row',async()=>{await db.exec('RESET ROLE');const now=(await db.query(functions)).rows;assert.equal(now.length,oldFunctions.length);const changed=[];for(let i=0;i<now.length;i++){if(now[i].hash!==oldFunctions[i].hash)changed.push(now[i].proname);const {hash:a,...left}=now[i],{hash:b,...right}=oldFunctions[i];assert.deepEqual(left,right);}assert.deepEqual(changed.sort(),['admin_settle_mission_v1','control_action_preview_v1']);assert.deepEqual((await db.query(security)).rows,oldSecurity);assert.deepEqual(await business(),oldRows);});
tx('P0 missing parent preview is refused before even a technical preview is written (former FAIL)',async()=>{await db.exec('RESET ROLE');const before=(await db.query('select count(*) n from fixeo_private.control_action_previews_v1')).rows[0].n;await actor(db,3);for(let retry=0;retry<3;retry++)await denied(()=>preview(),/REQUEST_NOT_FOUND/);await db.exec('RESET ROLE');assert.equal((await db.query('select count(*) n from fixeo_private.control_action_previews_v1')).rows[0].n,before);assert.deepEqual(await business(),oldRows);});
tx('P0 mutation authority itself rejects absent parent, independent of the preview guard',async()=>{await db.exec('RESET ROLE');await denied(()=>rpc('admin_settle_mission_v1',[uuid(206),100,null,payload.reason]),/REQUEST_NOT_FOUND/);assert.deepEqual(await business(),oldRows);});
tx('P0 pre-patch preview cannot settle an orphan; retry is deterministic and only a failed audit persists (former FAIL)',async()=>{const result=await execute(oldPreview);assert.equal(result.ok,false);assert.equal(result.code,'REQUEST_NOT_FOUND');assert.ok(result.audit_id);assert.deepEqual(await execute(oldPreview),result);await db.exec('RESET ROLE');assert.deepEqual(await business(),oldRows);const audit=(await db.query('select result,actor_id from fixeo_private.authority_audit_events_v1 where id=$1',[result.audit_id])).rows[0];assert.equal(audit.result,'failed');assert.equal(audit.actor_id,uuid(3));assert.equal(Number((await db.query("select count(*) n from fixeo_private.authority_audit_events_v1 where idempotency_key=$1 and action='execute'",[uuid(902)])).rows[0].n),1);});
tx('P0 valid request retains canonical price, commission, audit and idempotent result',async()=>{const p=await preview(219),r=await execute(p);assert.equal(r.ok,true);assert.equal(Number(r.verified.final_price),100);assert.equal(Number(r.verified.commission_amount),15);assert.equal(r.verified.status,'done');assert.equal(r.verified.request_status,'completed');assert.deepEqual(await execute(p),r);assert.ok(r.audit_id);});
tx('P0 deleted parent after a valid preview causes refusal with no partial business mutation',async()=>{const p=await preview(219);await db.exec(`RESET ROLE; DELETE FROM public.service_requests WHERE id='${uuid(119)}'`);const before=await business();await actor(db,3);const r=await execute(p);assert.equal(r.ok,false);assert.equal(r.code,'STALE_PREVIEW');assert.deepEqual(await execute(p),r);await db.exec('RESET ROLE');assert.deepEqual(await business(),before);});
tx('P0 missing parent remains refused even on an apparent idempotent price replay',async()=>{await db.exec(`RESET ROLE; ALTER TABLE public.missions DISABLE TRIGGER USER; UPDATE public.missions SET final_price=100 WHERE id='${uuid(206)}'; ALTER TABLE public.missions ENABLE TRIGGER USER;`);const before=await business();await denied(()=>rpc('admin_settle_mission_v1',[uuid(206),100,100,payload.reason]),/REQUEST_NOT_FOUND/);assert.deepEqual(await business(),before);});
tx('P0 anon/non-admin/service_role are refused and canonical authority is not exposed directly',async()=>{for(const [id,role] of [[1,'anon'],[1,'authenticated'],[2,'authenticated'],[3,'service_role']]){await actor(db,id,role);await denied(()=>preview(219),/permission denied|FORBIDDEN/);await denied(()=>execute(oldPreview),/permission denied|FORBIDDEN/);await denied(()=>rpc('admin_settle_mission_v1',[uuid(219),100,null,payload.reason]),/permission denied/);}await actor(db,3);await denied(()=>rpc('admin_settle_mission_v1',[uuid(219),100,null,payload.reason]),/permission denied/);});
tx('P0 all 19 orphan dossiers preserve canonical status, reference and UNKNOWN',async()=>{for(let i=0;i<19;i++){const d=await dossier(200+i);assert.equal(d.summary.status,statuses[i]);assert.equal(d.summary.request_status,null);assert.equal(d.request_id,uuid(100+i));const r=await dossier(200+i,'relations'),t=await dossier(200+i,'timeline');assert.ok(r.items.some(x=>x.type==='artisan'));assert.ok(!r.items.some(x=>x.type==='request'));assert.ok(Array.isArray(t.items));}});
tx('P0 missing operation context stays NOT_FOUND and queue contains only its one real request',async()=>{await denied(()=>rpc('control_operation_read_v1',[uuid(106)]),/NOT_FOUND/);const q=await rpc('control_operations_page_v1',[{},null,25]);assert.equal(q.items.length,1);assert.equal(q.items[0].id,uuid(119));});
tx('P0 RAFI keeps 19 inconsistencies as OPEN-only decisions and Finance excludes missing parents',async()=>{const ops=await rpc('control_rafi_source_v1',['operations','all']),missing=ops.observations.filter(o=>o.kind==='mission.inconsistent');assert.equal(missing.length,19);for(const o of missing)assert.equal(o.facts.request_status,null);const decisions=engine.build({operations:engine.sourceState('operations',ops,null)}).decisions.filter(d=>d.decision_type==='mission.inconsistent');assert.equal(decisions.length,19);for(const d of decisions){assert.equal(d.priority,'P1');assert.equal(d.actionability.capability,null);assert.equal(d.actionability.mode,'OPEN');assert.equal(d.actionability.execution_authorized,false);assert.equal(d.impact.kind,'INFERENCE');}const finance=await rpc('control_rafi_source_v1',['finance','all']);assert.equal(finance.observations.length,1);assert.equal(finance.observations[0].target_id,uuid(219));});
tx('P0 orphan UI remains readable with UNKNOWN, NOT_FOUND and no mutation control',async()=>{const dom=new JSDOM(fs.readFileSync(path.join(root,'admin.html'),'utf8'),{url:'https://isolated.invalid/admin.html',runScripts:'outside-only',pretendToBeVisual:true}),w=dom.window;let mutations=0;w.FixeoControl={request:async(op,b)=>{if(op==='dossier')return rpc('control_dossier_section_v1',[b.type,b.id,'identity',null,25]);if(op==='dossier-section')return rpc('control_dossier_section_v1',[b.type,b.id,b.section,b.after,b.limit]);if(op==='operation-context')throw Error('NOT_FOUND');throw Error(op);},command:async()=>{mutations++;throw Error('UNEXPECTED_MUTATION');}};try{w.eval(fs.readFileSync(path.join(root,'js/admin-fixeo-dossier.js'),'utf8'));for(let i=0;i<19;i++){await w.FixeoDossier.open('mission',uuid(200+i));assert.match(w.document.getElementById('drawer-summary').textContent,new RegExp(statuses[i]));const fact=[...w.document.querySelectorAll('#drawer-facts .fact')].find(el=>el.querySelector('span')?.textContent==='État demande');assert.equal(fact.querySelector('b').textContent,'UNKNOWN');assert.match(w.document.getElementById('dossier-operation').textContent,/SOURCE ERROR.*NOT_FOUND/);assert.equal(w.document.querySelectorAll('[data-rafi-prepare]').length,0);}assert.equal(mutations,0);}finally{w.close();}});
