const test=require('node:test');const assert=require('node:assert/strict');const fs=require('node:fs');const path=require('node:path');const root=path.resolve(__dirname,'../..');const read=p=>fs.readFileSync(path.join(root,p),'utf8');
const html=read('artisan-profile.html'),js=read('js/fixeo-artisan-profile-v4.js'),css=read('css/fixeo-artisan-profile-v4.css');
test('B2: V4 is mounted only from artisan-profile.html',()=>{assert.match(html,/fixeo-artisan-profile-v4\.css\?v=fxp4-b2/);assert.match(html,/fixeo-artisan-profile-v4\.js\?v=fxp4-b2/);assert.match(js,/public-artisan-root/);assert.match(css,/body\.fx-profile-v4/)});
test('B2: V4 consumes only canonical B1 resolver',()=>{assert.match(js,/\.rpc\('resolve_artisan_public_profile_v4'/);assert.match(js,/contract_version!=='artisan_public_profile_v4'/);assert.doesNotMatch(js,/\.from\('artisans'\)/)});
test('B2: no local pricing or fabricated review/trust authority',()=>{assert.doesNotMatch(js,/MAR_PRICES|SERVICE_PRICING|price_from|starting_price|150.?600|Estimation marché|FIXEO AI ESTIMATION/);assert.doesNotMatch(js,/trustScore\s*:\s*90/);assert.match(js,/verified_review_count/);assert.match(js,/verified_average_rating/)});
test('B2: missing photos use deterministic non-human identity',()=>{assert.match(js,/fxp4-avatar fallback/);assert.match(js,/initiales|ini\(/i);assert.doesNotMatch(js,/random\(/i)});
test('B2: booking remains legacy engine until Bloc 3',()=>{assert.match(js,/FixeoReservation&&typeof w\.FixeoReservation\.open/);assert.match(js,/id="public-artisan-action"/);assert.match(js,/Demander une intervention/)});
test('B2: RPC failure is a no-op legacy fallback',()=>{assert.match(js,/if\(res\.error\|\|!res\.data\|\|res\.data\.contract_version!=='artisan_public_profile_v4'\)return/);assert.match(js,/legacy fallback/)});
test('B2: mobile sticky CTA and desktop trust surface exist',()=>{assert.match(css,/\.fxp4-mobile/);assert.match(css,/@media\(max-width:800px\)/);assert.match(js,/Confiance FIXEO/);assert.match(js,/Disponibilité à confirmer/)});

test('B2 postflight: V4 waits for Supabase client instead of silently abandoning render',()=>{assert.match(js,/SUPABASE_CLIENT_TIMEOUT/);assert.match(js,/tries\+\+<30/);assert.match(js,/setTimeout\(r,100\)/)});
test('B2 postflight: profile CTA can only open targeted FixeoReservation',()=>{assert.match(js,/targeted booking engine unavailable/);assert.match(js,/FixeoReservation&&typeof w\.FixeoReservation\.open/);assert.doesNotMatch(js,/data-open-request-form|FixeoClientRequest\.open|fx-request-flow-v4/)});
