const test=require('node:test');const assert=require('node:assert/strict');const fs=require('node:fs');const path=require('node:path');const root=path.resolve(__dirname,'../..');const read=p=>fs.readFileSync(path.join(root,p),'utf8');
const js=read('js/fixeo-artisan-profile-v4.js'),css=read('css/fixeo-artisan-profile-v4.css'),html=read('artisan-profile.html');
test('B3: premium surface replaces legacy white-card composition',()=>{for(const x of ['fxp4-professional-surface','fxp4-profile-main','fxp4-intelligence','fxp4-next'])assert.ok(js.includes(x),x);assert.match(css,/\.fxp4-professional-surface/);assert.match(css,/\.fxp4-intelligence/)});
test('B3: sparse profiles get truthful useful summary without fabricated proof',()=>{assert.match(js,/Les détails de l’intervention sont confirmés avant prise en charge/);assert.match(js,/Aucun avis vérifié affiché/);assert.doesNotMatch(js,/\b4\.9\b|\b5\.0\b|missions? réalisées?/i)});
test('B3: reviews appear only from verified review contract',()=>{assert.match(js,/verified_review_count/);assert.match(js,/verified_average_rating/);assert.match(js,/if\(n>0&&rt>0\)/)});
test('B3: internal sourcing metadata remains filtered',()=>{assert.match(js,/function publicExperience/);assert.match(js,/TIER/);assert.match(js,/facebook/);assert.match(js,/qualifier/)});
test('B3: targeted booking remains same artisan-specific engine',()=>{assert.match(js,/FixeoReservation\.open\(artisan\(p\),false\)/);assert.match(js,/data-fxp4-book/);assert.doesNotMatch(js,/FixeoClientRequest\.open/)});
test('B3: Hero WOW remains intact',()=>{assert.match(js,/fxp4-hero-wow/);assert.match(js,/id="public-artisan-action"/);assert.match(js,/Votre besoin/);assert.match(js,/Son savoir-faire/)});
test('B3: no pricing authority is introduced',()=>{assert.doesNotMatch(js,/price_min|price_max|starting_price|tarif.*MAD|\d+\s*MAD/i)});
