const test=require('node:test');const assert=require('node:assert/strict');const fs=require('node:fs');const path=require('node:path');const root=path.resolve(__dirname,'../..');const read=p=>fs.readFileSync(path.join(root,p),'utf8');
const css=read('css/fixeo-artisan-profile-v4.css'),js=read('js/fixeo-artisan-profile-v4.js'),html=read('artisan-profile.html');
const marker='/* B3.4 DESIGN MASTER FINAL — visual/UX only; Hero B2 and business logic stay canonical */';const dm=css.slice(css.indexOf(marker));
test('Design Master is isolated and does not restyle Hero B2',()=>{assert.ok(dm.startsWith(marker));assert.doesNotMatch(dm,/\.fxp4-hero-wow/);assert.match(html,/fxp4-b34dm1/);});
test('Design Master creates a continuous professional passport surface',()=>{assert.match(dm,/\.fxp4-b34 \.fxp4-professional-surface/);assert.match(dm,/\.fxp4-b34 \.fxp4-profile-main>\.fxp4-section/);assert.match(dm,/border-bottom:1px solid #ecebf0/);});
test('Performance, gallery, reviews and final CTA have distinct premium rhythm',()=>{assert.match(dm,/\.fxp4-b34 \.fxp4-metrics/);assert.match(dm,/linear-gradient\(108deg,#111218/);assert.match(dm,/\.fxp4-b34 \.fxp4-gallery/);assert.match(dm,/\.fxp4-b34 \.fxp4-reviews/);assert.match(dm,/\.fxp4-b34 \.fxp4-next/);});
test('Mobile remains compact with floating sticky CTA and reduced-motion support',()=>{assert.match(dm,/bottom:calc\(8px \+ env\(safe-area-inset-bottom\)\)/);assert.match(dm,/grid-auto-columns:88%/);assert.match(dm,/@media\(prefers-reduced-motion:reduce\)/);assert.match(css,/\.fxp4-mobile\.is-visible/);});
test('Targeted booking and sticky visibility governance remain canonical',()=>{assert.match(js,/FixeoReservation\.open\(artisan\(p\),false\)/);assert.match(js,/finalVisible/);assert.match(js,/heroVisible/);assert.match(js,/!heroVisible&&!finalVisible/);});
test('Design Master introduces no pricing authority or fabricated proof',()=>{assert.doesNotMatch(js,/price_min|price_max|starting_price|tarif.*MAD|\d+\s*MAD/i);assert.match(js,/Galerie en préparation/);assert.match(js,/Donnée en construction/);});
