'use strict';
/**
 * artisan-card-v3.js — Canonical FIXEO Artisan Card V3
 * ======================================================
 * Renders ONE static artisan profile card from structured data.
 * Clean-room component. Zero dependency on:
 *   - artisan-card-conversion-v1.css (frozen)
 *   - fixeo-local-flagship-v1.js (runtime)
 *   - fixeo-artisan-directory-v1.js (runtime)
 *   - any reservation / RAFI / booking system
 *
 * PURPOSE:
 *   Server-side/generation-time HTML for SEO V3 pages.
 *   This module is consumed by V3 generators that want to
 *   embed a static artisan card before JS hydration.
 *   It is NOT a runtime rendering engine.
 *
 * OUTPUT:
 *   A self-contained <article class="fxseo-card-v3 …"> string.
 *   No external CSS URLs, no JS event handlers, no inline scripts.
 *
 * DATA CONTRACT — FIELD CLASSIFICATION:
 *   See PUBLIC_FIELDS / buildArtisanCard() JSDoc below.
 *
 * VERSION HISTORY:
 *   v3-a1 (2026-09-10): Initial implementation.
 *   v3-a2 (2026-09-10): Task 2.4A corrections:
 *     - Issue 1: Removed legacy ?id= profile URL fallback.
 *       publicSlug is now the ONLY source for a profile CTA.
 *       id is no longer an accepted API field; it is FORBIDDEN.
 *       Rationale: SEO V3 must strengthen canonical internal linking.
 *       Propagating /artisan-profile.html?id= legacy URLs across generated
 *       SEO pages is not an approved V3 internal-link strategy.
 *     - Issue 2: Description truth-guard rewritten.
 *       Old behavior: sanitizeDesc() silently removed banned phrases
 *       (e.g. "Artisan vérifié disponible immédiatement" → "Artisan disponible")
 *       — a silent partial rewrite that could output mutilated, misleading text.
 *       New behavior: plainTextDesc() strips HTML only → normalizes whitespace →
 *       content-guard BANNED_TERMS check → if ANY banned term found: return null
 *       → description block is omitted entirely. No surgical phrase removal.
 *       Rationale: a bad description should not be silently laundered; it should
 *       be surfaced to data team and omitted from public output.
 *
 * PROFILE URL STRATEGY (v3-a2, confirmed from vercel.json):
 *   /artisan/{public_slug}   → routes to /api/artisan-profile-fn?slug=
 *   This is the ONLY canonical public artisan URL in SEO V3.
 *   Missing/invalid publicSlug → no profile CTA (graceful degradation).
 *   Legacy /artisan-profile.html?id= is NOT generated by V3.
 *
 * DESCRIPTION TRUTH-GUARD (v3-a2):
 *   Phase 1: strip HTML tags (security, no injection risk)
 *   Phase 2: normalize whitespace to plain text
 *   Phase 3: check against content-guard BANNED_TERMS (same guard as all V3 generators)
 *   Phase 4: if clean — escape and truncate to DESC_MAX_LENGTH chars
 *   Phase 5: if banned term found — return null → description block omitted
 *   This is DETECTION + OMISSION, not detection + rewrite.
 *
 * RATINGS / REVIEWS:
 *   NOT rendered. Intentional product-truth decision, mirroring the
 *   artisan-card-conversion-v1.css V3B documented rationale:
 *   "Rating is NOT displayed — only show when genuine rating>0 AND
 *   reviews>0, and the data reliability does not yet meet that bar."
 *   When data is reliable, a future task can add the rating block.
 *
 * BANNED CLAIMS (per Q2 + Q11 decisions):
 *   vérifié, qualifié, certifié (in credential context),
 *   disponible immédiatement, 24h/7, réponse garantie,
 *   devis gratuit, meilleur artisan, top artisan.
 *   Approved: "profil référencé sur FIXEO", "paiement après intervention".
 *
 * FILE: seo/generators/shared/artisan-card-v3.js
 * Version: v3-a2 · 2026-09-10
 */

// ── Content-guard integration ─────────────────────────────────────────────────
// Import BANNED_TERMS only — do not call check() (which throws); we detect
// and omit rather than throw, since a bad DB description should not abort
// the entire page generation.

const { BANNED_TERMS } = require('./content-guard');

// ── Constant maps (mirrors fixeo-local-flagship-v1.js / fixeo-artisan-directory-v1.js) ──

const SVC_LABELS = {
  plomberie:    'Plomberie',
  electricite:  'Électricité',
  serrurerie:   'Serrurerie',
  climatisation:'Climatisation',
  peinture:     'Peinture',
  menuiserie:   'Menuiserie',
  maconnerie:   'Maçonnerie',
  nettoyage:    'Nettoyage',
};

const SVC_ICONS = {
  plomberie:    '🔧',
  electricite:  '⚡',
  serrurerie:   '🔑',
  climatisation:'❄️',
  peinture:     '🎨',
  menuiserie:   '🪵',
  maconnerie:   '🧱',
  nettoyage:    '🧹',
};

// ── Description constants ─────────────────────────────────────────────────────

const DESC_MAX_LENGTH = 160; // characters before truncation with ellipsis

// ── URL-safe slug validation ──────────────────────────────────────────────────

// Valid public_slug: 4–120 lowercase alphanumeric + hyphens
const SLUG_RE = /^[a-z0-9][a-z0-9-]{2,118}[a-z0-9]$/;

// Valid HTTPS photo URL: must start with https://, no spaces or injection chars
const PHOTO_URL_RE = /^https:\/\/[^\s"'<>]+$/;

// Forbidden href schemes
const UNSAFE_HREF_RE = /^(javascript:|data:|vbscript:)/i;

// ── HTML escape ───────────────────────────────────────────────────────────────

/**
 * Escape characters that have meaning in HTML contexts.
 * Handles null/undefined safely.
 * @param {*} val
 * @returns {string}
 */
function esc(val) {
  return String(val == null ? '' : val).replace(/[&<>"']/g, c => ({
    '&': '&amp;',
    '<': '&lt;',
    '>': '&gt;',
    '"': '&quot;',
    "'": '&#39;',
  }[c]));
}

// ── URL validation helpers ────────────────────────────────────────────────────

/**
 * Validate a public_slug value.
 * @param {string} slug
 * @returns {boolean}
 */
function isValidSlug(slug) {
  return typeof slug === 'string' && SLUG_RE.test(slug);
}

/**
 * Validate a public photo URL.
 * Must be HTTPS. No data: or javascript: allowed.
 * @param {string} url
 * @returns {boolean}
 */
function isValidPhotoUrl(url) {
  if (typeof url !== 'string' || !url) return false;
  if (UNSAFE_HREF_RE.test(url)) return false;
  return PHOTO_URL_RE.test(url);
}

/**
 * Validate a canonical profile href.
 * Must start with / or https://www.fixeo.ma/. No unsafe schemes.
 * @param {string} href
 * @returns {boolean}
 */
function isValidProfileHref(href) {
  if (typeof href !== 'string' || !href) return false;
  if (UNSAFE_HREF_RE.test(href)) return false;
  return href.startsWith('/') || href.startsWith('https://www.fixeo.ma/');
}

// ── Description truth-guard pipeline (v3-a2) ─────────────────────────────────

/**
 * normalise() — mirror of content-guard's internal _normalise():
 * lowercase + collapse apostrophe variants.
 * Must stay in sync with content-guard.js _normalise() implementation.
 * @param {string} s
 * @returns {string}
 */
function _normalise(s) {
  return s.toLowerCase().replace(/[\u2019\u2018']/g, "'");
}

/**
 * plainTextDesc() — Phase 1+2 of the description pipeline.
 * Strips HTML tags and normalizes whitespace to produce plain text.
 * Does NOT remove any content-bearing phrases. Does NOT truncate.
 * @param {string|null|undefined} raw
 * @returns {string} plain text, may be empty string
 */
function plainTextDesc(raw) {
  if (!raw) return '';
  let s = String(raw);
  // Strip HTML tags — no risk of injection, output is plain text
  s = s.replace(/<[^>]*>/g, ' ');
  // Normalize whitespace
  s = s.replace(/\s+/g, ' ').trim();
  return s;
}

/**
 * descriptionForCard() — Full description truth-guard pipeline.
 *
 * Pipeline (v3-a2 — DETECTION + OMISSION, no surgical rewrite):
 *   1. plainTextDesc(): strip HTML, normalize whitespace
 *   2. Check resulting plain text against content-guard BANNED_TERMS
 *   3. If ANY banned term found: return null (caller omits description block)
 *   4. If clean: escape and truncate to DESC_MAX_LENGTH chars
 *   5. Return escaped, safe, truncated string
 *
 * This replaces the old sanitizeDesc() which removed banned phrases
 * and could produce mutilated sentences like "Artisan disponible"
 * from an input of "Artisan vérifié disponible immédiatement".
 *
 * @param {string|null|undefined} raw  — raw description from DB
 * @returns {string|null}
 *   string — safe, escaped, display-ready
 *   null   — description contained a banned term; omit the block entirely
 */
function descriptionForCard(raw) {
  // Phase 1+2: strip HTML, normalize whitespace
  const plain = plainTextDesc(raw);

  // Empty — nothing to show
  if (!plain) return null;

  // Phase 3: truth-guard check against content-guard BANNED_TERMS
  const normalised = _normalise(plain);
  for (const term of BANNED_TERMS) {
    if (normalised.includes(term)) {
      // Banned term detected — omit description entirely (no rewrite, no fragment)
      return null;
    }
  }

  // Phase 4: truncate clean plain text
  let safe = plain;
  if (safe.length > DESC_MAX_LENGTH) {
    safe = safe.slice(0, DESC_MAX_LENGTH).replace(/\s+\S*$/, '').trim() + '\u2026';
  }

  // Phase 5: escape for HTML output
  return esc(safe);
}

// ── Service label / icon helpers ──────────────────────────────────────────────

function svcLabel(slug) {
  const normalized = (slug || '').toLowerCase().trim();
  return SVC_LABELS[normalized] || (slug ? slug.charAt(0).toUpperCase() + slug.slice(1) : '');
}

function svcIcon(slug) {
  const normalized = (slug || '').toLowerCase().trim();
  return SVC_ICONS[normalized] || '🔧';
}

// ── Profile URL builder (v3-a2 — publicSlug ONLY) ────────────────────────────

/**
 * Build the canonical profile URL for a V3 card.
 *
 * v3-a2: publicSlug is the ONLY source for a profile CTA.
 * Legacy /artisan-profile.html?id= is NOT generated by V3.
 *
 * Strategy:
 *   valid publicSlug → /artisan/{publicSlug}
 *   missing/invalid  → null (card renders without profile CTA)
 *
 * @param {string|null} publicSlug
 * @returns {string|null}
 */
function buildProfileHref(publicSlug) {
  if (isValidSlug(publicSlug)) {
    return '/artisan/' + publicSlug;
  }
  return null;
}

// ── Photo / fallback builder ──────────────────────────────────────────────────

/**
 * Build the avatar section HTML.
 * Strategy:
 *   1. Real photo URL (must be valid HTTPS, from photo_url field)
 *   2. Initials fallback: first letter of name on gradient surface
 * No gender/race/appearance assumptions. No illustrative hero injection
 * (that is a runtime JS concern — fixeo-heroes.js not available at gen time).
 * @param {string|null} photoUrl  — validated HTTPS photo URL or null
 * @param {string}      name      — already HTML-escaped artisan name
 * @param {string}      catSlug   — service category slug (for CSS data-category)
 * @param {string}      catIcon   — emoji for badge
 * @returns {string} HTML
 */
function buildAvatarHtml(photoUrl, name, catSlug, catIcon) {
  const escapedCat  = esc(catSlug);
  const escapedIcon = esc(catIcon);

  let imgHtml;
  let avatarState;

  if (photoUrl && isValidPhotoUrl(photoUrl)) {
    avatarState = 'real-photo';
    imgHtml = ''
      + '<img class="fxseo-card-v3__avatar-img"'
      + ' src="' + esc(photoUrl) + '"'
      + ' alt="Photo de ' + name + '"'
      + ' width="56" height="56" loading="lazy" decoding="async"'
      + ' data-avatar-type="real-photo"'
      + '>';
  } else {
    avatarState = 'initials';
    // De-escape HTML entities to get the raw first character
    const rawName = String(name || '').replace(/&[a-z]+;/gi, '').replace(/&#\d+;/gi, '');
    const initial = rawName.trim().charAt(0).toUpperCase() || 'A';
    imgHtml = '<span class="fxseo-card-v3__avatar-initials" aria-hidden="true">'
      + esc(initial)
      + '</span>';
  }

  return '<div class="fxseo-card-v3__avatar" data-category="' + escapedCat + '" data-avatar-state="' + avatarState + '" aria-hidden="true">'
    + imgHtml
    + '<span class="fxseo-card-v3__avatar-badge" aria-hidden="true">' + escapedIcon + '</span>'
    + '</div>';
}

// ── Price block builder ───────────────────────────────────────────────────────

/**
 * Build price display HTML.
 * Shows price only when actual data is present (price_from or price_label).
 * Never invents or defaults a price. No guaranteed/fixed-price wording.
 *
 * price_label (pre-formatted DB string) takes priority over price_from.
 * "Tarif indicatif" hint added when deriving from price_from — makes
 * clear this is an indicative, not a guaranteed/fixed price.
 *
 * @param {number|null}  priceFrom   — e.g. 120
 * @param {string|null}  priceLabel  — e.g. "À partir de 120 DH"
 * @returns {string} HTML or empty string
 */
function buildPriceHtml(priceFrom, priceLabel) {
  let main = '';
  let hint = '';

  if (priceLabel && String(priceLabel).trim()) {
    // DB already has a pre-formatted string — use as-is, no hint
    main = String(priceLabel).trim();
    hint = '';
  } else if (priceFrom != null && priceFrom > 0) {
    main = '\u00c0 partir de\u00a0' + Math.round(priceFrom) + '\u00a0MAD';
    hint = 'Tarif indicatif'; // explicit: not a fixed or guaranteed price
  }

  if (!main) return '';

  return '<div class="fxseo-card-v3__price">'
    + '<span class="fxseo-card-v3__price-main">' + esc(main) + '</span>'
    + (hint ? '<span class="fxseo-card-v3__price-hint">' + esc(hint) + '</span>' : '')
    + '</div>';
}

// ── Trust row builder ─────────────────────────────────────────────────────────

// SVG icons (inline — mirrors fixeo-artisan-directory-v1.js / fixeo-local-flagship-v1.js)
const SVG_DIRECTORY = '<svg aria-hidden="true" focusable="false" xmlns="http://www.w3.org/2000/svg" width="13" height="13" viewBox="0 0 14 14" fill="none">'
  + '<rect x="2" y="1" width="10" height="12" rx="1.5" stroke="currentColor" stroke-width="1.3" fill="none"/>'
  + '<line x1="4.5" y1="4.5" x2="9.5" y2="4.5" stroke="currentColor" stroke-width="1.1" stroke-linecap="round"/>'
  + '<line x1="4.5" y1="7" x2="9.5" y2="7" stroke="currentColor" stroke-width="1.1" stroke-linecap="round"/>'
  + '<line x1="4.5" y1="9.5" x2="7.5" y2="9.5" stroke="currentColor" stroke-width="1.1" stroke-linecap="round"/>'
  + '</svg>';

const SVG_PAYMENT = '<svg aria-hidden="true" focusable="false" xmlns="http://www.w3.org/2000/svg" width="13" height="13" viewBox="0 0 14 14" fill="none">'
  + '<circle cx="7" cy="7.5" r="4.5" stroke="currentColor" stroke-width="1.3" fill="none"/>'
  + '<path d="M7 4.5 L7 2 M7 2 L5.5 3.5 M7 2 L8.5 3.5" stroke="currentColor" stroke-width="1.1" stroke-linecap="round" stroke-linejoin="round"/>'
  + '<line x1="5.5" y1="7.5" x2="8.5" y2="7.5" stroke="currentColor" stroke-width="1.1" stroke-linecap="round"/>'
  + '</svg>';

function buildTrustHtml() {
  return '<div class="fxseo-card-v3__trust" role="list">'
    + '<span class="fxseo-card-v3__trust-item" role="listitem">'
    + '<span class="fxseo-card-v3__trust-icon">' + SVG_DIRECTORY + '</span>'
    + 'Profil r\u00e9f\u00e9renc\u00e9 sur FIXEO'
    + '</span>'
    + '<span class="fxseo-card-v3__trust-item" role="listitem">'
    + '<span class="fxseo-card-v3__trust-icon">' + SVG_PAYMENT + '</span>'
    + 'Paiement apr\u00e8s intervention'
    + '</span>'
    + '</div>';
}

// ── Main export ───────────────────────────────────────────────────────────────

/**
 * buildArtisanCard — render a canonical FIXEO V3 artisan card.
 *
 * PUBLIC FIELD CONTRACT (v3-a2)
 * ──────────────────────────────
 * REQUIRED:
 *   name         {string}         Artisan display name (public). Must be non-empty.
 *   serviceLabel {string}         Human label: "Plomberie", "Électricité", etc.
 *   cityLabel    {string}         Human city name: "Casablanca", "Rabat", etc.
 *
 * OPTIONAL (all safe to omit — card degrades gracefully):
 *   serviceSlug  {string}         Slug for CSS data-category + icon lookup.
 *                                 E.g. "plomberie", "electricite".
 *                                 Defaults to empty (generic icon).
 *   photoUrl     {string|null}    Public HTTPS photo URL.
 *                                 Validated: must start with https://.
 *                                 Rejected: data:, javascript:, non-HTTPS.
 *                                 Omit if not a confirmed public-safe URL.
 *   publicSlug   {string|null}    Artisan's public_slug from Supabase.
 *                                 Used to build /artisan/{slug} clean URL.
 *                                 Must match /^[a-z0-9][a-z0-9-]{2,118}[a-z0-9]$/.
 *                                 ONLY source for profile CTA in V3.
 *   description  {string|null}    Public description from Supabase.
 *                                 Truth-guarded: HTML stripped, then checked
 *                                 against content-guard BANNED_TERMS.
 *                                 If any banned term found: description omitted.
 *                                 If clean: escaped and truncated at DESC_MAX_LENGTH.
 *   priceFrom    {number|null}    Numeric price floor (MAD). E.g. 120.
 *                                 Rendered as "À partir de 120 MAD · Tarif indicatif".
 *                                 Never rendered when null/zero/negative.
 *   priceLabel   {string|null}    Pre-formatted price string from DB.
 *                                 Takes precedence over priceFrom when present.
 *
 * DERIVED (computed internally — do not pass):
 *   profileHref    — built from publicSlug only (v3-a2: no id fallback)
 *   catIcon        — looked up from serviceSlug
 *   descriptionOut — computed from description via descriptionForCard()
 *
 * FORBIDDEN (hard throw if passed):
 *   id / legacy_id / _supabase_id — internal DB identifiers.
 *     In v3-a2: id removed from API. Its former role (legacy profile URL
 *     fallback) is not an approved V3 internal-link strategy.
 *   phone / telephone       — private contact
 *   email                   — private contact
 *   owner_user_id           — auth / admin
 *   verified (boolean)      — never show "artisan vérifié" badge
 *   verifie                 — same
 *   claim_status            — internal state
 *   onboarding_completed    — internal state
 *   commission              — commercial/internal
 *   pricing_margin          — commercial/internal
 *   admin_notes             — internal
 *   response_time_min       — cannot guarantee; never show response time claims
 *   responseTime            — same
 *   rating / note           — not shown (product-truth decision)
 *   reviews / reviewCount / avis — not shown
 *   availability / disponibilite / available — not shown
 *   created_at / updated_at — internal timestamps
 *
 * @param {object} opts
 * @param {string}            opts.name
 * @param {string}            opts.serviceLabel
 * @param {string}            opts.cityLabel
 * @param {string}           [opts.serviceSlug]
 * @param {string|null}      [opts.photoUrl]
 * @param {string|null}      [opts.publicSlug]
 * @param {string|null}      [opts.description]
 * @param {number|null}      [opts.priceFrom]
 * @param {string|null}      [opts.priceLabel]
 * @returns {string} HTML string for one artisan card
 */
function buildArtisanCard(opts) {
  if (!opts || typeof opts !== 'object') {
    throw new TypeError('artisan-card-v3: opts must be a plain object');
  }

  // ── Validate required fields ────────────────────────────────────────────────

  const name = String(opts.name || '').trim();
  if (!name) throw new Error('artisan-card-v3: name is required and must be non-empty');

  const serviceLabel = String(opts.serviceLabel || '').trim();
  if (!serviceLabel) throw new Error('artisan-card-v3: serviceLabel is required and must be non-empty');

  const cityLabel = String(opts.cityLabel || '').trim();
  if (!cityLabel) throw new Error('artisan-card-v3: cityLabel is required and must be non-empty');

  // ── Validate forbidden fields ───────────────────────────────────────────────

  const FORBIDDEN = [
    // v3-a2: id removed from API — not an approved V3 internal-link strategy
    'id', 'legacy_id', '_supabase_id',
    'phone', 'telephone', 'email',
    'owner_user_id',
    'verified', 'verifie',
    'claim_status', 'onboarding_completed',
    'commission', 'pricing_margin', 'admin_notes',
    'response_time_min', 'responseTime',
    'rating', 'note', 'reviews', 'reviewCount', 'avis',
    'availability', 'disponibilite', 'available',
    'created_at', 'updated_at',
  ];

  FORBIDDEN.forEach(field => {
    if (Object.prototype.hasOwnProperty.call(opts, field)) {
      throw new Error('artisan-card-v3: forbidden field "' + field + '" must not be passed to buildArtisanCard');
    }
  });

  // ── Optional fields ─────────────────────────────────────────────────────────

  const serviceSlug = String(opts.serviceSlug || '').toLowerCase().trim();
  const photoUrl    = opts.photoUrl   || null;
  const publicSlug  = opts.publicSlug || null;
  const description = opts.description || null;
  const priceFrom   = (opts.priceFrom != null && Number.isFinite(Number(opts.priceFrom)) && Number(opts.priceFrom) > 0)
    ? Number(opts.priceFrom) : null;
  const priceLabel  = opts.priceLabel || null;

  // ── Derived values ──────────────────────────────────────────────────────────

  const catSlug      = serviceSlug || 'autre';
  const catIcon      = svcIcon(catSlug);
  const catLabel     = serviceLabel;

  const escapedName     = esc(name);
  const escapedCity     = esc(cityLabel);
  const escapedCatLabel = esc(catLabel);

  // v3-a2: publicSlug only — no id fallback
  const profile = buildProfileHref(publicSlug);

  // v3-a2: truth-guard pipeline — returns escaped string or null
  const descOut = descriptionForCard(description);

  // ── Build sub-sections ──────────────────────────────────────────────────────

  const avatarHtml = buildAvatarHtml(photoUrl, escapedName, catSlug, catIcon);

  // descOut is already escaped (by descriptionForCard) — do NOT double-escape
  const descHtml = descOut !== null
    ? '<p class="fxseo-card-v3__desc">' + descOut + '</p>'
    : '';

  const priceHtml = buildPriceHtml(priceFrom, priceLabel);
  const trustHtml = buildTrustHtml();

  // Profile CTA — only rendered when a valid canonical slug URL exists
  let profileCtaHtml = '';
  if (profile && isValidProfileHref(profile)) {
    profileCtaHtml = '<a class="fxseo-card-v3__profile-link"'
      + ' href="' + esc(profile) + '"'
      + ' aria-label="Voir le profil de ' + escapedName + ', ' + escapedCatLabel + ' \u00e0 ' + escapedCity + '">'
      + 'Voir le profil\u00a0\u203a'
      + '</a>';
  }

  // ── Assemble card ───────────────────────────────────────────────────────────

  return '<article class="fxseo-card-v3"'
    + ' aria-label="' + escapedName + ', ' + escapedCatLabel + ' \u00e0 ' + escapedCity + '">'

    // Header: avatar + identity
    + '<div class="fxseo-card-v3__header">'
    + avatarHtml
    + '<div class="fxseo-card-v3__identity">'
    + '<h3 class="fxseo-card-v3__name">' + escapedName + '</h3>'
    + '<div class="fxseo-card-v3__meta">'
    + '<span class="fxseo-card-v3__meta-service">'
    + esc(catIcon) + '\u00a0' + escapedCatLabel
    + '</span>'
    + '<span class="fxseo-card-v3__meta-sep" aria-hidden="true">\u00b7</span>'
    + '<span class="fxseo-card-v3__meta-city">'
    + '\uD83D\uDCCD\u00a0' + escapedCity
    + '</span>'
    + '</div>'
    + '</div>'
    + '</div>'

    // Description (optional — omitted if null or if truth-guard found banned term)
    + descHtml

    // Trust rows
    + trustHtml

    // Action area: optional price + optional profile link
    + '<div class="fxseo-card-v3__action">'
    + '<div class="fxseo-card-v3__divider" aria-hidden="true"></div>'
    + priceHtml
    + profileCtaHtml
    + '</div>'

    + '</article>';
}

// ── Module exports ────────────────────────────────────────────────────────────

module.exports = {
  buildArtisanCard,
  // Expose internals for testing only
  _esc:                esc,
  _plainTextDesc:      plainTextDesc,
  _descriptionForCard: descriptionForCard,
  _isValidSlug:        isValidSlug,
  _isValidPhotoUrl:    isValidPhotoUrl,
  _isValidProfileHref: isValidProfileHref,
  _buildProfileHref:   buildProfileHref,
  _buildPriceHtml:     buildPriceHtml,
  _svcLabel:           svcLabel,
  _svcIcon:            svcIcon,
};
