const {test}=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path');
const {PGlite}=require('@electric-sql/pglite');
test('Masonry confirmation, strict trade dispatch and settlement retain approved amounts',async()=>{
 const db=new PGlite();try{
 await db.exec(`CREATE ROLE anon; CREATE ROLE authenticated; CREATE ROLE service_role;
 CREATE TABLE artisans(owner_user_id uuid,full_name text,name text,phone_public text,phone text,source text,claimed boolean,claim_status text,photo_url text,is_public boolean,id uuid PRIMARY KEY DEFAULT gen_random_uuid(),city text,service_category text,work_zone text,availability text,review_count integer,rating numeric,updated_at timestamptz);
 CREATE TABLE service_requests(target_artisan_id uuid,id uuid PRIMARY KEY DEFAULT gen_random_uuid(),service_category text,city text,description text,client_phone text,urgency text,status text,idempotency_key text,tracking_ref text,guest_token_hash text);
 CREATE TABLE estimator_context_redemptions(context_id text PRIMARY KEY,outcome_type text,service_code text,session_id text,amount_mad integer,state text,acquired_at timestamptz,service_request_id uuid,committed_at timestamptz,failed_at timestamptz,failure_reason text,booking_ref text,order_id text);
 CREATE TABLE missions(id uuid PRIMARY KEY DEFAULT gen_random_uuid(),request_id text,artisan_profile_id uuid,status text,agreed_price numeric,final_price numeric,commission_amount numeric);
 CREATE FUNCTION set_commission_amount() RETURNS trigger LANGUAGE plpgsql AS $$ BEGIN NEW.commission_amount:=coalesce(round(coalesce(NEW.final_price,NEW.agreed_price)*0.15,2),0);RETURN NEW;END $$;
 CREATE TRIGGER trg_set_commission_amount BEFORE INSERT OR UPDATE ON missions FOR EACH ROW EXECUTE FUNCTION set_commission_amount();
 INSERT INTO missions(request_id,agreed_price) VALUES('legacy',300);
 GRANT USAGE ON SCHEMA public TO anon,authenticated,service_role;
 GRANT ALL ON ALL TABLES IN SCHEMA public TO service_role,authenticated;`);
 for(const file of ['20260921005143_vap_bp33_offers_foundation.sql','20260921012731_vap_booking_settlement_binding.sql','20260921090058_garden_vap_confirmation.sql','20260921091341_tile_vap_confirmation.sql']) await db.exec('BEGIN;'+fs.readFileSync(path.join(__dirname,'../../supabase/migrations',file),'utf8')+'COMMIT;');
 await db.exec(fs.readFileSync(path.join(__dirname,'fixtures/dispatch-request-live-20260921.sql'),'utf8'));
 await db.exec(fs.readFileSync(path.join(__dirname,'fixtures/category-resolution-live-20260921.sql'),'utf8'));
 await db.exec(fs.readFileSync(path.join(__dirname,'../../supabase/migrations/20260921100804_masonry_vap_confirmation.sql'),'utf8'));
 await db.exec("INSERT INTO artisans(city,service_category,availability,review_count,rating,updated_at) VALUES ('Rabat','Carrelage','available',500,5,now()),('Rabat','Maçonnerie','available',0,0,now());");
 const id=(await db.query(`INSERT INTO fixeo_pricing_offers_v1(offer_key,pricing_version,currency,service_code,catalogue_version,city,scope,vap_minor,materials_minor,commission_minor,client_total_minor,expires_at) VALUES(gen_random_uuid(),'vap-bp33-v1','MAD','maconnerie.reprise_enduit','test','rabat','{"context_id":"fxctx-aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa","session_id":"session","outcome_type":"PRICE_READY"}',50000,0,7500,57500,now()+interval '15 minutes') RETURNING id`)).rows[0].id;
 const args=['fxctx-'+'a'.repeat(32),'PRICE_READY','maconnerie.reprise_enduit','session','575','rabat','0612345678','Test only','FX-TEST','a'.repeat(64),id];
 const sql='SELECT confirm_estimator_request_vap_v1('+args.map((_,i)=>'$'+(i+1)).join(',')+') AS r';
 await db.exec('SET ROLE service_role');
 let result=(await db.query(sql,args)).rows[0].r;assert.equal(result.ok,true);const request=result.request_id;assert.equal(result.service_category,'maconnerie');
 assert.equal((await db.query(sql,args)).rows[0].r.replayed,true);
 const bad=[...args];bad[4]='360';assert.equal((await db.query(sql,bad)).rows[0].r.reason,'offer_mismatch');
 const preview=(await db.query('SELECT * FROM dispatch_preview_v21($1)',[request])).rows;assert.equal(preview.length,1);assert.equal(preview[0].artisan_category,'Maçonnerie');
 const dispatched=(await db.query('SELECT dispatch_request_v1($1) AS r',[request])).rows[0].r;assert.equal(dispatched.ok,true);
 const mission=(await db.query('SELECT * FROM missions WHERE id=$1',[dispatched.mission_id])).rows[0];
 assert.equal((await db.query('SELECT service_category FROM artisans WHERE id=$1',[mission.artisan_profile_id])).rows[0].service_category,'Maçonnerie');
 assert.equal(mission.agreed_price,'575.0000000000000000');assert.equal(Number(mission.commission_amount),75);
 await db.query('UPDATE missions SET final_price=575 WHERE id=$1',[mission.id]);
 await db.query('UPDATE missions SET final_price=575 WHERE id=$1',[mission.id]);
 await assert.rejects(db.query('UPDATE missions SET final_price=400 WHERE id=$1',[mission.id]));
 await assert.rejects(db.query('UPDATE missions SET pricing_offer_id=NULL WHERE id=$1',[mission.id]));
 await assert.rejects(db.query('UPDATE service_requests SET pricing_offer_id=NULL WHERE id=$1',[request]));
 await db.exec('RESET ROLE; SET ROLE authenticated');
 await assert.rejects(db.query(sql,args));
 await assert.rejects(db.query("INSERT INTO missions(request_id,status) VALUES($1,'pending')",[request]));
 await db.query("UPDATE missions SET status='validated' WHERE id=$1",[mission.id]);
 assert.equal(Number((await db.query('SELECT commission_amount FROM missions WHERE id=$1',[mission.id])).rows[0].commission_amount),75);
 await db.exec('RESET ROLE');
 const legacyRequest=(await db.query("INSERT INTO service_requests(service_category,city,status,description) VALUES('maconnerie','Rabat','new','Legacy compatibility') RETURNING id")).rows[0].id;
 const legacyDispatch=(await db.query('SELECT dispatch_request_v1($1) AS r',[legacyRequest])).rows[0].r;assert.equal(legacyDispatch.ok,true);
 assert.equal((await db.query('SELECT service_category FROM artisans WHERE id=$1',[legacyDispatch.artisan_id])).rows[0].service_category,'Carrelage');
 assert.equal(Number((await db.query("SELECT commission_amount FROM missions WHERE request_id='legacy'")).rows[0].commission_amount),45);
 }finally{await db.close();}
});
