-- AUTH SECURITY P0 -- production read-only catalog evidence; no writes.
SELECT c.relname table_name, r.rolname role_name,
  array_agg(p.priv ORDER BY p.priv) FILTER (WHERE has_table_privilege(r.rolname,c.oid,p.priv)) privileges
FROM pg_class c JOIN pg_namespace n ON n.oid=c.relnamespace
CROSS JOIN pg_roles r CROSS JOIN unnest(ARRAY['SELECT','INSERT','UPDATE','DELETE','TRUNCATE','REFERENCES','TRIGGER','MAINTAIN']) p(priv)
WHERE n.nspname='public' AND c.relname IN ('users','profiles','service_requests','missions','artisans','artisan_profiles','notifications','enterprise_accounts','enterprise_members','enterprise_sites','enterprise_member_sites','enterprise_request_context','enterprise_leads','estimator_context_redemptions')
AND r.rolname IN ('anon','authenticated','service_role')
GROUP BY c.relname,r.rolname ORDER BY 1,2;
SELECT pol.polrelid::regclass::text table_name,pol.polname,att.attname,pg_get_expr(pol.polqual,pol.polrelid) using_expr,pg_get_expr(pol.polwithcheck,pol.polrelid) check_expr FROM pg_depend d JOIN pg_policy pol ON d.classid='pg_policy'::regclass AND d.objid=pol.oid JOIN pg_attribute att ON att.attrelid=d.refobjid AND att.attnum=d.refobjsubid WHERE d.refclassid='pg_class'::regclass AND d.refobjid='public.profiles'::regclass AND att.attname='role' ORDER BY 1,2;
SELECT 'test_table_columns' section,jsonb_agg(to_jsonb(x)) evidence FROM (SELECT c.relname table_name,a.attname column_name,format_type(a.atttypid,a.atttypmod) sql_type FROM pg_attribute a JOIN pg_class c ON c.oid=a.attrelid JOIN pg_namespace n ON n.oid=c.relnamespace WHERE n.nspname='public' AND c.relname IN ('users','profiles','service_requests','missions','artisans','artisan_profiles','notifications','enterprise_accounts','enterprise_members','enterprise_sites','enterprise_member_sites','enterprise_request_context','enterprise_leads','estimator_context_redemptions') AND a.attnum>0 AND NOT a.attisdropped ORDER BY c.relname,a.attnum)x
UNION ALL SELECT 'enterprise_and_onboarding_function_fingerprints',jsonb_agg(to_jsonb(x)) FROM (SELECT n.nspname,p.proname,pg_get_function_identity_arguments(p.oid) arguments,p.proacl,md5(pg_get_functiondef(p.oid)) definition_md5 FROM pg_proc p JOIN pg_namespace n ON n.oid=p.pronamespace WHERE n.nspname IN ('public','fixeo_private') AND (p.proname LIKE '%enterprise%' OR p.proname IN ('register_new_artisan','approve_artisan_claim')))x
UNION ALL SELECT 'enterprise_helper_definitions',jsonb_agg(to_jsonb(x)) FROM (SELECT p.proname,pg_get_functiondef(p.oid) definition FROM pg_proc p JOIN pg_namespace n ON n.oid=p.pronamespace WHERE n.nspname='fixeo_private' AND p.proname IN ('_fixeo_is_enterprise_member','_fixeo_is_enterprise_manager','_fixeo_can_access_enterprise_site'))x;

SELECT 'baseline' section,jsonb_build_object('captured_at',clock_timestamp(),'database',current_database(),'server_version',current_setting('server_version'),'server_version_num',current_setting('server_version_num')) evidence
UNION ALL SELECT 'identity_counts',jsonb_build_object('auth_users',(SELECT count(*) FROM auth.users),'public_users',(SELECT count(*) FROM public.users),'public_profiles',(SELECT count(*) FROM public.profiles),'users_without_profiles',(SELECT count(*) FROM public.users u LEFT JOIN public.profiles p ON p.id=u.id WHERE p.id IS NULL),'profiles_without_users',(SELECT count(*) FROM public.profiles p LEFT JOIN public.users u ON u.id=p.id WHERE u.id IS NULL),'auth_without_users',(SELECT count(*) FROM auth.users a LEFT JOIN public.users u ON u.id=a.id WHERE u.id IS NULL),'role_mismatches',(SELECT count(*) FROM public.users u JOIN public.profiles p ON p.id=u.id WHERE p.role IS DISTINCT FROM u.role),'missing_profile_roles',(SELECT jsonb_agg(x) FROM (SELECT u.role,count(*) FROM public.users u LEFT JOIN public.profiles p ON p.id=u.id WHERE p.id IS NULL GROUP BY u.role)x))
UNION ALL SELECT 'identity_tables',jsonb_agg(to_jsonb(x)) FROM (SELECT n.nspname,c.relname,pg_get_userbyid(c.relowner) owner,c.relrowsecurity,c.relforcerowsecurity,c.relacl FROM pg_class c JOIN pg_namespace n ON n.oid=c.relnamespace WHERE n.nspname='public' AND c.relname IN ('users','profiles'))x
UNION ALL SELECT 'identity_acl',jsonb_agg(to_jsonb(x)) FROM (SELECT c.relname,CASE WHEN a.grantee=0 THEN 'PUBLIC' ELSE pg_get_userbyid(a.grantee) END grantee,pg_get_userbyid(a.grantor) grantor,a.privilege_type,a.is_grantable FROM pg_class c JOIN pg_namespace n ON n.oid=c.relnamespace CROSS JOIN LATERAL aclexplode(coalesce(c.relacl,acldefault('r',c.relowner)))a WHERE n.nspname='public' AND c.relname IN ('users','profiles'))x
UNION ALL SELECT 'identity_column_acl',coalesce(jsonb_agg(to_jsonb(x)),'[]') FROM (SELECT c.relname,a.attname,a.attacl FROM pg_attribute a JOIN pg_class c ON c.oid=a.attrelid JOIN pg_namespace n ON n.oid=c.relnamespace WHERE n.nspname='public' AND c.relname IN ('users','profiles') AND a.attacl IS NOT NULL)x
UNION ALL SELECT 'identity_effective_grants',jsonb_agg(to_jsonb(x)) FROM (SELECT r.role_name,t.table_name,p.privilege,has_table_privilege(r.role_name,'public.'||t.table_name,p.privilege) allowed FROM unnest(ARRAY['anon','authenticated','service_role'])r(role_name) CROSS JOIN unnest(ARRAY['users','profiles'])t(table_name) CROSS JOIN unnest(ARRAY['SELECT','INSERT','UPDATE','DELETE','TRUNCATE','REFERENCES','TRIGGER','MAINTAIN'])p(privilege))x
UNION ALL SELECT 'identity_columns',jsonb_agg(to_jsonb(x)) FROM (SELECT table_name,column_name,data_type,is_nullable,column_default FROM information_schema.columns WHERE table_schema='public' AND table_name IN ('users','profiles') ORDER BY table_name,ordinal_position)x
UNION ALL SELECT 'identity_constraints',jsonb_agg(to_jsonb(x)) FROM (SELECT conrelid::regclass::text table_name,conname,pg_get_constraintdef(oid,true) definition FROM pg_constraint WHERE conrelid IN ('public.users'::regclass,'public.profiles'::regclass))x
UNION ALL SELECT 'all_policies',jsonb_agg(to_jsonb(x)) FROM (SELECT schemaname,tablename,policyname,permissive,roles,cmd,qual,with_check FROM pg_policies ORDER BY schemaname,tablename,policyname)x
UNION ALL SELECT 'identity_triggers',jsonb_agg(to_jsonb(x)) FROM (SELECT t.tgrelid::regclass::text table_name,t.tgname,t.tgenabled,pg_get_triggerdef(t.oid,true) definition,t.tgfoid::regprocedure::text function_name FROM pg_trigger t WHERE t.tgrelid IN ('auth.users'::regclass,'public.users'::regclass,'public.profiles'::regclass) AND NOT t.tgisinternal)x
UNION ALL SELECT 'authority_functions',jsonb_agg(to_jsonb(x)) FROM (SELECT n.nspname,p.proname,pg_get_function_identity_arguments(p.oid) arguments,pg_get_userbyid(p.proowner) owner,p.prosecdef,p.proconfig,p.proacl,pg_get_functiondef(p.oid) definition FROM pg_proc p JOIN pg_namespace n ON n.oid=p.pronamespace WHERE n.nspname IN ('public','fixeo_private') AND (p.proname IN ('is_admin','_fixeo_is_admin','handle_new_user','prevent_non_admin_role_change') OR (p.prosrc ~* 'profiles' AND p.prosrc ~* '(role|admin)')))x
UNION ALL SELECT 'role_membership',coalesce(jsonb_agg(to_jsonb(x)),'[]') FROM (SELECT pg_get_userbyid(member) member,pg_get_userbyid(roleid) parent,inherit_option,set_option,admin_option FROM pg_auth_members WHERE member IN (SELECT oid FROM pg_roles WHERE rolname IN ('anon','authenticated','service_role')))x
UNION ALL SELECT 'policy_function_dependencies',coalesce(jsonb_agg(to_jsonb(x)),'[]') FROM (SELECT pol.polrelid::regclass::text table_name,pol.polname,n.nspname function_schema,p.proname,p.prosecdef,p.proconfig,p.prosrc FROM pg_depend d JOIN pg_policy pol ON d.classid='pg_policy'::regclass AND d.objid=pol.oid JOIN pg_proc p ON d.refclassid='pg_proc'::regclass AND d.refobjid=p.oid JOIN pg_namespace n ON n.oid=p.pronamespace WHERE n.nspname NOT IN ('pg_catalog','auth','extensions') ORDER BY 1,2,3,4)x;

SELECT 'function_security' section,jsonb_agg(to_jsonb(x)) evidence FROM (SELECT n.nspname,p.proname,pg_get_function_identity_arguments(p.oid) args,pg_get_userbyid(p.proowner) owner,p.prosecdef,p.proconfig,p.proacl,md5(pg_get_functiondef(p.oid)) definition_md5 FROM pg_proc p JOIN pg_namespace n ON n.oid=p.pronamespace WHERE n.nspname IN ('public','fixeo_private') AND (p.proname ILIKE '%admin%' OR p.proname ILIKE '%role%' OR p.prosrc ~* 'profiles.{0,150}role'))x
UNION ALL SELECT 'schema_privileges',jsonb_agg(to_jsonb(x)) FROM (SELECT n.nspname,n.nspacl,r.rolname,has_schema_privilege(r.rolname,n.oid,'CREATE') can_create,has_schema_privilege(r.rolname,n.oid,'USAGE') can_use FROM pg_namespace n CROSS JOIN pg_roles r WHERE n.nspname IN ('public','fixeo_private') AND r.rolname IN ('anon','authenticated','service_role'))x
UNION ALL SELECT 'authority_dependents',coalesce(jsonb_agg(to_jsonb(x)),'[]') FROM (SELECT n.nspname,c.relname,pg_get_viewdef(c.oid) definition FROM pg_class c JOIN pg_namespace n ON n.oid=c.relnamespace WHERE c.relkind IN ('v','m') AND n.nspname IN ('public','fixeo_private') AND pg_get_viewdef(c.oid) ~* '(profiles|role|admin)')x;
